generatorName: java
inputSpec: ./spec/vertesia-openapi.json
outputDir: .

globalProperties:
  modelTests: "false"
  apiTests: "false"
  modelDocs: "false"
  apiDocs: "false"

nameMappings:
  additionalProperties: schemaAdditionalProperties

additionalProperties:
  enumClassPrefix: true
  enumUnknownDefaultCase: true
  disallowAdditionalPropertiesIfNotPresent: false
  hideGenerationTimestamp: true
  useJakartaEe: true
  invokerPackage: io.vertesia
  apiPackage: io.vertesia.api
  modelPackage: io.vertesia.model
  groupId: io.vertesia
  artifactId: vertesia-client
  artifactVersion: 1.2.0
  developerName: Vertesia
  developerEmail: contact@vertesia.com
  developerOrganization: Vertesia
  developerOrganizationUrl: https://www.vertesiahq.com
  scmConnection: scm:git:https://github.com/vertesia/vertesia-client-java.git
  scmDeveloperConnection: scm:git:https://github.com/vertesia/vertesia-client-java.git
  scmUrl: https://github.com/vertesia/vertesia-client-java
  implicitHeadersRegex: ^x-api-version$
  licenseName: Apache-2.0
  licenseUrl: https://www.apache.org/licenses/LICENSE-2.0
