/*
 * Vertesia API
 * The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` SDK for typed access from Node.js applications.
 *
 * The version of the OpenAPI document: 1.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.vertesia.api;

import com.google.gson.reflect.TypeToken;
import io.vertesia.ApiCallback;
import io.vertesia.ApiClient;
import io.vertesia.ApiException;
import io.vertesia.ApiResponse;
import io.vertesia.Configuration;
import io.vertesia.Pair;
import io.vertesia.model.CompleteTaskPayload;
import io.vertesia.model.CreateTaskPayload;
import io.vertesia.model.DeleteCountResult;
import io.vertesia.model.Task;
import io.vertesia.model.UpdateTaskPayload;
import java.lang.reflect.Type;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class TasksApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public TasksApi() {
        this(Configuration.getDefaultApiClient());
    }

    public TasksApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for cancelTask
     * @param taskId  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     * <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> The cancelled task. </td><td>  -  </td></tr>
     * <tr><td> 500 </td><td> Internal server error. </td><td>  -  </td></tr>
     * <tr><td> 4XX </td><td> Client error. </td><td>  -  </td></tr>
     * </table>
     */
    public okhttp3.Call cancelTaskCall(
            @jakarta.annotation.Nonnull String taskId, final ApiCallback _callback)
            throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {};

        // Determine Base Path to Use
        if (localCustomBaseUrl != null) {
            basePath = localCustomBaseUrl;
        } else if (localBasePaths.length > 0) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath =
                "/tasks/{taskId}/cancel"
                        .replace(
                                "{" + "taskId" + "}",
                                localVarApiClient.escapeString(taskId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {"application/json"};
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {};
        final String localVarContentType =
                localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {"bearerAuth", "OpenID"};
        return localVarApiClient.buildCall(
                basePath,
                localVarPath,
                "POST",
                localVarQueryParams,
                localVarCollectionQueryParams,
                localVarPostBody,
                localVarHeaderParams,
                localVarCookieParams,
                localVarFormParams,
                localVarAuthNames,
                _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call cancelTaskValidateBeforeCall(
            @jakarta.annotation.Nonnull String taskId, final ApiCallback _callback)
            throws ApiException {
        // verify the required parameter 'taskId' is set
        if (taskId == null) {
            throw new ApiException(
                    "Missing the required parameter 'taskId' when calling cancelTask(Async)");
        }

        return cancelTaskCall(taskId, _callback);
    }

    /**
     * Cancel a task
     * Cancels a pending or in-progress durable task.  **Required permissions:** &#x60;task:manage&#x60;
     * @param taskId  (required)
     * @return Task
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     * <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> The cancelled task. </td><td>  -  </td></tr>
     * <tr><td> 500 </td><td> Internal server error. </td><td>  -  </td></tr>
     * <tr><td> 4XX </td><td> Client error. </td><td>  -  </td></tr>
     * </table>
     */
    public Task cancelTask(@jakarta.annotation.Nonnull String taskId) throws ApiException {
        ApiResponse<Task> localVarResp = cancelTaskWithHttpInfo(taskId);
        return localVarResp.getData();
    }

    /**
     * Cancel a task
     * Cancels a pending or in-progress durable task.  **Required permissions:** &#x60;task:manage&#x60;
     * @param taskId  (required)
     * @return ApiResponse&lt;Task&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     * <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> The cancelled task. </td><td>  -  </td></tr>
     * <tr><td> 500 </td><td> Internal server error. </td><td>  -  </td></tr>
     * <tr><td> 4XX </td><td> Client error. </td><td>  -  </td></tr>
     * </table>
     */
    public ApiResponse<Task> cancelTaskWithHttpInfo(@jakarta.annotation.Nonnull String taskId)
            throws ApiException {
        okhttp3.Call localVarCall = cancelTaskValidateBeforeCall(taskId, null);
        Type localVarReturnType = new TypeToken<Task>() {}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Cancel a task (asynchronously)
     * Cancels a pending or in-progress durable task.  **Required permissions:** &#x60;task:manage&#x60;
     * @param taskId  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     * <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> The cancelled task. </td><td>  -  </td></tr>
     * <tr><td> 500 </td><td> Internal server error. </td><td>  -  </td></tr>
     * <tr><td> 4XX </td><td> Client error. </td><td>  -  </td></tr>
     * </table>
     */
    public okhttp3.Call cancelTaskAsync(
            @jakarta.annotation.Nonnull String taskId, final ApiCallback<Task> _callback)
            throws ApiException {

        okhttp3.Call localVarCall = cancelTaskValidateBeforeCall(taskId, _callback);
        Type localVarReturnType = new TypeToken<Task>() {}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    /**
     * Build call for completeTask
     * @param taskId  (required)
     * @param completeTaskPayload  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     * <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> The completed task. </td><td>  -  </td></tr>
     * <tr><td> 500 </td><td> Internal server error. </td><td>  -  </td></tr>
     * <tr><td> 4XX </td><td> Client error. </td><td>  -  </td></tr>
     * </table>
     */
    public okhttp3.Call completeTaskCall(
            @jakarta.annotation.Nonnull String taskId,
            @jakarta.annotation.Nonnull CompleteTaskPayload completeTaskPayload,
            final ApiCallback _callback)
            throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {};

        // Determine Base Path to Use
        if (localCustomBaseUrl != null) {
            basePath = localCustomBaseUrl;
        } else if (localBasePaths.length > 0) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = completeTaskPayload;

        // create path and map variables
        String localVarPath =
                "/tasks/{taskId}/complete"
                        .replace(
                                "{" + "taskId" + "}",
                                localVarApiClient.escapeString(taskId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {"application/json"};
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {"application/json"};
        final String localVarContentType =
                localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {"bearerAuth", "OpenID"};
        return localVarApiClient.buildCall(
                basePath,
                localVarPath,
                "POST",
                localVarQueryParams,
                localVarCollectionQueryParams,
                localVarPostBody,
                localVarHeaderParams,
                localVarCookieParams,
                localVarFormParams,
                localVarAuthNames,
                _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call completeTaskValidateBeforeCall(
            @jakarta.annotation.Nonnull String taskId,
            @jakarta.annotation.Nonnull CompleteTaskPayload completeTaskPayload,
            final ApiCallback _callback)
            throws ApiException {
        // verify the required parameter 'taskId' is set
        if (taskId == null) {
            throw new ApiException(
                    "Missing the required parameter 'taskId' when calling completeTask(Async)");
        }

        // verify the required parameter 'completeTaskPayload' is set
        if (completeTaskPayload == null) {
            throw new ApiException(
                    "Missing the required parameter 'completeTaskPayload' when calling completeTask(Async)");
        }

        return completeTaskCall(taskId, completeTaskPayload, _callback);
    }

    /**
     * Complete a task
     * Completes a durable task and, for agent ask tasks, signals the backing workflow with the submitted result. Process &#x60;human_task&#x60; nodes should be resumed through &#x60;POST /agents/{agentRunId}/answer-task&#x60; instead of this endpoint.
     * @param taskId  (required)
     * @param completeTaskPayload  (required)
     * @return Task
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     * <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> The completed task. </td><td>  -  </td></tr>
     * <tr><td> 500 </td><td> Internal server error. </td><td>  -  </td></tr>
     * <tr><td> 4XX </td><td> Client error. </td><td>  -  </td></tr>
     * </table>
     */
    public Task completeTask(
            @jakarta.annotation.Nonnull String taskId,
            @jakarta.annotation.Nonnull CompleteTaskPayload completeTaskPayload)
            throws ApiException {
        ApiResponse<Task> localVarResp = completeTaskWithHttpInfo(taskId, completeTaskPayload);
        return localVarResp.getData();
    }

    /**
     * Complete a task
     * Completes a durable task and, for agent ask tasks, signals the backing workflow with the submitted result. Process &#x60;human_task&#x60; nodes should be resumed through &#x60;POST /agents/{agentRunId}/answer-task&#x60; instead of this endpoint.
     * @param taskId  (required)
     * @param completeTaskPayload  (required)
     * @return ApiResponse&lt;Task&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     * <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> The completed task. </td><td>  -  </td></tr>
     * <tr><td> 500 </td><td> Internal server error. </td><td>  -  </td></tr>
     * <tr><td> 4XX </td><td> Client error. </td><td>  -  </td></tr>
     * </table>
     */
    public ApiResponse<Task> completeTaskWithHttpInfo(
            @jakarta.annotation.Nonnull String taskId,
            @jakarta.annotation.Nonnull CompleteTaskPayload completeTaskPayload)
            throws ApiException {
        okhttp3.Call localVarCall =
                completeTaskValidateBeforeCall(taskId, completeTaskPayload, null);
        Type localVarReturnType = new TypeToken<Task>() {}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Complete a task (asynchronously)
     * Completes a durable task and, for agent ask tasks, signals the backing workflow with the submitted result. Process &#x60;human_task&#x60; nodes should be resumed through &#x60;POST /agents/{agentRunId}/answer-task&#x60; instead of this endpoint.
     * @param taskId  (required)
     * @param completeTaskPayload  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     * <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> The completed task. </td><td>  -  </td></tr>
     * <tr><td> 500 </td><td> Internal server error. </td><td>  -  </td></tr>
     * <tr><td> 4XX </td><td> Client error. </td><td>  -  </td></tr>
     * </table>
     */
    public okhttp3.Call completeTaskAsync(
            @jakarta.annotation.Nonnull String taskId,
            @jakarta.annotation.Nonnull CompleteTaskPayload completeTaskPayload,
            final ApiCallback<Task> _callback)
            throws ApiException {

        okhttp3.Call localVarCall =
                completeTaskValidateBeforeCall(taskId, completeTaskPayload, _callback);
        Type localVarReturnType = new TypeToken<Task>() {}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    /**
     * Build call for createTask
     * @param createTaskPayload  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     * <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 201 </td><td> The created task. </td><td>  -  </td></tr>
     * <tr><td> 500 </td><td> Internal server error. </td><td>  -  </td></tr>
     * <tr><td> 4XX </td><td> Client error. </td><td>  -  </td></tr>
     * </table>
     */
    public okhttp3.Call createTaskCall(
            @jakarta.annotation.Nonnull CreateTaskPayload createTaskPayload,
            final ApiCallback _callback)
            throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {};

        // Determine Base Path to Use
        if (localCustomBaseUrl != null) {
            basePath = localCustomBaseUrl;
        } else if (localBasePaths.length > 0) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = createTaskPayload;

        // create path and map variables
        String localVarPath = "/tasks";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {"application/json"};
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {"application/json"};
        final String localVarContentType =
                localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {"bearerAuth", "OpenID"};
        return localVarApiClient.buildCall(
                basePath,
                localVarPath,
                "POST",
                localVarQueryParams,
                localVarCollectionQueryParams,
                localVarPostBody,
                localVarHeaderParams,
                localVarCookieParams,
                localVarFormParams,
                localVarAuthNames,
                _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call createTaskValidateBeforeCall(
            @jakarta.annotation.Nonnull CreateTaskPayload createTaskPayload,
            final ApiCallback _callback)
            throws ApiException {
        // verify the required parameter 'createTaskPayload' is set
        if (createTaskPayload == null) {
            throw new ApiException(
                    "Missing the required parameter 'createTaskPayload' when calling createTask(Async)");
        }

        return createTaskCall(createTaskPayload, _callback);
    }

    /**
     * Create a task
     * Creates a durable human task for a process or agent run. Callers must have &#x60;workflow:run&#x60; or &#x60;task:manage&#x60;.
     * @param createTaskPayload  (required)
     * @return Task
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     * <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 201 </td><td> The created task. </td><td>  -  </td></tr>
     * <tr><td> 500 </td><td> Internal server error. </td><td>  -  </td></tr>
     * <tr><td> 4XX </td><td> Client error. </td><td>  -  </td></tr>
     * </table>
     */
    public Task createTask(@jakarta.annotation.Nonnull CreateTaskPayload createTaskPayload)
            throws ApiException {
        ApiResponse<Task> localVarResp = createTaskWithHttpInfo(createTaskPayload);
        return localVarResp.getData();
    }

    /**
     * Create a task
     * Creates a durable human task for a process or agent run. Callers must have &#x60;workflow:run&#x60; or &#x60;task:manage&#x60;.
     * @param createTaskPayload  (required)
     * @return ApiResponse&lt;Task&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     * <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 201 </td><td> The created task. </td><td>  -  </td></tr>
     * <tr><td> 500 </td><td> Internal server error. </td><td>  -  </td></tr>
     * <tr><td> 4XX </td><td> Client error. </td><td>  -  </td></tr>
     * </table>
     */
    public ApiResponse<Task> createTaskWithHttpInfo(
            @jakarta.annotation.Nonnull CreateTaskPayload createTaskPayload) throws ApiException {
        okhttp3.Call localVarCall = createTaskValidateBeforeCall(createTaskPayload, null);
        Type localVarReturnType = new TypeToken<Task>() {}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Create a task (asynchronously)
     * Creates a durable human task for a process or agent run. Callers must have &#x60;workflow:run&#x60; or &#x60;task:manage&#x60;.
     * @param createTaskPayload  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     * <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 201 </td><td> The created task. </td><td>  -  </td></tr>
     * <tr><td> 500 </td><td> Internal server error. </td><td>  -  </td></tr>
     * <tr><td> 4XX </td><td> Client error. </td><td>  -  </td></tr>
     * </table>
     */
    public okhttp3.Call createTaskAsync(
            @jakarta.annotation.Nonnull CreateTaskPayload createTaskPayload,
            final ApiCallback<Task> _callback)
            throws ApiException {

        okhttp3.Call localVarCall = createTaskValidateBeforeCall(createTaskPayload, _callback);
        Type localVarReturnType = new TypeToken<Task>() {}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    /**
     * Build call for deleteTask
     * @param taskId  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     * <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Task deletion result. </td><td>  -  </td></tr>
     * <tr><td> 500 </td><td> Internal server error. </td><td>  -  </td></tr>
     * <tr><td> 4XX </td><td> Client error. </td><td>  -  </td></tr>
     * </table>
     */
    public okhttp3.Call deleteTaskCall(
            @jakarta.annotation.Nonnull String taskId, final ApiCallback _callback)
            throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {};

        // Determine Base Path to Use
        if (localCustomBaseUrl != null) {
            basePath = localCustomBaseUrl;
        } else if (localBasePaths.length > 0) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath =
                "/tasks/{taskId}"
                        .replace(
                                "{" + "taskId" + "}",
                                localVarApiClient.escapeString(taskId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {"application/json"};
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {};
        final String localVarContentType =
                localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {"bearerAuth", "OpenID"};
        return localVarApiClient.buildCall(
                basePath,
                localVarPath,
                "DELETE",
                localVarQueryParams,
                localVarCollectionQueryParams,
                localVarPostBody,
                localVarHeaderParams,
                localVarCookieParams,
                localVarFormParams,
                localVarAuthNames,
                _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call deleteTaskValidateBeforeCall(
            @jakarta.annotation.Nonnull String taskId, final ApiCallback _callback)
            throws ApiException {
        // verify the required parameter 'taskId' is set
        if (taskId == null) {
            throw new ApiException(
                    "Missing the required parameter 'taskId' when calling deleteTask(Async)");
        }

        return deleteTaskCall(taskId, _callback);
    }

    /**
     * Delete a task
     * Deletes a durable task by id.  **Required permissions:** &#x60;task:manage&#x60;
     * @param taskId  (required)
     * @return DeleteCountResult
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     * <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Task deletion result. </td><td>  -  </td></tr>
     * <tr><td> 500 </td><td> Internal server error. </td><td>  -  </td></tr>
     * <tr><td> 4XX </td><td> Client error. </td><td>  -  </td></tr>
     * </table>
     */
    public DeleteCountResult deleteTask(@jakarta.annotation.Nonnull String taskId)
            throws ApiException {
        ApiResponse<DeleteCountResult> localVarResp = deleteTaskWithHttpInfo(taskId);
        return localVarResp.getData();
    }

    /**
     * Delete a task
     * Deletes a durable task by id.  **Required permissions:** &#x60;task:manage&#x60;
     * @param taskId  (required)
     * @return ApiResponse&lt;DeleteCountResult&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     * <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Task deletion result. </td><td>  -  </td></tr>
     * <tr><td> 500 </td><td> Internal server error. </td><td>  -  </td></tr>
     * <tr><td> 4XX </td><td> Client error. </td><td>  -  </td></tr>
     * </table>
     */
    public ApiResponse<DeleteCountResult> deleteTaskWithHttpInfo(
            @jakarta.annotation.Nonnull String taskId) throws ApiException {
        okhttp3.Call localVarCall = deleteTaskValidateBeforeCall(taskId, null);
        Type localVarReturnType = new TypeToken<DeleteCountResult>() {}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Delete a task (asynchronously)
     * Deletes a durable task by id.  **Required permissions:** &#x60;task:manage&#x60;
     * @param taskId  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     * <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Task deletion result. </td><td>  -  </td></tr>
     * <tr><td> 500 </td><td> Internal server error. </td><td>  -  </td></tr>
     * <tr><td> 4XX </td><td> Client error. </td><td>  -  </td></tr>
     * </table>
     */
    public okhttp3.Call deleteTaskAsync(
            @jakarta.annotation.Nonnull String taskId,
            final ApiCallback<DeleteCountResult> _callback)
            throws ApiException {

        okhttp3.Call localVarCall = deleteTaskValidateBeforeCall(taskId, _callback);
        Type localVarReturnType = new TypeToken<DeleteCountResult>() {}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    /**
     * Build call for getTask
     * @param taskId  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     * <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> The requested task. </td><td>  -  </td></tr>
     * <tr><td> 500 </td><td> Internal server error. </td><td>  -  </td></tr>
     * <tr><td> 4XX </td><td> Client error. </td><td>  -  </td></tr>
     * </table>
     */
    public okhttp3.Call getTaskCall(
            @jakarta.annotation.Nonnull String taskId, final ApiCallback _callback)
            throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {};

        // Determine Base Path to Use
        if (localCustomBaseUrl != null) {
            basePath = localCustomBaseUrl;
        } else if (localBasePaths.length > 0) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath =
                "/tasks/{taskId}"
                        .replace(
                                "{" + "taskId" + "}",
                                localVarApiClient.escapeString(taskId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {"application/json"};
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {};
        final String localVarContentType =
                localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {"bearerAuth", "OpenID"};
        return localVarApiClient.buildCall(
                basePath,
                localVarPath,
                "GET",
                localVarQueryParams,
                localVarCollectionQueryParams,
                localVarPostBody,
                localVarHeaderParams,
                localVarCookieParams,
                localVarFormParams,
                localVarAuthNames,
                _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getTaskValidateBeforeCall(
            @jakarta.annotation.Nonnull String taskId, final ApiCallback _callback)
            throws ApiException {
        // verify the required parameter 'taskId' is set
        if (taskId == null) {
            throw new ApiException(
                    "Missing the required parameter 'taskId' when calling getTask(Async)");
        }

        return getTaskCall(taskId, _callback);
    }

    /**
     * Retrieve a task
     * Retrieves a single durable task by id.
     * @param taskId  (required)
     * @return Task
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     * <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> The requested task. </td><td>  -  </td></tr>
     * <tr><td> 500 </td><td> Internal server error. </td><td>  -  </td></tr>
     * <tr><td> 4XX </td><td> Client error. </td><td>  -  </td></tr>
     * </table>
     */
    public Task getTask(@jakarta.annotation.Nonnull String taskId) throws ApiException {
        ApiResponse<Task> localVarResp = getTaskWithHttpInfo(taskId);
        return localVarResp.getData();
    }

    /**
     * Retrieve a task
     * Retrieves a single durable task by id.
     * @param taskId  (required)
     * @return ApiResponse&lt;Task&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     * <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> The requested task. </td><td>  -  </td></tr>
     * <tr><td> 500 </td><td> Internal server error. </td><td>  -  </td></tr>
     * <tr><td> 4XX </td><td> Client error. </td><td>  -  </td></tr>
     * </table>
     */
    public ApiResponse<Task> getTaskWithHttpInfo(@jakarta.annotation.Nonnull String taskId)
            throws ApiException {
        okhttp3.Call localVarCall = getTaskValidateBeforeCall(taskId, null);
        Type localVarReturnType = new TypeToken<Task>() {}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Retrieve a task (asynchronously)
     * Retrieves a single durable task by id.
     * @param taskId  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     * <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> The requested task. </td><td>  -  </td></tr>
     * <tr><td> 500 </td><td> Internal server error. </td><td>  -  </td></tr>
     * <tr><td> 4XX </td><td> Client error. </td><td>  -  </td></tr>
     * </table>
     */
    public okhttp3.Call getTaskAsync(
            @jakarta.annotation.Nonnull String taskId, final ApiCallback<Task> _callback)
            throws ApiException {

        okhttp3.Call localVarCall = getTaskValidateBeforeCall(taskId, _callback);
        Type localVarReturnType = new TypeToken<Task>() {}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    /**
     * Build call for listTasks
     * @param status  (optional)
     * @param assignee  (optional)
     * @param runId  (optional)
     * @param sourceType  (optional)
     * @param limit  (optional)
     * @param offset  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     * <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Matching tasks. </td><td>  -  </td></tr>
     * <tr><td> 500 </td><td> Internal server error. </td><td>  -  </td></tr>
     * <tr><td> 4XX </td><td> Client error. </td><td>  -  </td></tr>
     * </table>
     */
    public okhttp3.Call listTasksCall(
            @jakarta.annotation.Nullable List<String> status,
            @jakarta.annotation.Nullable String assignee,
            @jakarta.annotation.Nullable String runId,
            @jakarta.annotation.Nullable String sourceType,
            @jakarta.annotation.Nullable BigDecimal limit,
            @jakarta.annotation.Nullable BigDecimal offset,
            final ApiCallback _callback)
            throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {};

        // Determine Base Path to Use
        if (localCustomBaseUrl != null) {
            basePath = localCustomBaseUrl;
        } else if (localBasePaths.length > 0) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/tasks";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (status != null) {
            localVarCollectionQueryParams.addAll(
                    localVarApiClient.parameterToPairs("multi", "status", status));
        }

        if (assignee != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("assignee", assignee));
        }

        if (runId != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("run_id", runId));
        }

        if (sourceType != null) {
            localVarQueryParams.addAll(
                    localVarApiClient.parameterToPair("source_type", sourceType));
        }

        if (limit != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("limit", limit));
        }

        if (offset != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("offset", offset));
        }

        final String[] localVarAccepts = {"application/json"};
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {};
        final String localVarContentType =
                localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {"bearerAuth", "OpenID"};
        return localVarApiClient.buildCall(
                basePath,
                localVarPath,
                "GET",
                localVarQueryParams,
                localVarCollectionQueryParams,
                localVarPostBody,
                localVarHeaderParams,
                localVarCookieParams,
                localVarFormParams,
                localVarAuthNames,
                _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call listTasksValidateBeforeCall(
            @jakarta.annotation.Nullable List<String> status,
            @jakarta.annotation.Nullable String assignee,
            @jakarta.annotation.Nullable String runId,
            @jakarta.annotation.Nullable String sourceType,
            @jakarta.annotation.Nullable BigDecimal limit,
            @jakarta.annotation.Nullable BigDecimal offset,
            final ApiCallback _callback)
            throws ApiException {
        return listTasksCall(status, assignee, runId, sourceType, limit, offset, _callback);
    }

    /**
     * List tasks
     * Lists durable tasks visible to the current principal, with optional filters for status, assignee, run id, and source type.
     * @param status  (optional)
     * @param assignee  (optional)
     * @param runId  (optional)
     * @param sourceType  (optional)
     * @param limit  (optional)
     * @param offset  (optional)
     * @return List&lt;Task&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     * <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Matching tasks. </td><td>  -  </td></tr>
     * <tr><td> 500 </td><td> Internal server error. </td><td>  -  </td></tr>
     * <tr><td> 4XX </td><td> Client error. </td><td>  -  </td></tr>
     * </table>
     */
    public List<Task> listTasks(
            @jakarta.annotation.Nullable List<String> status,
            @jakarta.annotation.Nullable String assignee,
            @jakarta.annotation.Nullable String runId,
            @jakarta.annotation.Nullable String sourceType,
            @jakarta.annotation.Nullable BigDecimal limit,
            @jakarta.annotation.Nullable BigDecimal offset)
            throws ApiException {
        ApiResponse<List<Task>> localVarResp =
                listTasksWithHttpInfo(status, assignee, runId, sourceType, limit, offset);
        return localVarResp.getData();
    }

    /**
     * List tasks
     * Lists durable tasks visible to the current principal, with optional filters for status, assignee, run id, and source type.
     * @param status  (optional)
     * @param assignee  (optional)
     * @param runId  (optional)
     * @param sourceType  (optional)
     * @param limit  (optional)
     * @param offset  (optional)
     * @return ApiResponse&lt;List&lt;Task&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     * <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Matching tasks. </td><td>  -  </td></tr>
     * <tr><td> 500 </td><td> Internal server error. </td><td>  -  </td></tr>
     * <tr><td> 4XX </td><td> Client error. </td><td>  -  </td></tr>
     * </table>
     */
    public ApiResponse<List<Task>> listTasksWithHttpInfo(
            @jakarta.annotation.Nullable List<String> status,
            @jakarta.annotation.Nullable String assignee,
            @jakarta.annotation.Nullable String runId,
            @jakarta.annotation.Nullable String sourceType,
            @jakarta.annotation.Nullable BigDecimal limit,
            @jakarta.annotation.Nullable BigDecimal offset)
            throws ApiException {
        okhttp3.Call localVarCall =
                listTasksValidateBeforeCall(
                        status, assignee, runId, sourceType, limit, offset, null);
        Type localVarReturnType = new TypeToken<List<Task>>() {}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * List tasks (asynchronously)
     * Lists durable tasks visible to the current principal, with optional filters for status, assignee, run id, and source type.
     * @param status  (optional)
     * @param assignee  (optional)
     * @param runId  (optional)
     * @param sourceType  (optional)
     * @param limit  (optional)
     * @param offset  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     * <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Matching tasks. </td><td>  -  </td></tr>
     * <tr><td> 500 </td><td> Internal server error. </td><td>  -  </td></tr>
     * <tr><td> 4XX </td><td> Client error. </td><td>  -  </td></tr>
     * </table>
     */
    public okhttp3.Call listTasksAsync(
            @jakarta.annotation.Nullable List<String> status,
            @jakarta.annotation.Nullable String assignee,
            @jakarta.annotation.Nullable String runId,
            @jakarta.annotation.Nullable String sourceType,
            @jakarta.annotation.Nullable BigDecimal limit,
            @jakarta.annotation.Nullable BigDecimal offset,
            final ApiCallback<List<Task>> _callback)
            throws ApiException {

        okhttp3.Call localVarCall =
                listTasksValidateBeforeCall(
                        status, assignee, runId, sourceType, limit, offset, _callback);
        Type localVarReturnType = new TypeToken<List<Task>>() {}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    /**
     * Build call for updateTask
     * @param taskId  (required)
     * @param updateTaskPayload  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     * <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> The updated task. </td><td>  -  </td></tr>
     * <tr><td> 500 </td><td> Internal server error. </td><td>  -  </td></tr>
     * <tr><td> 4XX </td><td> Client error. </td><td>  -  </td></tr>
     * </table>
     */
    public okhttp3.Call updateTaskCall(
            @jakarta.annotation.Nonnull String taskId,
            @jakarta.annotation.Nonnull UpdateTaskPayload updateTaskPayload,
            final ApiCallback _callback)
            throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {};

        // Determine Base Path to Use
        if (localCustomBaseUrl != null) {
            basePath = localCustomBaseUrl;
        } else if (localBasePaths.length > 0) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = updateTaskPayload;

        // create path and map variables
        String localVarPath =
                "/tasks/{taskId}"
                        .replace(
                                "{" + "taskId" + "}",
                                localVarApiClient.escapeString(taskId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {"application/json"};
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {"application/json"};
        final String localVarContentType =
                localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {"bearerAuth", "OpenID"};
        return localVarApiClient.buildCall(
                basePath,
                localVarPath,
                "PUT",
                localVarQueryParams,
                localVarCollectionQueryParams,
                localVarPostBody,
                localVarHeaderParams,
                localVarCookieParams,
                localVarFormParams,
                localVarAuthNames,
                _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call updateTaskValidateBeforeCall(
            @jakarta.annotation.Nonnull String taskId,
            @jakarta.annotation.Nonnull UpdateTaskPayload updateTaskPayload,
            final ApiCallback _callback)
            throws ApiException {
        // verify the required parameter 'taskId' is set
        if (taskId == null) {
            throw new ApiException(
                    "Missing the required parameter 'taskId' when calling updateTask(Async)");
        }

        // verify the required parameter 'updateTaskPayload' is set
        if (updateTaskPayload == null) {
            throw new ApiException(
                    "Missing the required parameter 'updateTaskPayload' when calling updateTask(Async)");
        }

        return updateTaskCall(taskId, updateTaskPayload, _callback);
    }

    /**
     * Update a task
     * Updates a durable task, including assignment, fields, due date, and status.  **Required permissions:** &#x60;task:manage&#x60;
     * @param taskId  (required)
     * @param updateTaskPayload  (required)
     * @return Task
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     * <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> The updated task. </td><td>  -  </td></tr>
     * <tr><td> 500 </td><td> Internal server error. </td><td>  -  </td></tr>
     * <tr><td> 4XX </td><td> Client error. </td><td>  -  </td></tr>
     * </table>
     */
    public Task updateTask(
            @jakarta.annotation.Nonnull String taskId,
            @jakarta.annotation.Nonnull UpdateTaskPayload updateTaskPayload)
            throws ApiException {
        ApiResponse<Task> localVarResp = updateTaskWithHttpInfo(taskId, updateTaskPayload);
        return localVarResp.getData();
    }

    /**
     * Update a task
     * Updates a durable task, including assignment, fields, due date, and status.  **Required permissions:** &#x60;task:manage&#x60;
     * @param taskId  (required)
     * @param updateTaskPayload  (required)
     * @return ApiResponse&lt;Task&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     * <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> The updated task. </td><td>  -  </td></tr>
     * <tr><td> 500 </td><td> Internal server error. </td><td>  -  </td></tr>
     * <tr><td> 4XX </td><td> Client error. </td><td>  -  </td></tr>
     * </table>
     */
    public ApiResponse<Task> updateTaskWithHttpInfo(
            @jakarta.annotation.Nonnull String taskId,
            @jakarta.annotation.Nonnull UpdateTaskPayload updateTaskPayload)
            throws ApiException {
        okhttp3.Call localVarCall = updateTaskValidateBeforeCall(taskId, updateTaskPayload, null);
        Type localVarReturnType = new TypeToken<Task>() {}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Update a task (asynchronously)
     * Updates a durable task, including assignment, fields, due date, and status.  **Required permissions:** &#x60;task:manage&#x60;
     * @param taskId  (required)
     * @param updateTaskPayload  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     * <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> The updated task. </td><td>  -  </td></tr>
     * <tr><td> 500 </td><td> Internal server error. </td><td>  -  </td></tr>
     * <tr><td> 4XX </td><td> Client error. </td><td>  -  </td></tr>
     * </table>
     */
    public okhttp3.Call updateTaskAsync(
            @jakarta.annotation.Nonnull String taskId,
            @jakarta.annotation.Nonnull UpdateTaskPayload updateTaskPayload,
            final ApiCallback<Task> _callback)
            throws ApiException {

        okhttp3.Call localVarCall =
                updateTaskValidateBeforeCall(taskId, updateTaskPayload, _callback);
        Type localVarReturnType = new TypeToken<Task>() {}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
