/*
 * Vertesia API
 * The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.
 *
 * The version of the OpenAPI document: 1.5.0-dev.20260901.005903Z
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.vertesia.api;

import com.google.gson.reflect.TypeToken;
import io.vertesia.ApiCallback;
import io.vertesia.ApiClient;
import io.vertesia.ApiException;
import io.vertesia.ApiResponse;
import io.vertesia.Configuration;
import io.vertesia.Pair;
import io.vertesia.model.AggregatedTool;
import io.vertesia.model.ToolInspection;
import io.vertesia.model.ValidateToolNamesPayload;
import io.vertesia.model.ValidateToolNamesResponse;
import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ToolsApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public ToolsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public ToolsApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for inspectProjectTool
     * @param toolName  (required)
     * @param context  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     * <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Resolved tool details and input schema. </td><td>  -  </td></tr>
     * <tr><td> 500 </td><td> Internal server error. </td><td>  -  </td></tr>
     * <tr><td> 4XX </td><td> Client error. </td><td>  -  </td></tr>
     * </table>
     */
    public okhttp3.Call inspectProjectToolCall(
            @jakarta.annotation.Nonnull String toolName,
            @jakarta.annotation.Nullable String context,
            final ApiCallback _callback)
            throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {};

        // Determine Base Path to Use
        if (localCustomBaseUrl != null) {
            basePath = localCustomBaseUrl;
        } else if (localBasePaths.length > 0) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath =
                "/tools/{toolName}"
                        .replace(
                                "{" + "toolName" + "}",
                                localVarApiClient.escapeString(toolName.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (context != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("context", context));
        }

        final String[] localVarAccepts = {"application/json"};
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {};
        final String localVarContentType =
                localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {"bearerAuth", "OpenID"};
        return localVarApiClient.buildCall(
                basePath,
                localVarPath,
                "GET",
                localVarQueryParams,
                localVarCollectionQueryParams,
                localVarPostBody,
                localVarHeaderParams,
                localVarCookieParams,
                localVarFormParams,
                localVarAuthNames,
                _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call inspectProjectToolValidateBeforeCall(
            @jakarta.annotation.Nonnull String toolName,
            @jakarta.annotation.Nullable String context,
            final ApiCallback _callback)
            throws ApiException {
        // verify the required parameter 'toolName' is set
        if (toolName == null) {
            throw new ApiException(
                    "Missing the required parameter 'toolName' when calling inspectProjectTool(Async)");
        }

        return inspectProjectToolCall(toolName, context, _callback);
    }

    /**
     * Inspect one project tool
     * **Required permissions:** &#x60;account:member&#x60;
     * @param toolName  (required)
     * @param context  (optional)
     * @return ToolInspection
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     * <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Resolved tool details and input schema. </td><td>  -  </td></tr>
     * <tr><td> 500 </td><td> Internal server error. </td><td>  -  </td></tr>
     * <tr><td> 4XX </td><td> Client error. </td><td>  -  </td></tr>
     * </table>
     */
    public ToolInspection inspectProjectTool(
            @jakarta.annotation.Nonnull String toolName,
            @jakarta.annotation.Nullable String context)
            throws ApiException {
        ApiResponse<ToolInspection> localVarResp =
                inspectProjectToolWithHttpInfo(toolName, context);
        return localVarResp.getData();
    }

    /**
     * Inspect one project tool
     * **Required permissions:** &#x60;account:member&#x60;
     * @param toolName  (required)
     * @param context  (optional)
     * @return ApiResponse&lt;ToolInspection&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     * <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Resolved tool details and input schema. </td><td>  -  </td></tr>
     * <tr><td> 500 </td><td> Internal server error. </td><td>  -  </td></tr>
     * <tr><td> 4XX </td><td> Client error. </td><td>  -  </td></tr>
     * </table>
     */
    public ApiResponse<ToolInspection> inspectProjectToolWithHttpInfo(
            @jakarta.annotation.Nonnull String toolName,
            @jakarta.annotation.Nullable String context)
            throws ApiException {
        okhttp3.Call localVarCall = inspectProjectToolValidateBeforeCall(toolName, context, null);
        Type localVarReturnType = new TypeToken<ToolInspection>() {}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Inspect one project tool (asynchronously)
     * **Required permissions:** &#x60;account:member&#x60;
     * @param toolName  (required)
     * @param context  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     * <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Resolved tool details and input schema. </td><td>  -  </td></tr>
     * <tr><td> 500 </td><td> Internal server error. </td><td>  -  </td></tr>
     * <tr><td> 4XX </td><td> Client error. </td><td>  -  </td></tr>
     * </table>
     */
    public okhttp3.Call inspectProjectToolAsync(
            @jakarta.annotation.Nonnull String toolName,
            @jakarta.annotation.Nullable String context,
            final ApiCallback<ToolInspection> _callback)
            throws ApiException {

        okhttp3.Call localVarCall =
                inspectProjectToolValidateBeforeCall(toolName, context, _callback);
        Type localVarReturnType = new TypeToken<ToolInspection>() {}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    /**
     * Build call for listAgentTools
     * @param context  (optional)
     * @param sources Include only these sources. (optional)
     * @param exclude Drop these sources from the result (and skip their fetch). Applied after &#x60;sources&#x60;. (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     * <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Aggregated tool list. </td><td>  -  </td></tr>
     * <tr><td> 500 </td><td> Internal server error. </td><td>  -  </td></tr>
     * <tr><td> 4XX </td><td> Client error. </td><td>  -  </td></tr>
     * </table>
     */
    public okhttp3.Call listAgentToolsCall(
            @jakarta.annotation.Nullable String context,
            @jakarta.annotation.Nullable List<String> sources,
            @jakarta.annotation.Nullable List<String> exclude,
            final ApiCallback _callback)
            throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {};

        // Determine Base Path to Use
        if (localCustomBaseUrl != null) {
            basePath = localCustomBaseUrl;
        } else if (localBasePaths.length > 0) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/tools";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (context != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("context", context));
        }

        if (sources != null) {
            localVarCollectionQueryParams.addAll(
                    localVarApiClient.parameterToPairs("multi", "sources", sources));
        }

        if (exclude != null) {
            localVarCollectionQueryParams.addAll(
                    localVarApiClient.parameterToPairs("multi", "exclude", exclude));
        }

        final String[] localVarAccepts = {"application/json"};
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {};
        final String localVarContentType =
                localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {"bearerAuth", "OpenID"};
        return localVarApiClient.buildCall(
                basePath,
                localVarPath,
                "GET",
                localVarQueryParams,
                localVarCollectionQueryParams,
                localVarPostBody,
                localVarHeaderParams,
                localVarCookieParams,
                localVarFormParams,
                localVarAuthNames,
                _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call listAgentToolsValidateBeforeCall(
            @jakarta.annotation.Nullable String context,
            @jakarta.annotation.Nullable List<String> sources,
            @jakarta.annotation.Nullable List<String> exclude,
            final ApiCallback _callback)
            throws ApiException {
        return listAgentToolsCall(context, sources, exclude, _callback);
    }

    /**
     * List all tools available in the project
     * Returns the unified project-scoped tool registry visible to the current principal. Sources can be filtered via the &#x60;sources&#x60; query string.  **Required permissions:** &#x60;account:member&#x60;
     * @param context  (optional)
     * @param sources Include only these sources. (optional)
     * @param exclude Drop these sources from the result (and skip their fetch). Applied after &#x60;sources&#x60;. (optional)
     * @return List&lt;AggregatedTool&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     * <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Aggregated tool list. </td><td>  -  </td></tr>
     * <tr><td> 500 </td><td> Internal server error. </td><td>  -  </td></tr>
     * <tr><td> 4XX </td><td> Client error. </td><td>  -  </td></tr>
     * </table>
     */
    public List<AggregatedTool> listAgentTools(
            @jakarta.annotation.Nullable String context,
            @jakarta.annotation.Nullable List<String> sources,
            @jakarta.annotation.Nullable List<String> exclude)
            throws ApiException {
        ApiResponse<List<AggregatedTool>> localVarResp =
                listAgentToolsWithHttpInfo(context, sources, exclude);
        return localVarResp.getData();
    }

    /**
     * List all tools available in the project
     * Returns the unified project-scoped tool registry visible to the current principal. Sources can be filtered via the &#x60;sources&#x60; query string.  **Required permissions:** &#x60;account:member&#x60;
     * @param context  (optional)
     * @param sources Include only these sources. (optional)
     * @param exclude Drop these sources from the result (and skip their fetch). Applied after &#x60;sources&#x60;. (optional)
     * @return ApiResponse&lt;List&lt;AggregatedTool&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     * <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Aggregated tool list. </td><td>  -  </td></tr>
     * <tr><td> 500 </td><td> Internal server error. </td><td>  -  </td></tr>
     * <tr><td> 4XX </td><td> Client error. </td><td>  -  </td></tr>
     * </table>
     */
    public ApiResponse<List<AggregatedTool>> listAgentToolsWithHttpInfo(
            @jakarta.annotation.Nullable String context,
            @jakarta.annotation.Nullable List<String> sources,
            @jakarta.annotation.Nullable List<String> exclude)
            throws ApiException {
        okhttp3.Call localVarCall =
                listAgentToolsValidateBeforeCall(context, sources, exclude, null);
        Type localVarReturnType = new TypeToken<List<AggregatedTool>>() {}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * List all tools available in the project (asynchronously)
     * Returns the unified project-scoped tool registry visible to the current principal. Sources can be filtered via the &#x60;sources&#x60; query string.  **Required permissions:** &#x60;account:member&#x60;
     * @param context  (optional)
     * @param sources Include only these sources. (optional)
     * @param exclude Drop these sources from the result (and skip their fetch). Applied after &#x60;sources&#x60;. (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     * <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Aggregated tool list. </td><td>  -  </td></tr>
     * <tr><td> 500 </td><td> Internal server error. </td><td>  -  </td></tr>
     * <tr><td> 4XX </td><td> Client error. </td><td>  -  </td></tr>
     * </table>
     */
    public okhttp3.Call listAgentToolsAsync(
            @jakarta.annotation.Nullable String context,
            @jakarta.annotation.Nullable List<String> sources,
            @jakarta.annotation.Nullable List<String> exclude,
            final ApiCallback<List<AggregatedTool>> _callback)
            throws ApiException {

        okhttp3.Call localVarCall =
                listAgentToolsValidateBeforeCall(context, sources, exclude, _callback);
        Type localVarReturnType = new TypeToken<List<AggregatedTool>>() {}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    /**
     * Build call for validateAgentToolNames
     * @param validateToolNamesPayload  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     * <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Per-name validation results. </td><td>  -  </td></tr>
     * <tr><td> 500 </td><td> Internal server error. </td><td>  -  </td></tr>
     * <tr><td> 4XX </td><td> Client error. </td><td>  -  </td></tr>
     * </table>
     */
    public okhttp3.Call validateAgentToolNamesCall(
            @jakarta.annotation.Nonnull ValidateToolNamesPayload validateToolNamesPayload,
            final ApiCallback _callback)
            throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {};

        // Determine Base Path to Use
        if (localCustomBaseUrl != null) {
            basePath = localCustomBaseUrl;
        } else if (localBasePaths.length > 0) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = validateToolNamesPayload;

        // create path and map variables
        String localVarPath = "/tools/validate";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {"application/json"};
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {"application/json"};
        final String localVarContentType =
                localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {"bearerAuth", "OpenID"};
        return localVarApiClient.buildCall(
                basePath,
                localVarPath,
                "POST",
                localVarQueryParams,
                localVarCollectionQueryParams,
                localVarPostBody,
                localVarHeaderParams,
                localVarCookieParams,
                localVarFormParams,
                localVarAuthNames,
                _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call validateAgentToolNamesValidateBeforeCall(
            @jakarta.annotation.Nonnull ValidateToolNamesPayload validateToolNamesPayload,
            final ApiCallback _callback)
            throws ApiException {
        // verify the required parameter 'validateToolNamesPayload' is set
        if (validateToolNamesPayload == null) {
            throw new ApiException(
                    "Missing the required parameter 'validateToolNamesPayload' when calling validateAgentToolNames(Async)");
        }

        return validateAgentToolNamesCall(validateToolNamesPayload, _callback);
    }

    /**
     * Validate tool names against the project registry
     * Resolves each name to its source or reports it as invalid with a suggestion.  **Required permissions:** &#x60;account:member&#x60;
     * @param validateToolNamesPayload  (required)
     * @return ValidateToolNamesResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     * <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Per-name validation results. </td><td>  -  </td></tr>
     * <tr><td> 500 </td><td> Internal server error. </td><td>  -  </td></tr>
     * <tr><td> 4XX </td><td> Client error. </td><td>  -  </td></tr>
     * </table>
     */
    public ValidateToolNamesResponse validateAgentToolNames(
            @jakarta.annotation.Nonnull ValidateToolNamesPayload validateToolNamesPayload)
            throws ApiException {
        ApiResponse<ValidateToolNamesResponse> localVarResp =
                validateAgentToolNamesWithHttpInfo(validateToolNamesPayload);
        return localVarResp.getData();
    }

    /**
     * Validate tool names against the project registry
     * Resolves each name to its source or reports it as invalid with a suggestion.  **Required permissions:** &#x60;account:member&#x60;
     * @param validateToolNamesPayload  (required)
     * @return ApiResponse&lt;ValidateToolNamesResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     * <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Per-name validation results. </td><td>  -  </td></tr>
     * <tr><td> 500 </td><td> Internal server error. </td><td>  -  </td></tr>
     * <tr><td> 4XX </td><td> Client error. </td><td>  -  </td></tr>
     * </table>
     */
    public ApiResponse<ValidateToolNamesResponse> validateAgentToolNamesWithHttpInfo(
            @jakarta.annotation.Nonnull ValidateToolNamesPayload validateToolNamesPayload)
            throws ApiException {
        okhttp3.Call localVarCall =
                validateAgentToolNamesValidateBeforeCall(validateToolNamesPayload, null);
        Type localVarReturnType = new TypeToken<ValidateToolNamesResponse>() {}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Validate tool names against the project registry (asynchronously)
     * Resolves each name to its source or reports it as invalid with a suggestion.  **Required permissions:** &#x60;account:member&#x60;
     * @param validateToolNamesPayload  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     * <table border="1">
     * <caption>Response Details</caption>
     * <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
     * <tr><td> 200 </td><td> Per-name validation results. </td><td>  -  </td></tr>
     * <tr><td> 500 </td><td> Internal server error. </td><td>  -  </td></tr>
     * <tr><td> 4XX </td><td> Client error. </td><td>  -  </td></tr>
     * </table>
     */
    public okhttp3.Call validateAgentToolNamesAsync(
            @jakarta.annotation.Nonnull ValidateToolNamesPayload validateToolNamesPayload,
            final ApiCallback<ValidateToolNamesResponse> _callback)
            throws ApiException {

        okhttp3.Call localVarCall =
                validateAgentToolNamesValidateBeforeCall(validateToolNamesPayload, _callback);
        Type localVarReturnType = new TypeToken<ValidateToolNamesResponse>() {}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
