/*
 * Vertesia API
 * The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.
 *
 * The version of the OpenAPI document: 1.5.0-dev
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.vertesia.model;

import com.google.gson.JsonElement;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

/**
 * Gets or Sets AbacScope
 */
@JsonAdapter(AbacScope.Adapter.class)
public enum AbacScope {
    DOCUMENT("document"),

    COLLECTION("collection"),

    TASK("task"),

    UNKNOWN_DEFAULT_OPEN_API("unknown_default_open_api");

    private String value;

    AbacScope(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }

    public static AbacScope fromValue(String value) {
        for (AbacScope b : AbacScope.values()) {
            if (b.value.equals(value)) {
                return b;
            }
        }
        return UNKNOWN_DEFAULT_OPEN_API;
    }

    public static class Adapter extends TypeAdapter<AbacScope> {
        @Override
        public void write(final JsonWriter jsonWriter, final AbacScope enumeration)
                throws IOException {
            jsonWriter.value(enumeration.getValue());
        }

        @Override
        public AbacScope read(final JsonReader jsonReader) throws IOException {
            String value = jsonReader.nextString();
            return AbacScope.fromValue(value);
        }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        String value = jsonElement.getAsString();
        AbacScope.fromValue(value);
    }
}
