/*
 * Vertesia API
 * The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.
 *
 * The version of the OpenAPI document: 1.5.0-dev.20260714.072725Z
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.vertesia.model;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.vertesia.JSON;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashSet;
import java.util.List;
import java.util.Objects;

/**
 * AIModel
 */
@jakarta.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.22.0")
public class AIModel {
    public static final String SERIALIZED_NAME_ID = "id";

    @SerializedName(SERIALIZED_NAME_ID)
    @jakarta.annotation.Nonnull
    private String id;

    public static final String SERIALIZED_NAME_NAME = "name";

    @SerializedName(SERIALIZED_NAME_NAME)
    @jakarta.annotation.Nonnull
    private String name;

    public static final String SERIALIZED_NAME_PROVIDER = "provider";

    @SerializedName(SERIALIZED_NAME_PROVIDER)
    @jakarta.annotation.Nonnull
    private String provider;

    public static final String SERIALIZED_NAME_DESCRIPTION = "description";

    @SerializedName(SERIALIZED_NAME_DESCRIPTION)
    @jakarta.annotation.Nullable private String description;

    public static final String SERIALIZED_NAME_VERSION = "version";

    @SerializedName(SERIALIZED_NAME_VERSION)
    @jakarta.annotation.Nullable private String version;

    public static final String SERIALIZED_NAME_TYPE = "type";

    @SerializedName(SERIALIZED_NAME_TYPE)
    @jakarta.annotation.Nullable private ModelType type;

    public static final String SERIALIZED_NAME_TAGS = "tags";

    @SerializedName(SERIALIZED_NAME_TAGS)
    @jakarta.annotation.Nullable private List<String> tags = new ArrayList<>();

    public static final String SERIALIZED_NAME_OWNER = "owner";

    @SerializedName(SERIALIZED_NAME_OWNER)
    @jakarta.annotation.Nullable private String owner;

    public static final String SERIALIZED_NAME_STATUS = "status";

    @SerializedName(SERIALIZED_NAME_STATUS)
    @jakarta.annotation.Nullable private AIModelStatus status;

    public static final String SERIALIZED_NAME_CAN_STREAM = "can_stream";

    @SerializedName(SERIALIZED_NAME_CAN_STREAM)
    @jakarta.annotation.Nullable private Boolean canStream;

    public static final String SERIALIZED_NAME_IS_CUSTOM = "is_custom";

    @SerializedName(SERIALIZED_NAME_IS_CUSTOM)
    @jakarta.annotation.Nullable private Boolean isCustom;

    public static final String SERIALIZED_NAME_IS_MULTIMODAL = "is_multimodal";

    @SerializedName(SERIALIZED_NAME_IS_MULTIMODAL)
    @jakarta.annotation.Nullable private Boolean isMultimodal;

    public static final String SERIALIZED_NAME_INPUT_MODALITIES = "input_modalities";

    @SerializedName(SERIALIZED_NAME_INPUT_MODALITIES)
    @jakarta.annotation.Nullable private List<String> inputModalities = new ArrayList<>();

    public static final String SERIALIZED_NAME_OUTPUT_MODALITIES = "output_modalities";

    @SerializedName(SERIALIZED_NAME_OUTPUT_MODALITIES)
    @jakarta.annotation.Nullable private List<String> outputModalities = new ArrayList<>();

    public static final String SERIALIZED_NAME_TOOL_SUPPORT = "tool_support";

    @SerializedName(SERIALIZED_NAME_TOOL_SUPPORT)
    @jakarta.annotation.Nullable private Boolean toolSupport;

    public static final String SERIALIZED_NAME_ENVIRONMENT = "environment";

    @SerializedName(SERIALIZED_NAME_ENVIRONMENT)
    @jakarta.annotation.Nullable private String environment;

    public AIModel() {}

    public AIModel id(@jakarta.annotation.Nonnull String id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     * @return id
     */
    @jakarta.annotation.Nonnull
    public String getId() {
        return id;
    }

    public void setId(@jakarta.annotation.Nonnull String id) {
        this.id = id;
    }

    public AIModel name(@jakarta.annotation.Nonnull String name) {
        this.name = name;
        return this;
    }

    /**
     * Get name
     * @return name
     */
    @jakarta.annotation.Nonnull
    public String getName() {
        return name;
    }

    public void setName(@jakarta.annotation.Nonnull String name) {
        this.name = name;
    }

    public AIModel provider(@jakarta.annotation.Nonnull String provider) {
        this.provider = provider;
        return this;
    }

    /**
     * Get provider
     * @return provider
     */
    @jakarta.annotation.Nonnull
    public String getProvider() {
        return provider;
    }

    public void setProvider(@jakarta.annotation.Nonnull String provider) {
        this.provider = provider;
    }

    public AIModel description(@jakarta.annotation.Nullable String description) {
        this.description = description;
        return this;
    }

    /**
     * Get description
     * @return description
     */
    @jakarta.annotation.Nullable public String getDescription() {
        return description;
    }

    public void setDescription(@jakarta.annotation.Nullable String description) {
        this.description = description;
    }

    public AIModel version(@jakarta.annotation.Nullable String version) {
        this.version = version;
        return this;
    }

    /**
     * Get version
     * @return version
     */
    @jakarta.annotation.Nullable public String getVersion() {
        return version;
    }

    public void setVersion(@jakarta.annotation.Nullable String version) {
        this.version = version;
    }

    public AIModel type(@jakarta.annotation.Nullable ModelType type) {
        this.type = type;
        return this;
    }

    /**
     * Get type
     * @return type
     */
    @jakarta.annotation.Nullable public ModelType getType() {
        return type;
    }

    public void setType(@jakarta.annotation.Nullable ModelType type) {
        this.type = type;
    }

    public AIModel tags(@jakarta.annotation.Nullable List<String> tags) {
        this.tags = tags;
        return this;
    }

    public AIModel addTagsItem(String tagsItem) {
        if (this.tags == null) {
            this.tags = new ArrayList<>();
        }
        this.tags.add(tagsItem);
        return this;
    }

    /**
     * Get tags
     * @return tags
     */
    @jakarta.annotation.Nullable public List<String> getTags() {
        return tags;
    }

    public void setTags(@jakarta.annotation.Nullable List<String> tags) {
        this.tags = tags;
    }

    public AIModel owner(@jakarta.annotation.Nullable String owner) {
        this.owner = owner;
        return this;
    }

    /**
     * Get owner
     * @return owner
     */
    @jakarta.annotation.Nullable public String getOwner() {
        return owner;
    }

    public void setOwner(@jakarta.annotation.Nullable String owner) {
        this.owner = owner;
    }

    public AIModel status(@jakarta.annotation.Nullable AIModelStatus status) {
        this.status = status;
        return this;
    }

    /**
     * Get status
     * @return status
     */
    @jakarta.annotation.Nullable public AIModelStatus getStatus() {
        return status;
    }

    public void setStatus(@jakarta.annotation.Nullable AIModelStatus status) {
        this.status = status;
    }

    public AIModel canStream(@jakarta.annotation.Nullable Boolean canStream) {
        this.canStream = canStream;
        return this;
    }

    /**
     * Get canStream
     * @return canStream
     */
    @jakarta.annotation.Nullable public Boolean getCanStream() {
        return canStream;
    }

    public void setCanStream(@jakarta.annotation.Nullable Boolean canStream) {
        this.canStream = canStream;
    }

    public AIModel isCustom(@jakarta.annotation.Nullable Boolean isCustom) {
        this.isCustom = isCustom;
        return this;
    }

    /**
     * Get isCustom
     * @return isCustom
     */
    @jakarta.annotation.Nullable public Boolean getIsCustom() {
        return isCustom;
    }

    public void setIsCustom(@jakarta.annotation.Nullable Boolean isCustom) {
        this.isCustom = isCustom;
    }

    public AIModel isMultimodal(@jakarta.annotation.Nullable Boolean isMultimodal) {
        this.isMultimodal = isMultimodal;
        return this;
    }

    /**
     * Get isMultimodal
     * @return isMultimodal
     */
    @jakarta.annotation.Nullable public Boolean getIsMultimodal() {
        return isMultimodal;
    }

    public void setIsMultimodal(@jakarta.annotation.Nullable Boolean isMultimodal) {
        this.isMultimodal = isMultimodal;
    }

    public AIModel inputModalities(@jakarta.annotation.Nullable List<String> inputModalities) {
        this.inputModalities = inputModalities;
        return this;
    }

    public AIModel addInputModalitiesItem(String inputModalitiesItem) {
        if (this.inputModalities == null) {
            this.inputModalities = new ArrayList<>();
        }
        this.inputModalities.add(inputModalitiesItem);
        return this;
    }

    /**
     * Get inputModalities
     * @return inputModalities
     */
    @jakarta.annotation.Nullable public List<String> getInputModalities() {
        return inputModalities;
    }

    public void setInputModalities(@jakarta.annotation.Nullable List<String> inputModalities) {
        this.inputModalities = inputModalities;
    }

    public AIModel outputModalities(@jakarta.annotation.Nullable List<String> outputModalities) {
        this.outputModalities = outputModalities;
        return this;
    }

    public AIModel addOutputModalitiesItem(String outputModalitiesItem) {
        if (this.outputModalities == null) {
            this.outputModalities = new ArrayList<>();
        }
        this.outputModalities.add(outputModalitiesItem);
        return this;
    }

    /**
     * Get outputModalities
     * @return outputModalities
     */
    @jakarta.annotation.Nullable public List<String> getOutputModalities() {
        return outputModalities;
    }

    public void setOutputModalities(@jakarta.annotation.Nullable List<String> outputModalities) {
        this.outputModalities = outputModalities;
    }

    public AIModel toolSupport(@jakarta.annotation.Nullable Boolean toolSupport) {
        this.toolSupport = toolSupport;
        return this;
    }

    /**
     * Get toolSupport
     * @return toolSupport
     */
    @jakarta.annotation.Nullable public Boolean getToolSupport() {
        return toolSupport;
    }

    public void setToolSupport(@jakarta.annotation.Nullable Boolean toolSupport) {
        this.toolSupport = toolSupport;
    }

    public AIModel environment(@jakarta.annotation.Nullable String environment) {
        this.environment = environment;
        return this;
    }

    /**
     * Get environment
     * @return environment
     */
    @jakarta.annotation.Nullable public String getEnvironment() {
        return environment;
    }

    public void setEnvironment(@jakarta.annotation.Nullable String environment) {
        this.environment = environment;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AIModel aiModel = (AIModel) o;
        return Objects.equals(this.id, aiModel.id)
                && Objects.equals(this.name, aiModel.name)
                && Objects.equals(this.provider, aiModel.provider)
                && Objects.equals(this.description, aiModel.description)
                && Objects.equals(this.version, aiModel.version)
                && Objects.equals(this.type, aiModel.type)
                && Objects.equals(this.tags, aiModel.tags)
                && Objects.equals(this.owner, aiModel.owner)
                && Objects.equals(this.status, aiModel.status)
                && Objects.equals(this.canStream, aiModel.canStream)
                && Objects.equals(this.isCustom, aiModel.isCustom)
                && Objects.equals(this.isMultimodal, aiModel.isMultimodal)
                && Objects.equals(this.inputModalities, aiModel.inputModalities)
                && Objects.equals(this.outputModalities, aiModel.outputModalities)
                && Objects.equals(this.toolSupport, aiModel.toolSupport)
                && Objects.equals(this.environment, aiModel.environment);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                id,
                name,
                provider,
                description,
                version,
                type,
                tags,
                owner,
                status,
                canStream,
                isCustom,
                isMultimodal,
                inputModalities,
                outputModalities,
                toolSupport,
                environment);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class AIModel {\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    provider: ").append(toIndentedString(provider)).append("\n");
        sb.append("    description: ").append(toIndentedString(description)).append("\n");
        sb.append("    version: ").append(toIndentedString(version)).append("\n");
        sb.append("    type: ").append(toIndentedString(type)).append("\n");
        sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
        sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
        sb.append("    status: ").append(toIndentedString(status)).append("\n");
        sb.append("    canStream: ").append(toIndentedString(canStream)).append("\n");
        sb.append("    isCustom: ").append(toIndentedString(isCustom)).append("\n");
        sb.append("    isMultimodal: ").append(toIndentedString(isMultimodal)).append("\n");
        sb.append("    inputModalities: ").append(toIndentedString(inputModalities)).append("\n");
        sb.append("    outputModalities: ").append(toIndentedString(outputModalities)).append("\n");
        sb.append("    toolSupport: ").append(toIndentedString(toolSupport)).append("\n");
        sb.append("    environment: ").append(toIndentedString(environment)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        return o == null ? "null" : o.toString().replace("\n", "\n    ");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields =
                new HashSet<String>(
                        Arrays.asList(
                                "id",
                                "name",
                                "provider",
                                "description",
                                "version",
                                "type",
                                "tags",
                                "owner",
                                "status",
                                "can_stream",
                                "is_custom",
                                "is_multimodal",
                                "input_modalities",
                                "output_modalities",
                                "tool_support",
                                "environment"));

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>(Arrays.asList("id", "name", "provider"));
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to AIModel
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!AIModel.openapiRequiredFields
                    .isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(
                        String.format(
                                java.util.Locale.ROOT,
                                "The required field(s) %s in AIModel is not found in the empty JSON string",
                                AIModel.openapiRequiredFields.toString()));
            }
        }

        // check to make sure all required properties/fields are present in the JSON string
        for (String requiredField : AIModel.openapiRequiredFields) {
            if (jsonElement.getAsJsonObject().get(requiredField) == null) {
                throw new IllegalArgumentException(
                        String.format(
                                java.util.Locale.ROOT,
                                "The required field `%s` is not found in the JSON string: %s",
                                requiredField,
                                jsonElement.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if (!jsonObj.get("id").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `id` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("id").toString()));
        }
        if (!jsonObj.get("name").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `name` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("name").toString()));
        }
        if (!jsonObj.get("provider").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `provider` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("provider").toString()));
        }
        if ((jsonObj.get("description") != null && !jsonObj.get("description").isJsonNull())
                && !jsonObj.get("description").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `description` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("description").toString()));
        }
        if ((jsonObj.get("version") != null && !jsonObj.get("version").isJsonNull())
                && !jsonObj.get("version").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `version` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("version").toString()));
        }
        // validate the optional field `type`
        if (jsonObj.get("type") != null && !jsonObj.get("type").isJsonNull()) {
            ModelType.validateJsonElement(jsonObj.get("type"));
        }
        // ensure the optional json data is an array if present
        if (jsonObj.get("tags") != null
                && !jsonObj.get("tags").isJsonNull()
                && !jsonObj.get("tags").isJsonArray()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `tags` to be an array in the JSON string but got `%s`",
                            jsonObj.get("tags").toString()));
        }
        if ((jsonObj.get("owner") != null && !jsonObj.get("owner").isJsonNull())
                && !jsonObj.get("owner").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `owner` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("owner").toString()));
        }
        // validate the optional field `status`
        if (jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) {
            AIModelStatus.validateJsonElement(jsonObj.get("status"));
        }
        // ensure the optional json data is an array if present
        if (jsonObj.get("input_modalities") != null
                && !jsonObj.get("input_modalities").isJsonNull()
                && !jsonObj.get("input_modalities").isJsonArray()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `input_modalities` to be an array in the JSON string but got `%s`",
                            jsonObj.get("input_modalities").toString()));
        }
        // ensure the optional json data is an array if present
        if (jsonObj.get("output_modalities") != null
                && !jsonObj.get("output_modalities").isJsonNull()
                && !jsonObj.get("output_modalities").isJsonArray()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `output_modalities` to be an array in the JSON string but got `%s`",
                            jsonObj.get("output_modalities").toString()));
        }
        if ((jsonObj.get("environment") != null && !jsonObj.get("environment").isJsonNull())
                && !jsonObj.get("environment").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `environment` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("environment").toString()));
        }
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!AIModel.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'AIModel' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<AIModel> thisAdapter =
                    gson.getDelegateAdapter(this, TypeToken.get(AIModel.class));

            return (TypeAdapter<T>)
                    new TypeAdapter<AIModel>() {
                        @Override
                        public void write(JsonWriter out, AIModel value) throws IOException {
                            JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                            elementAdapter.write(out, obj);
                        }

                        @Override
                        public AIModel read(JsonReader in) throws IOException {
                            JsonElement jsonElement = elementAdapter.read(in);
                            validateJsonElement(jsonElement);
                            return thisAdapter.fromJsonTree(jsonElement);
                        }
                    }.nullSafe();
        }
    }

    /**
     * Create an instance of AIModel given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of AIModel
     * @throws IOException if the JSON string is invalid with respect to AIModel
     */
    public static AIModel fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, AIModel.class);
    }

    /**
     * Convert an instance of AIModel to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
