/*
 * Vertesia API
 * The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.
 *
 * The version of the OpenAPI document: 1.5.0-dev.20260901.052906Z
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.vertesia.model;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.vertesia.JSON;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Objects;

/**
 * AlterTableOperationOneOf3
 */
@jakarta.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.22.0")
public class AlterTableOperationOneOf3 {
    /**
     * Gets or Sets op
     */
    @JsonAdapter(OpEnum.Adapter.class)
    public enum OpEnum {
        MODIFY_COLUMN("modify_column"),

        UNKNOWN_DEFAULT_OPEN_API("unknown_default_open_api");

        private String value;

        OpEnum(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        public static OpEnum fromValue(String value) {
            for (OpEnum b : OpEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            return UNKNOWN_DEFAULT_OPEN_API;
        }

        public static class Adapter extends TypeAdapter<OpEnum> {
            @Override
            public void write(final JsonWriter jsonWriter, final OpEnum enumeration)
                    throws IOException {
                jsonWriter.value(enumeration.getValue());
            }

            @Override
            public OpEnum read(final JsonReader jsonReader) throws IOException {
                String value = jsonReader.nextString();
                return OpEnum.fromValue(value);
            }
        }

        public static void validateJsonElement(JsonElement jsonElement) throws IOException {
            String value = jsonElement.getAsString();
            OpEnum.fromValue(value);
        }
    }

    public static final String SERIALIZED_NAME_OP = "op";

    @SerializedName(SERIALIZED_NAME_OP)
    @jakarta.annotation.Nonnull
    private OpEnum op;

    public static final String SERIALIZED_NAME_COLUMN = "column";

    @SerializedName(SERIALIZED_NAME_COLUMN)
    @jakarta.annotation.Nonnull
    private String column;

    public static final String SERIALIZED_NAME_UPDATES = "updates";

    @SerializedName(SERIALIZED_NAME_UPDATES)
    @jakarta.annotation.Nonnull
    private DataColumnUpdate updates;

    public AlterTableOperationOneOf3() {}

    public AlterTableOperationOneOf3 op(@jakarta.annotation.Nonnull OpEnum op) {
        this.op = op;
        return this;
    }

    /**
     * Get op
     * @return op
     */
    @jakarta.annotation.Nonnull
    public OpEnum getOp() {
        return op;
    }

    public void setOp(@jakarta.annotation.Nonnull OpEnum op) {
        this.op = op;
    }

    public AlterTableOperationOneOf3 column(@jakarta.annotation.Nonnull String column) {
        this.column = column;
        return this;
    }

    /**
     * Get column
     * @return column
     */
    @jakarta.annotation.Nonnull
    public String getColumn() {
        return column;
    }

    public void setColumn(@jakarta.annotation.Nonnull String column) {
        this.column = column;
    }

    public AlterTableOperationOneOf3 updates(@jakarta.annotation.Nonnull DataColumnUpdate updates) {
        this.updates = updates;
        return this;
    }

    /**
     * Get updates
     * @return updates
     */
    @jakarta.annotation.Nonnull
    public DataColumnUpdate getUpdates() {
        return updates;
    }

    public void setUpdates(@jakarta.annotation.Nonnull DataColumnUpdate updates) {
        this.updates = updates;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AlterTableOperationOneOf3 alterTableOperationOneOf3 = (AlterTableOperationOneOf3) o;
        return Objects.equals(this.op, alterTableOperationOneOf3.op)
                && Objects.equals(this.column, alterTableOperationOneOf3.column)
                && Objects.equals(this.updates, alterTableOperationOneOf3.updates);
    }

    @Override
    public int hashCode() {
        return Objects.hash(op, column, updates);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class AlterTableOperationOneOf3 {\n");
        sb.append("    op: ").append(toIndentedString(op)).append("\n");
        sb.append("    column: ").append(toIndentedString(column)).append("\n");
        sb.append("    updates: ").append(toIndentedString(updates)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        return o == null ? "null" : o.toString().replace("\n", "\n    ");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>(Arrays.asList("op", "column", "updates"));

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>(Arrays.asList("op", "column", "updates"));
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to AlterTableOperationOneOf3
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!AlterTableOperationOneOf3.openapiRequiredFields
                    .isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(
                        String.format(
                                java.util.Locale.ROOT,
                                "The required field(s) %s in AlterTableOperationOneOf3 is not found in the empty JSON string",
                                AlterTableOperationOneOf3.openapiRequiredFields.toString()));
            }
        }

        // check to make sure all required properties/fields are present in the JSON string
        for (String requiredField : AlterTableOperationOneOf3.openapiRequiredFields) {
            if (jsonElement.getAsJsonObject().get(requiredField) == null) {
                throw new IllegalArgumentException(
                        String.format(
                                java.util.Locale.ROOT,
                                "The required field `%s` is not found in the JSON string: %s",
                                requiredField,
                                jsonElement.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if (!jsonObj.get("op").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `op` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("op").toString()));
        }
        // validate the required field `op`
        OpEnum.validateJsonElement(jsonObj.get("op"));
        if (!jsonObj.get("column").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `column` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("column").toString()));
        }
        // validate the required field `updates`
        DataColumnUpdate.validateJsonElement(jsonObj.get("updates"));
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!AlterTableOperationOneOf3.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'AlterTableOperationOneOf3' and its
                // subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<AlterTableOperationOneOf3> thisAdapter =
                    gson.getDelegateAdapter(this, TypeToken.get(AlterTableOperationOneOf3.class));

            return (TypeAdapter<T>)
                    new TypeAdapter<AlterTableOperationOneOf3>() {
                        @Override
                        public void write(JsonWriter out, AlterTableOperationOneOf3 value)
                                throws IOException {
                            JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                            elementAdapter.write(out, obj);
                        }

                        @Override
                        public AlterTableOperationOneOf3 read(JsonReader in) throws IOException {
                            JsonElement jsonElement = elementAdapter.read(in);
                            validateJsonElement(jsonElement);
                            return thisAdapter.fromJsonTree(jsonElement);
                        }
                    }.nullSafe();
        }
    }

    /**
     * Create an instance of AlterTableOperationOneOf3 given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of AlterTableOperationOneOf3
     * @throws IOException if the JSON string is invalid with respect to AlterTableOperationOneOf3
     */
    public static AlterTableOperationOneOf3 fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, AlterTableOperationOneOf3.class);
    }

    /**
     * Convert an instance of AlterTableOperationOneOf3 to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
