/*
 * Vertesia API
 * The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.
 *
 * The version of the OpenAPI document: 1.6.0-dev.20261004.085740Z
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.vertesia.model;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.vertesia.JSON;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Objects;

/**
 * AuditAdoptionHistory
 */
@jakarta.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.22.0")
public class AuditAdoptionHistory {
    public static final String SERIALIZED_NAME_EARLIEST_OBSERVED_AT = "earliest_observed_at";

    @SerializedName(SERIALIZED_NAME_EARLIEST_OBSERVED_AT)
    @jakarta.annotation.Nullable private OffsetDateTime earliestObservedAt;

    public static final String SERIALIZED_NAME_COVERAGE_FROM = "coverage_from";

    @SerializedName(SERIALIZED_NAME_COVERAGE_FROM)
    @jakarta.annotation.Nullable private OffsetDateTime coverageFrom;

    /**
     * Gets or Sets completeness
     */
    @JsonAdapter(CompletenessEnum.Adapter.class)
    public enum CompletenessEnum {
        UNKNOWN("unknown"),

        INSUFFICIENT("insufficient"),

        VERIFIED("verified"),

        UNKNOWN_DEFAULT_OPEN_API("unknown_default_open_api");

        private String value;

        CompletenessEnum(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        public static CompletenessEnum fromValue(String value) {
            for (CompletenessEnum b : CompletenessEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            return UNKNOWN_DEFAULT_OPEN_API;
        }

        public static class Adapter extends TypeAdapter<CompletenessEnum> {
            @Override
            public void write(final JsonWriter jsonWriter, final CompletenessEnum enumeration)
                    throws IOException {
                jsonWriter.value(enumeration.getValue());
            }

            @Override
            public CompletenessEnum read(final JsonReader jsonReader) throws IOException {
                String value = jsonReader.nextString();
                return CompletenessEnum.fromValue(value);
            }
        }

        public static void validateJsonElement(JsonElement jsonElement) throws IOException {
            String value = jsonElement.getAsString();
            CompletenessEnum.fromValue(value);
        }
    }

    public static final String SERIALIZED_NAME_COMPLETENESS = "completeness";

    @SerializedName(SERIALIZED_NAME_COMPLETENESS)
    @jakarta.annotation.Nonnull
    private CompletenessEnum completeness;

    /**
     * Gets or Sets retentionUnavailableReason
     */
    @JsonAdapter(RetentionUnavailableReasonEnum.Adapter.class)
    public enum RetentionUnavailableReasonEnum {
        NO_PREVIOUS_USERS("no_previous_users"),

        INSUFFICIENT_HISTORY("insufficient_history"),

        UNKNOWN_DEFAULT_OPEN_API("unknown_default_open_api");

        private String value;

        RetentionUnavailableReasonEnum(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        public static RetentionUnavailableReasonEnum fromValue(String value) {
            for (RetentionUnavailableReasonEnum b : RetentionUnavailableReasonEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            return null;
        }

        public static class Adapter extends TypeAdapter<RetentionUnavailableReasonEnum> {
            @Override
            public void write(
                    final JsonWriter jsonWriter, final RetentionUnavailableReasonEnum enumeration)
                    throws IOException {
                jsonWriter.value(enumeration.getValue());
            }

            @Override
            public RetentionUnavailableReasonEnum read(final JsonReader jsonReader)
                    throws IOException {
                String value = jsonReader.nextString();
                return RetentionUnavailableReasonEnum.fromValue(value);
            }
        }

        public static void validateJsonElement(JsonElement jsonElement) throws IOException {
            String value = jsonElement.getAsString();
            RetentionUnavailableReasonEnum.fromValue(value);
        }
    }

    public static final String SERIALIZED_NAME_RETENTION_UNAVAILABLE_REASON =
            "retention_unavailable_reason";

    @SerializedName(SERIALIZED_NAME_RETENTION_UNAVAILABLE_REASON)
    @jakarta.annotation.Nullable private RetentionUnavailableReasonEnum retentionUnavailableReason;

    public AuditAdoptionHistory() {}

    public AuditAdoptionHistory earliestObservedAt(
            @jakarta.annotation.Nullable OffsetDateTime earliestObservedAt) {
        this.earliestObservedAt = earliestObservedAt;
        return this;
    }

    /**
     * Get earliestObservedAt
     * @return earliestObservedAt
     */
    @jakarta.annotation.Nullable public OffsetDateTime getEarliestObservedAt() {
        return earliestObservedAt;
    }

    public void setEarliestObservedAt(
            @jakarta.annotation.Nullable OffsetDateTime earliestObservedAt) {
        this.earliestObservedAt = earliestObservedAt;
    }

    public AuditAdoptionHistory coverageFrom(
            @jakarta.annotation.Nullable OffsetDateTime coverageFrom) {
        this.coverageFrom = coverageFrom;
        return this;
    }

    /**
     * Authoritative complete-history boundary, if known. Earliest observation is not a coverage boundary.
     * @return coverageFrom
     */
    @jakarta.annotation.Nullable public OffsetDateTime getCoverageFrom() {
        return coverageFrom;
    }

    public void setCoverageFrom(@jakarta.annotation.Nullable OffsetDateTime coverageFrom) {
        this.coverageFrom = coverageFrom;
    }

    public AuditAdoptionHistory completeness(
            @jakarta.annotation.Nonnull CompletenessEnum completeness) {
        this.completeness = completeness;
        return this;
    }

    /**
     * Get completeness
     * @return completeness
     */
    @jakarta.annotation.Nonnull
    public CompletenessEnum getCompleteness() {
        return completeness;
    }

    public void setCompleteness(@jakarta.annotation.Nonnull CompletenessEnum completeness) {
        this.completeness = completeness;
    }

    public AuditAdoptionHistory retentionUnavailableReason(
            @jakarta.annotation.Nullable RetentionUnavailableReasonEnum retentionUnavailableReason) {
        this.retentionUnavailableReason = retentionUnavailableReason;
        return this;
    }

    /**
     * Get retentionUnavailableReason
     * @return retentionUnavailableReason
     */
    @jakarta.annotation.Nullable public RetentionUnavailableReasonEnum getRetentionUnavailableReason() {
        return retentionUnavailableReason;
    }

    public void setRetentionUnavailableReason(
            @jakarta.annotation.Nullable RetentionUnavailableReasonEnum retentionUnavailableReason) {
        this.retentionUnavailableReason = retentionUnavailableReason;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AuditAdoptionHistory auditAdoptionHistory = (AuditAdoptionHistory) o;
        return Objects.equals(this.earliestObservedAt, auditAdoptionHistory.earliestObservedAt)
                && Objects.equals(this.coverageFrom, auditAdoptionHistory.coverageFrom)
                && Objects.equals(this.completeness, auditAdoptionHistory.completeness)
                && Objects.equals(
                        this.retentionUnavailableReason,
                        auditAdoptionHistory.retentionUnavailableReason);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                earliestObservedAt, coverageFrom, completeness, retentionUnavailableReason);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class AuditAdoptionHistory {\n");
        sb.append("    earliestObservedAt: ")
                .append(toIndentedString(earliestObservedAt))
                .append("\n");
        sb.append("    coverageFrom: ").append(toIndentedString(coverageFrom)).append("\n");
        sb.append("    completeness: ").append(toIndentedString(completeness)).append("\n");
        sb.append("    retentionUnavailableReason: ")
                .append(toIndentedString(retentionUnavailableReason))
                .append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        return o == null ? "null" : o.toString().replace("\n", "\n    ");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields =
                new HashSet<String>(
                        Arrays.asList(
                                "earliest_observed_at",
                                "coverage_from",
                                "completeness",
                                "retention_unavailable_reason"));

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields =
                new HashSet<String>(
                        Arrays.asList(
                                "earliest_observed_at",
                                "coverage_from",
                                "completeness",
                                "retention_unavailable_reason"));
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to AuditAdoptionHistory
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!AuditAdoptionHistory.openapiRequiredFields
                    .isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(
                        String.format(
                                java.util.Locale.ROOT,
                                "The required field(s) %s in AuditAdoptionHistory is not found in the empty JSON string",
                                AuditAdoptionHistory.openapiRequiredFields.toString()));
            }
        }

        // check to make sure all required properties/fields are present in the JSON string
        for (String requiredField : AuditAdoptionHistory.openapiRequiredFields) {
            if (jsonElement.getAsJsonObject().get(requiredField) == null) {
                throw new IllegalArgumentException(
                        String.format(
                                java.util.Locale.ROOT,
                                "The required field `%s` is not found in the JSON string: %s",
                                requiredField,
                                jsonElement.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if (!jsonObj.get("completeness").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `completeness` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("completeness").toString()));
        }
        // validate the required field `completeness`
        CompletenessEnum.validateJsonElement(jsonObj.get("completeness"));
        if ((jsonObj.get("retention_unavailable_reason") != null
                        && !jsonObj.get("retention_unavailable_reason").isJsonNull())
                && !jsonObj.get("retention_unavailable_reason").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `retention_unavailable_reason` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("retention_unavailable_reason").toString()));
        }
        if (jsonObj.get("retention_unavailable_reason") != null
                && !jsonObj.get("retention_unavailable_reason").isJsonNull()) {
            // validate the required field `retention_unavailable_reason`
            RetentionUnavailableReasonEnum.validateJsonElement(
                    jsonObj.get("retention_unavailable_reason"));
        }
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!AuditAdoptionHistory.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'AuditAdoptionHistory' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<AuditAdoptionHistory> thisAdapter =
                    gson.getDelegateAdapter(this, TypeToken.get(AuditAdoptionHistory.class));

            return (TypeAdapter<T>)
                    new TypeAdapter<AuditAdoptionHistory>() {
                        @Override
                        public void write(JsonWriter out, AuditAdoptionHistory value)
                                throws IOException {
                            JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                            elementAdapter.write(out, obj);
                        }

                        @Override
                        public AuditAdoptionHistory read(JsonReader in) throws IOException {
                            JsonElement jsonElement = elementAdapter.read(in);
                            validateJsonElement(jsonElement);
                            return thisAdapter.fromJsonTree(jsonElement);
                        }
                    }.nullSafe();
        }
    }

    /**
     * Create an instance of AuditAdoptionHistory given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of AuditAdoptionHistory
     * @throws IOException if the JSON string is invalid with respect to AuditAdoptionHistory
     */
    public static AuditAdoptionHistory fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, AuditAdoptionHistory.class);
    }

    /**
     * Convert an instance of AuditAdoptionHistory to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
