/*
 * Vertesia API
 * The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.
 *
 * The version of the OpenAPI document: 1.4.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.vertesia.model;

import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.vertesia.JSON;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/**
 * CostRunPriceResponse
 */
@jakarta.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.22.0")
public class CostRunPriceResponse {
    public static final String SERIALIZED_NAME_SUMMARY = "summary";

    @SerializedName(SERIALIZED_NAME_SUMMARY)
    @jakarta.annotation.Nonnull
    private CostSummary summary;

    public static final String SERIALIZED_NAME_BY_MODEL = "by_model";

    @SerializedName(SERIALIZED_NAME_BY_MODEL)
    @jakarta.annotation.Nonnull
    private List<CostByDimension> byModel = new ArrayList<>();

    public static final String SERIALIZED_NAME_PRICING = "pricing";

    @SerializedName(SERIALIZED_NAME_PRICING)
    @jakarta.annotation.Nullable private List<ModelPricing> pricing = new ArrayList<>();

    public static final String SERIALIZED_NAME_QUERY_RANGE = "query_range";

    @SerializedName(SERIALIZED_NAME_QUERY_RANGE)
    @jakarta.annotation.Nullable private CostAnalyticsResponseQueryRange queryRange;

    /**
     * Gets or Sets pricingSource
     */
    @JsonAdapter(PricingSourceEnum.Adapter.class)
    public enum PricingSourceEnum {
        LIST("list"),

        HISTORICAL("historical"),

        UNKNOWN_DEFAULT_OPEN_API("unknown_default_open_api");

        private String value;

        PricingSourceEnum(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        public static PricingSourceEnum fromValue(String value) {
            for (PricingSourceEnum b : PricingSourceEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            return UNKNOWN_DEFAULT_OPEN_API;
        }

        public static class Adapter extends TypeAdapter<PricingSourceEnum> {
            @Override
            public void write(final JsonWriter jsonWriter, final PricingSourceEnum enumeration)
                    throws IOException {
                jsonWriter.value(enumeration.getValue());
            }

            @Override
            public PricingSourceEnum read(final JsonReader jsonReader) throws IOException {
                String value = jsonReader.nextString();
                return PricingSourceEnum.fromValue(value);
            }
        }

        public static void validateJsonElement(JsonElement jsonElement) throws IOException {
            String value = jsonElement.getAsString();
            PricingSourceEnum.fromValue(value);
        }
    }

    public static final String SERIALIZED_NAME_PRICING_SOURCE = "pricing_source";

    @SerializedName(SERIALIZED_NAME_PRICING_SOURCE)
    @jakarta.annotation.Nonnull
    private PricingSourceEnum pricingSource;

    public static final String SERIALIZED_NAME_MATCHED_EVENTS = "matched_events";

    @SerializedName(SERIALIZED_NAME_MATCHED_EVENTS)
    @jakarta.annotation.Nonnull
    private BigDecimal matchedEvents;

    public CostRunPriceResponse() {}

    public CostRunPriceResponse summary(@jakarta.annotation.Nonnull CostSummary summary) {
        this.summary = summary;
        return this;
    }

    /**
     * Get summary
     * @return summary
     */
    @jakarta.annotation.Nonnull
    public CostSummary getSummary() {
        return summary;
    }

    public void setSummary(@jakarta.annotation.Nonnull CostSummary summary) {
        this.summary = summary;
    }

    public CostRunPriceResponse byModel(@jakarta.annotation.Nonnull List<CostByDimension> byModel) {
        this.byModel = byModel;
        return this;
    }

    public CostRunPriceResponse addByModelItem(CostByDimension byModelItem) {
        if (this.byModel == null) {
            this.byModel = new ArrayList<>();
        }
        this.byModel.add(byModelItem);
        return this;
    }

    /**
     * Get byModel
     * @return byModel
     */
    @jakarta.annotation.Nonnull
    public List<CostByDimension> getByModel() {
        return byModel;
    }

    public void setByModel(@jakarta.annotation.Nonnull List<CostByDimension> byModel) {
        this.byModel = byModel;
    }

    public CostRunPriceResponse pricing(@jakarta.annotation.Nullable List<ModelPricing> pricing) {
        this.pricing = pricing;
        return this;
    }

    public CostRunPriceResponse addPricingItem(ModelPricing pricingItem) {
        if (this.pricing == null) {
            this.pricing = new ArrayList<>();
        }
        this.pricing.add(pricingItem);
        return this;
    }

    /**
     * Get pricing
     * @return pricing
     */
    @jakarta.annotation.Nullable public List<ModelPricing> getPricing() {
        return pricing;
    }

    public void setPricing(@jakarta.annotation.Nullable List<ModelPricing> pricing) {
        this.pricing = pricing;
    }

    public CostRunPriceResponse queryRange(
            @jakarta.annotation.Nullable CostAnalyticsResponseQueryRange queryRange) {
        this.queryRange = queryRange;
        return this;
    }

    /**
     * Get queryRange
     * @return queryRange
     */
    @jakarta.annotation.Nullable public CostAnalyticsResponseQueryRange getQueryRange() {
        return queryRange;
    }

    public void setQueryRange(
            @jakarta.annotation.Nullable CostAnalyticsResponseQueryRange queryRange) {
        this.queryRange = queryRange;
    }

    public CostRunPriceResponse pricingSource(
            @jakarta.annotation.Nonnull PricingSourceEnum pricingSource) {
        this.pricingSource = pricingSource;
        return this;
    }

    /**
     * Get pricingSource
     * @return pricingSource
     */
    @jakarta.annotation.Nonnull
    public PricingSourceEnum getPricingSource() {
        return pricingSource;
    }

    public void setPricingSource(@jakarta.annotation.Nonnull PricingSourceEnum pricingSource) {
        this.pricingSource = pricingSource;
    }

    public CostRunPriceResponse matchedEvents(
            @jakarta.annotation.Nonnull BigDecimal matchedEvents) {
        this.matchedEvents = matchedEvents;
        return this;
    }

    /**
     * Get matchedEvents
     * @return matchedEvents
     */
    @jakarta.annotation.Nonnull
    public BigDecimal getMatchedEvents() {
        return matchedEvents;
    }

    public void setMatchedEvents(@jakarta.annotation.Nonnull BigDecimal matchedEvents) {
        this.matchedEvents = matchedEvents;
    }

    /**
     * A container for additional, undeclared properties.
     * This is a holder for any undeclared properties as specified with
     * the 'additionalProperties' keyword in the OAS document.
     */
    private Map<String, Object> additionalProperties;

    /**
     * Set the additional (undeclared) property with the specified name and value.
     * If the property does not already exist, create it otherwise replace it.
     *
     * @param key name of the property
     * @param value value of the property
     * @return the CostRunPriceResponse instance itself
     */
    public CostRunPriceResponse putAdditionalProperty(String key, Object value) {
        if (this.additionalProperties == null) {
            this.additionalProperties = new HashMap<String, Object>();
        }
        this.additionalProperties.put(key, value);
        return this;
    }

    /**
     * Return the additional (undeclared) property.
     *
     * @return a map of objects
     */
    public Map<String, Object> getAdditionalProperties() {
        return additionalProperties;
    }

    /**
     * Return the additional (undeclared) property with the specified name.
     *
     * @param key name of the property
     * @return an object
     */
    public Object getAdditionalProperty(String key) {
        if (this.additionalProperties == null) {
            return null;
        }
        return this.additionalProperties.get(key);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CostRunPriceResponse costRunPriceResponse = (CostRunPriceResponse) o;
        return Objects.equals(this.summary, costRunPriceResponse.summary)
                && Objects.equals(this.byModel, costRunPriceResponse.byModel)
                && Objects.equals(this.pricing, costRunPriceResponse.pricing)
                && Objects.equals(this.queryRange, costRunPriceResponse.queryRange)
                && Objects.equals(this.pricingSource, costRunPriceResponse.pricingSource)
                && Objects.equals(this.matchedEvents, costRunPriceResponse.matchedEvents)
                && Objects.equals(
                        this.additionalProperties, costRunPriceResponse.additionalProperties);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                summary,
                byModel,
                pricing,
                queryRange,
                pricingSource,
                matchedEvents,
                additionalProperties);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class CostRunPriceResponse {\n");
        sb.append("    summary: ").append(toIndentedString(summary)).append("\n");
        sb.append("    byModel: ").append(toIndentedString(byModel)).append("\n");
        sb.append("    pricing: ").append(toIndentedString(pricing)).append("\n");
        sb.append("    queryRange: ").append(toIndentedString(queryRange)).append("\n");
        sb.append("    pricingSource: ").append(toIndentedString(pricingSource)).append("\n");
        sb.append("    matchedEvents: ").append(toIndentedString(matchedEvents)).append("\n");
        sb.append("    additionalProperties: ")
                .append(toIndentedString(additionalProperties))
                .append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        return o == null ? "null" : o.toString().replace("\n", "\n    ");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields =
                new HashSet<String>(
                        Arrays.asList(
                                "summary",
                                "by_model",
                                "pricing",
                                "query_range",
                                "pricing_source",
                                "matched_events"));

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields =
                new HashSet<String>(
                        Arrays.asList("summary", "by_model", "pricing_source", "matched_events"));
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to CostRunPriceResponse
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!CostRunPriceResponse.openapiRequiredFields
                    .isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(
                        String.format(
                                java.util.Locale.ROOT,
                                "The required field(s) %s in CostRunPriceResponse is not found in the empty JSON string",
                                CostRunPriceResponse.openapiRequiredFields.toString()));
            }
        }

        // check to make sure all required properties/fields are present in the JSON string
        for (String requiredField : CostRunPriceResponse.openapiRequiredFields) {
            if (jsonElement.getAsJsonObject().get(requiredField) == null) {
                throw new IllegalArgumentException(
                        String.format(
                                java.util.Locale.ROOT,
                                "The required field `%s` is not found in the JSON string: %s",
                                requiredField,
                                jsonElement.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        // validate the required field `summary`
        CostSummary.validateJsonElement(jsonObj.get("summary"));
        if (jsonObj.get("by_model") != null) {
            if (!jsonObj.get("by_model").isJsonArray()) {
                throw new IllegalArgumentException(
                        String.format(
                                java.util.Locale.ROOT,
                                "Expected the field `by_model` to be an array in the JSON string but got `%s`",
                                jsonObj.get("by_model").toString()));
            }
            JsonArray jsonArraybyModel = jsonObj.getAsJsonArray("by_model");
            // validate the required field `by_model` (array)
            for (int i = 0; i < jsonArraybyModel.size(); i++) {
                CostByDimension.validateJsonElement(jsonArraybyModel.get(i));
            }
        }
        if (jsonObj.get("pricing") != null && !jsonObj.get("pricing").isJsonNull()) {
            JsonArray jsonArraypricing = jsonObj.getAsJsonArray("pricing");
            if (jsonArraypricing != null) {
                // ensure the json data is an array
                if (!jsonObj.get("pricing").isJsonArray()) {
                    throw new IllegalArgumentException(
                            String.format(
                                    java.util.Locale.ROOT,
                                    "Expected the field `pricing` to be an array in the JSON string but got `%s`",
                                    jsonObj.get("pricing").toString()));
                }

                // validate the optional field `pricing` (array)
                for (int i = 0; i < jsonArraypricing.size(); i++) {
                    ModelPricing.validateJsonElement(jsonArraypricing.get(i));
                }
                ;
            }
        }
        // validate the optional field `query_range`
        if (jsonObj.get("query_range") != null && !jsonObj.get("query_range").isJsonNull()) {
            CostAnalyticsResponseQueryRange.validateJsonElement(jsonObj.get("query_range"));
        }
        if (!jsonObj.get("pricing_source").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `pricing_source` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("pricing_source").toString()));
        }
        // validate the required field `pricing_source`
        PricingSourceEnum.validateJsonElement(jsonObj.get("pricing_source"));
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!CostRunPriceResponse.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'CostRunPriceResponse' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<CostRunPriceResponse> thisAdapter =
                    gson.getDelegateAdapter(this, TypeToken.get(CostRunPriceResponse.class));

            return (TypeAdapter<T>)
                    new TypeAdapter<CostRunPriceResponse>() {
                        @Override
                        public void write(JsonWriter out, CostRunPriceResponse value)
                                throws IOException {
                            JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                            obj.remove("additionalProperties");
                            // serialize additional properties
                            if (value.getAdditionalProperties() != null) {
                                for (Map.Entry<String, Object> entry :
                                        value.getAdditionalProperties().entrySet()) {
                                    if (entry.getValue() instanceof String)
                                        obj.addProperty(entry.getKey(), (String) entry.getValue());
                                    else if (entry.getValue() instanceof Number)
                                        obj.addProperty(entry.getKey(), (Number) entry.getValue());
                                    else if (entry.getValue() instanceof Boolean)
                                        obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                                    else if (entry.getValue() instanceof Character)
                                        obj.addProperty(
                                                entry.getKey(), (Character) entry.getValue());
                                    else {
                                        JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                                        if (jsonElement.isJsonArray()) {
                                            obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                                        } else {
                                            obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                                        }
                                    }
                                }
                            }
                            elementAdapter.write(out, obj);
                        }

                        @Override
                        public CostRunPriceResponse read(JsonReader in) throws IOException {
                            JsonElement jsonElement = elementAdapter.read(in);
                            validateJsonElement(jsonElement);
                            JsonObject jsonObj = jsonElement.getAsJsonObject();
                            // store additional fields in the deserialized instance
                            CostRunPriceResponse instance = thisAdapter.fromJsonTree(jsonObj);
                            for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
                                if (!openapiFields.contains(entry.getKey())) {
                                    if (entry.getValue().isJsonPrimitive()) { // primitive type
                                        if (entry.getValue().getAsJsonPrimitive().isString())
                                            instance.putAdditionalProperty(
                                                    entry.getKey(), entry.getValue().getAsString());
                                        else if (entry.getValue().getAsJsonPrimitive().isNumber())
                                            instance.putAdditionalProperty(
                                                    entry.getKey(), entry.getValue().getAsNumber());
                                        else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                                            instance.putAdditionalProperty(
                                                    entry.getKey(),
                                                    entry.getValue().getAsBoolean());
                                        else
                                            throw new IllegalArgumentException(
                                                    String.format(
                                                            java.util.Locale.ROOT,
                                                            "The field `%s` has unknown primitive type. Value: %s",
                                                            entry.getKey(),
                                                            entry.getValue().toString()));
                                    } else if (entry.getValue().isJsonArray()) {
                                        instance.putAdditionalProperty(
                                                entry.getKey(),
                                                gson.fromJson(entry.getValue(), List.class));
                                    } else { // JSON object
                                        instance.putAdditionalProperty(
                                                entry.getKey(),
                                                gson.fromJson(entry.getValue(), HashMap.class));
                                    }
                                }
                            }
                            return instance;
                        }
                    }.nullSafe();
        }
    }

    /**
     * Create an instance of CostRunPriceResponse given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of CostRunPriceResponse
     * @throws IOException if the JSON string is invalid with respect to CostRunPriceResponse
     */
    public static CostRunPriceResponse fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, CostRunPriceResponse.class);
    }

    /**
     * Convert an instance of CostRunPriceResponse to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
