/*
 * Vertesia API
 * The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.
 *
 * The version of the OpenAPI document: 1.5.0-dev.20260905.011013Z
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.vertesia.model;

import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.vertesia.JSON;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashSet;
import java.util.List;
import java.util.Objects;

/**
 * CostAnalyticsResponsePricingCoverage
 */
@jakarta.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.22.0")
public class CostAnalyticsResponsePricingCoverage {
    public static final String SERIALIZED_NAME_PRICED_CALLS = "priced_calls";

    @SerializedName(SERIALIZED_NAME_PRICED_CALLS)
    @jakarta.annotation.Nonnull
    private BigDecimal pricedCalls;

    public static final String SERIALIZED_NAME_UNPRICED_CALLS = "unpriced_calls";

    @SerializedName(SERIALIZED_NAME_UNPRICED_CALLS)
    @jakarta.annotation.Nonnull
    private BigDecimal unpricedCalls;

    public static final String SERIALIZED_NAME_ASSUMED_DEFAULT_CALLS = "assumed_default_calls";

    @SerializedName(SERIALIZED_NAME_ASSUMED_DEFAULT_CALLS)
    @jakarta.annotation.Nonnull
    private BigDecimal assumedDefaultCalls;

    public static final String SERIALIZED_NAME_UNPRICED = "unpriced";

    @SerializedName(SERIALIZED_NAME_UNPRICED)
    @jakarta.annotation.Nonnull
    private List<CostAnalyticsResponsePricingCoverageUnpricedInner> unpriced = new ArrayList<>();

    public CostAnalyticsResponsePricingCoverage() {}

    public CostAnalyticsResponsePricingCoverage pricedCalls(
            @jakarta.annotation.Nonnull BigDecimal pricedCalls) {
        this.pricedCalls = pricedCalls;
        return this;
    }

    /**
     * Get pricedCalls
     * @return pricedCalls
     */
    @jakarta.annotation.Nonnull
    public BigDecimal getPricedCalls() {
        return pricedCalls;
    }

    public void setPricedCalls(@jakarta.annotation.Nonnull BigDecimal pricedCalls) {
        this.pricedCalls = pricedCalls;
    }

    public CostAnalyticsResponsePricingCoverage unpricedCalls(
            @jakarta.annotation.Nonnull BigDecimal unpricedCalls) {
        this.unpricedCalls = unpricedCalls;
        return this;
    }

    /**
     * Get unpricedCalls
     * @return unpricedCalls
     */
    @jakarta.annotation.Nonnull
    public BigDecimal getUnpricedCalls() {
        return unpricedCalls;
    }

    public void setUnpricedCalls(@jakarta.annotation.Nonnull BigDecimal unpricedCalls) {
        this.unpricedCalls = unpricedCalls;
    }

    public CostAnalyticsResponsePricingCoverage assumedDefaultCalls(
            @jakarta.annotation.Nonnull BigDecimal assumedDefaultCalls) {
        this.assumedDefaultCalls = assumedDefaultCalls;
        return this;
    }

    /**
     * Get assumedDefaultCalls
     * @return assumedDefaultCalls
     */
    @jakarta.annotation.Nonnull
    public BigDecimal getAssumedDefaultCalls() {
        return assumedDefaultCalls;
    }

    public void setAssumedDefaultCalls(@jakarta.annotation.Nonnull BigDecimal assumedDefaultCalls) {
        this.assumedDefaultCalls = assumedDefaultCalls;
    }

    public CostAnalyticsResponsePricingCoverage unpriced(
            @jakarta.annotation.Nonnull
                    List<CostAnalyticsResponsePricingCoverageUnpricedInner> unpriced) {
        this.unpriced = unpriced;
        return this;
    }

    public CostAnalyticsResponsePricingCoverage addUnpricedItem(
            CostAnalyticsResponsePricingCoverageUnpricedInner unpricedItem) {
        if (this.unpriced == null) {
            this.unpriced = new ArrayList<>();
        }
        this.unpriced.add(unpricedItem);
        return this;
    }

    /**
     * Get unpriced
     * @return unpriced
     */
    @jakarta.annotation.Nonnull
    public List<CostAnalyticsResponsePricingCoverageUnpricedInner> getUnpriced() {
        return unpriced;
    }

    public void setUnpriced(
            @jakarta.annotation.Nonnull
                    List<CostAnalyticsResponsePricingCoverageUnpricedInner> unpriced) {
        this.unpriced = unpriced;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CostAnalyticsResponsePricingCoverage costAnalyticsResponsePricingCoverage =
                (CostAnalyticsResponsePricingCoverage) o;
        return Objects.equals(this.pricedCalls, costAnalyticsResponsePricingCoverage.pricedCalls)
                && Objects.equals(
                        this.unpricedCalls, costAnalyticsResponsePricingCoverage.unpricedCalls)
                && Objects.equals(
                        this.assumedDefaultCalls,
                        costAnalyticsResponsePricingCoverage.assumedDefaultCalls)
                && Objects.equals(this.unpriced, costAnalyticsResponsePricingCoverage.unpriced);
    }

    @Override
    public int hashCode() {
        return Objects.hash(pricedCalls, unpricedCalls, assumedDefaultCalls, unpriced);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class CostAnalyticsResponsePricingCoverage {\n");
        sb.append("    pricedCalls: ").append(toIndentedString(pricedCalls)).append("\n");
        sb.append("    unpricedCalls: ").append(toIndentedString(unpricedCalls)).append("\n");
        sb.append("    assumedDefaultCalls: ")
                .append(toIndentedString(assumedDefaultCalls))
                .append("\n");
        sb.append("    unpriced: ").append(toIndentedString(unpriced)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        return o == null ? "null" : o.toString().replace("\n", "\n    ");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields =
                new HashSet<String>(
                        Arrays.asList(
                                "priced_calls",
                                "unpriced_calls",
                                "assumed_default_calls",
                                "unpriced"));

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields =
                new HashSet<String>(
                        Arrays.asList(
                                "priced_calls",
                                "unpriced_calls",
                                "assumed_default_calls",
                                "unpriced"));
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to CostAnalyticsResponsePricingCoverage
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!CostAnalyticsResponsePricingCoverage.openapiRequiredFields
                    .isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(
                        String.format(
                                java.util.Locale.ROOT,
                                "The required field(s) %s in CostAnalyticsResponsePricingCoverage is not found in the empty JSON string",
                                CostAnalyticsResponsePricingCoverage.openapiRequiredFields
                                        .toString()));
            }
        }

        // check to make sure all required properties/fields are present in the JSON string
        for (String requiredField : CostAnalyticsResponsePricingCoverage.openapiRequiredFields) {
            if (jsonElement.getAsJsonObject().get(requiredField) == null) {
                throw new IllegalArgumentException(
                        String.format(
                                java.util.Locale.ROOT,
                                "The required field `%s` is not found in the JSON string: %s",
                                requiredField,
                                jsonElement.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if (jsonObj.get("unpriced") != null) {
            if (!jsonObj.get("unpriced").isJsonArray()) {
                throw new IllegalArgumentException(
                        String.format(
                                java.util.Locale.ROOT,
                                "Expected the field `unpriced` to be an array in the JSON string but got `%s`",
                                jsonObj.get("unpriced").toString()));
            }
            JsonArray jsonArrayunpriced = jsonObj.getAsJsonArray("unpriced");
            // validate the required field `unpriced` (array)
            for (int i = 0; i < jsonArrayunpriced.size(); i++) {
                CostAnalyticsResponsePricingCoverageUnpricedInner.validateJsonElement(
                        jsonArrayunpriced.get(i));
            }
        }
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!CostAnalyticsResponsePricingCoverage.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'CostAnalyticsResponsePricingCoverage'
                // and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<CostAnalyticsResponsePricingCoverage> thisAdapter =
                    gson.getDelegateAdapter(
                            this, TypeToken.get(CostAnalyticsResponsePricingCoverage.class));

            return (TypeAdapter<T>)
                    new TypeAdapter<CostAnalyticsResponsePricingCoverage>() {
                        @Override
                        public void write(
                                JsonWriter out, CostAnalyticsResponsePricingCoverage value)
                                throws IOException {
                            JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                            elementAdapter.write(out, obj);
                        }

                        @Override
                        public CostAnalyticsResponsePricingCoverage read(JsonReader in)
                                throws IOException {
                            JsonElement jsonElement = elementAdapter.read(in);
                            validateJsonElement(jsonElement);
                            return thisAdapter.fromJsonTree(jsonElement);
                        }
                    }.nullSafe();
        }
    }

    /**
     * Create an instance of CostAnalyticsResponsePricingCoverage given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of CostAnalyticsResponsePricingCoverage
     * @throws IOException if the JSON string is invalid with respect to CostAnalyticsResponsePricingCoverage
     */
    public static CostAnalyticsResponsePricingCoverage fromJson(String jsonString)
            throws IOException {
        return JSON.getGson().fromJson(jsonString, CostAnalyticsResponsePricingCoverage.class);
    }

    /**
     * Convert an instance of CostAnalyticsResponsePricingCoverage to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
