/*
 * Vertesia API
 * The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` SDK for typed access from Node.js applications.
 *
 * The version of the OpenAPI document: 1.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.vertesia.model;

import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.vertesia.JSON;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashSet;
import java.util.List;
import java.util.Objects;

/**
 * Complete schema definition for a data store.
 */
@jakarta.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.22.0")
public class DataSchema {
    public static final String SERIALIZED_NAME_VERSION = "version";

    @SerializedName(SERIALIZED_NAME_VERSION)
    @jakarta.annotation.Nonnull
    private String version;

    public static final String SERIALIZED_NAME_DESCRIPTION = "description";

    @SerializedName(SERIALIZED_NAME_DESCRIPTION)
    @jakarta.annotation.Nullable private String description;

    public static final String SERIALIZED_NAME_TABLES = "tables";

    @SerializedName(SERIALIZED_NAME_TABLES)
    @jakarta.annotation.Nonnull
    private List<DataTable> tables = new ArrayList<>();

    public static final String SERIALIZED_NAME_RELATIONSHIPS = "relationships";

    @SerializedName(SERIALIZED_NAME_RELATIONSHIPS)
    @jakarta.annotation.Nonnull
    private List<DataRelationship> relationships = new ArrayList<>();

    public static final String SERIALIZED_NAME_UPDATED_AT = "updated_at";

    @SerializedName(SERIALIZED_NAME_UPDATED_AT)
    @jakarta.annotation.Nonnull
    private String updatedAt;

    public static final String SERIALIZED_NAME_UPDATED_BY = "updated_by";

    @SerializedName(SERIALIZED_NAME_UPDATED_BY)
    @jakarta.annotation.Nullable private String updatedBy;

    public DataSchema() {}

    public DataSchema version(@jakarta.annotation.Nonnull String version) {
        this.version = version;
        return this;
    }

    /**
     * Semantic version (e.g., \&quot;1.2.0\&quot;)
     * @return version
     */
    @jakarta.annotation.Nonnull
    public String getVersion() {
        return version;
    }

    public void setVersion(@jakarta.annotation.Nonnull String version) {
        this.version = version;
    }

    public DataSchema description(@jakarta.annotation.Nullable String description) {
        this.description = description;
        return this;
    }

    /**
     * Schema description
     * @return description
     */
    @jakarta.annotation.Nullable public String getDescription() {
        return description;
    }

    public void setDescription(@jakarta.annotation.Nullable String description) {
        this.description = description;
    }

    public DataSchema tables(@jakarta.annotation.Nonnull List<DataTable> tables) {
        this.tables = tables;
        return this;
    }

    public DataSchema addTablesItem(DataTable tablesItem) {
        if (this.tables == null) {
            this.tables = new ArrayList<>();
        }
        this.tables.add(tablesItem);
        return this;
    }

    /**
     * Table definitions
     * @return tables
     */
    @jakarta.annotation.Nonnull
    public List<DataTable> getTables() {
        return tables;
    }

    public void setTables(@jakarta.annotation.Nonnull List<DataTable> tables) {
        this.tables = tables;
    }

    public DataSchema relationships(
            @jakarta.annotation.Nonnull List<DataRelationship> relationships) {
        this.relationships = relationships;
        return this;
    }

    public DataSchema addRelationshipsItem(DataRelationship relationshipsItem) {
        if (this.relationships == null) {
            this.relationships = new ArrayList<>();
        }
        this.relationships.add(relationshipsItem);
        return this;
    }

    /**
     * Relationship definitions
     * @return relationships
     */
    @jakarta.annotation.Nonnull
    public List<DataRelationship> getRelationships() {
        return relationships;
    }

    public void setRelationships(@jakarta.annotation.Nonnull List<DataRelationship> relationships) {
        this.relationships = relationships;
    }

    public DataSchema updatedAt(@jakarta.annotation.Nonnull String updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }

    /**
     * Last update timestamp
     * @return updatedAt
     */
    @jakarta.annotation.Nonnull
    public String getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(@jakarta.annotation.Nonnull String updatedAt) {
        this.updatedAt = updatedAt;
    }

    public DataSchema updatedBy(@jakarta.annotation.Nullable String updatedBy) {
        this.updatedBy = updatedBy;
        return this;
    }

    /**
     * User/agent who last updated
     * @return updatedBy
     */
    @jakarta.annotation.Nullable public String getUpdatedBy() {
        return updatedBy;
    }

    public void setUpdatedBy(@jakarta.annotation.Nullable String updatedBy) {
        this.updatedBy = updatedBy;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DataSchema dataSchema = (DataSchema) o;
        return Objects.equals(this.version, dataSchema.version)
                && Objects.equals(this.description, dataSchema.description)
                && Objects.equals(this.tables, dataSchema.tables)
                && Objects.equals(this.relationships, dataSchema.relationships)
                && Objects.equals(this.updatedAt, dataSchema.updatedAt)
                && Objects.equals(this.updatedBy, dataSchema.updatedBy);
    }

    @Override
    public int hashCode() {
        return Objects.hash(version, description, tables, relationships, updatedAt, updatedBy);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class DataSchema {\n");
        sb.append("    version: ").append(toIndentedString(version)).append("\n");
        sb.append("    description: ").append(toIndentedString(description)).append("\n");
        sb.append("    tables: ").append(toIndentedString(tables)).append("\n");
        sb.append("    relationships: ").append(toIndentedString(relationships)).append("\n");
        sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
        sb.append("    updatedBy: ").append(toIndentedString(updatedBy)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        return o == null ? "null" : o.toString().replace("\n", "\n    ");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields =
                new HashSet<String>(
                        Arrays.asList(
                                "version",
                                "description",
                                "tables",
                                "relationships",
                                "updated_at",
                                "updated_by"));

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields =
                new HashSet<String>(
                        Arrays.asList("version", "tables", "relationships", "updated_at"));
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to DataSchema
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!DataSchema.openapiRequiredFields
                    .isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(
                        String.format(
                                java.util.Locale.ROOT,
                                "The required field(s) %s in DataSchema is not found in the empty JSON string",
                                DataSchema.openapiRequiredFields.toString()));
            }
        }

        // check to make sure all required properties/fields are present in the JSON string
        for (String requiredField : DataSchema.openapiRequiredFields) {
            if (jsonElement.getAsJsonObject().get(requiredField) == null) {
                throw new IllegalArgumentException(
                        String.format(
                                java.util.Locale.ROOT,
                                "The required field `%s` is not found in the JSON string: %s",
                                requiredField,
                                jsonElement.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if (!jsonObj.get("version").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `version` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("version").toString()));
        }
        if ((jsonObj.get("description") != null && !jsonObj.get("description").isJsonNull())
                && !jsonObj.get("description").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `description` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("description").toString()));
        }
        if (jsonObj.get("tables") != null) {
            if (!jsonObj.get("tables").isJsonArray()) {
                throw new IllegalArgumentException(
                        String.format(
                                java.util.Locale.ROOT,
                                "Expected the field `tables` to be an array in the JSON string but got `%s`",
                                jsonObj.get("tables").toString()));
            }
            JsonArray jsonArraytables = jsonObj.getAsJsonArray("tables");
            // validate the required field `tables` (array)
            for (int i = 0; i < jsonArraytables.size(); i++) {
                DataTable.validateJsonElement(jsonArraytables.get(i));
            }
        }
        if (jsonObj.get("relationships") != null) {
            if (!jsonObj.get("relationships").isJsonArray()) {
                throw new IllegalArgumentException(
                        String.format(
                                java.util.Locale.ROOT,
                                "Expected the field `relationships` to be an array in the JSON string but got `%s`",
                                jsonObj.get("relationships").toString()));
            }
            JsonArray jsonArrayrelationships = jsonObj.getAsJsonArray("relationships");
            // validate the required field `relationships` (array)
            for (int i = 0; i < jsonArrayrelationships.size(); i++) {
                DataRelationship.validateJsonElement(jsonArrayrelationships.get(i));
            }
        }
        if (!jsonObj.get("updated_at").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `updated_at` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("updated_at").toString()));
        }
        if ((jsonObj.get("updated_by") != null && !jsonObj.get("updated_by").isJsonNull())
                && !jsonObj.get("updated_by").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `updated_by` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("updated_by").toString()));
        }
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!DataSchema.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'DataSchema' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<DataSchema> thisAdapter =
                    gson.getDelegateAdapter(this, TypeToken.get(DataSchema.class));

            return (TypeAdapter<T>)
                    new TypeAdapter<DataSchema>() {
                        @Override
                        public void write(JsonWriter out, DataSchema value) throws IOException {
                            JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                            elementAdapter.write(out, obj);
                        }

                        @Override
                        public DataSchema read(JsonReader in) throws IOException {
                            JsonElement jsonElement = elementAdapter.read(in);
                            validateJsonElement(jsonElement);
                            return thisAdapter.fromJsonTree(jsonElement);
                        }
                    }.nullSafe();
        }
    }

    /**
     * Create an instance of DataSchema given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of DataSchema
     * @throws IOException if the JSON string is invalid with respect to DataSchema
     */
    public static DataSchema fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, DataSchema.class);
    }

    /**
     * Convert an instance of DataSchema to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
