/*
 * Vertesia API
 * The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.
 *
 * The version of the OpenAPI document: 1.5.0-dev.20260725.083715Z
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.vertesia.model;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.vertesia.JSON;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashSet;
import java.util.List;
import java.util.Objects;

/**
 * DataStoreDownloadInfo
 */
@jakarta.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.22.0")
public class DataStoreDownloadInfo {
    public static final String SERIALIZED_NAME_URL = "url";

    @SerializedName(SERIALIZED_NAME_URL)
    @jakarta.annotation.Nonnull
    private String url;

    public static final String SERIALIZED_NAME_GCS_GENERATION = "gcs_generation";

    @SerializedName(SERIALIZED_NAME_GCS_GENERATION)
    @jakarta.annotation.Nonnull
    private BigDecimal gcsGeneration;

    public static final String SERIALIZED_NAME_SCHEMA_VERSION = "schema_version";

    @SerializedName(SERIALIZED_NAME_SCHEMA_VERSION)
    @jakarta.annotation.Nonnull
    private String schemaVersion;

    public static final String SERIALIZED_NAME_STORE_ID = "store_id";

    @SerializedName(SERIALIZED_NAME_STORE_ID)
    @jakarta.annotation.Nonnull
    private String storeId;

    public static final String SERIALIZED_NAME_STORE_NAME = "store_name";

    @SerializedName(SERIALIZED_NAME_STORE_NAME)
    @jakarta.annotation.Nonnull
    private String storeName;

    public static final String SERIALIZED_NAME_TABLES = "tables";

    @SerializedName(SERIALIZED_NAME_TABLES)
    @jakarta.annotation.Nonnull
    private List<String> tables = new ArrayList<>();

    public static final String SERIALIZED_NAME_EXPIRES_IN = "expires_in";

    @SerializedName(SERIALIZED_NAME_EXPIRES_IN)
    @jakarta.annotation.Nonnull
    private BigDecimal expiresIn;

    public DataStoreDownloadInfo() {}

    public DataStoreDownloadInfo url(@jakarta.annotation.Nonnull String url) {
        this.url = url;
        return this;
    }

    /**
     * Get url
     * @return url
     */
    @jakarta.annotation.Nonnull
    public String getUrl() {
        return url;
    }

    public void setUrl(@jakarta.annotation.Nonnull String url) {
        this.url = url;
    }

    public DataStoreDownloadInfo gcsGeneration(
            @jakarta.annotation.Nonnull BigDecimal gcsGeneration) {
        this.gcsGeneration = gcsGeneration;
        return this;
    }

    /**
     * Get gcsGeneration
     * @return gcsGeneration
     */
    @jakarta.annotation.Nonnull
    public BigDecimal getGcsGeneration() {
        return gcsGeneration;
    }

    public void setGcsGeneration(@jakarta.annotation.Nonnull BigDecimal gcsGeneration) {
        this.gcsGeneration = gcsGeneration;
    }

    public DataStoreDownloadInfo schemaVersion(@jakarta.annotation.Nonnull String schemaVersion) {
        this.schemaVersion = schemaVersion;
        return this;
    }

    /**
     * Get schemaVersion
     * @return schemaVersion
     */
    @jakarta.annotation.Nonnull
    public String getSchemaVersion() {
        return schemaVersion;
    }

    public void setSchemaVersion(@jakarta.annotation.Nonnull String schemaVersion) {
        this.schemaVersion = schemaVersion;
    }

    public DataStoreDownloadInfo storeId(@jakarta.annotation.Nonnull String storeId) {
        this.storeId = storeId;
        return this;
    }

    /**
     * Get storeId
     * @return storeId
     */
    @jakarta.annotation.Nonnull
    public String getStoreId() {
        return storeId;
    }

    public void setStoreId(@jakarta.annotation.Nonnull String storeId) {
        this.storeId = storeId;
    }

    public DataStoreDownloadInfo storeName(@jakarta.annotation.Nonnull String storeName) {
        this.storeName = storeName;
        return this;
    }

    /**
     * Get storeName
     * @return storeName
     */
    @jakarta.annotation.Nonnull
    public String getStoreName() {
        return storeName;
    }

    public void setStoreName(@jakarta.annotation.Nonnull String storeName) {
        this.storeName = storeName;
    }

    public DataStoreDownloadInfo tables(@jakarta.annotation.Nonnull List<String> tables) {
        this.tables = tables;
        return this;
    }

    public DataStoreDownloadInfo addTablesItem(String tablesItem) {
        if (this.tables == null) {
            this.tables = new ArrayList<>();
        }
        this.tables.add(tablesItem);
        return this;
    }

    /**
     * Get tables
     * @return tables
     */
    @jakarta.annotation.Nonnull
    public List<String> getTables() {
        return tables;
    }

    public void setTables(@jakarta.annotation.Nonnull List<String> tables) {
        this.tables = tables;
    }

    public DataStoreDownloadInfo expiresIn(@jakarta.annotation.Nonnull BigDecimal expiresIn) {
        this.expiresIn = expiresIn;
        return this;
    }

    /**
     * Get expiresIn
     * @return expiresIn
     */
    @jakarta.annotation.Nonnull
    public BigDecimal getExpiresIn() {
        return expiresIn;
    }

    public void setExpiresIn(@jakarta.annotation.Nonnull BigDecimal expiresIn) {
        this.expiresIn = expiresIn;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DataStoreDownloadInfo dataStoreDownloadInfo = (DataStoreDownloadInfo) o;
        return Objects.equals(this.url, dataStoreDownloadInfo.url)
                && Objects.equals(this.gcsGeneration, dataStoreDownloadInfo.gcsGeneration)
                && Objects.equals(this.schemaVersion, dataStoreDownloadInfo.schemaVersion)
                && Objects.equals(this.storeId, dataStoreDownloadInfo.storeId)
                && Objects.equals(this.storeName, dataStoreDownloadInfo.storeName)
                && Objects.equals(this.tables, dataStoreDownloadInfo.tables)
                && Objects.equals(this.expiresIn, dataStoreDownloadInfo.expiresIn);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                url, gcsGeneration, schemaVersion, storeId, storeName, tables, expiresIn);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class DataStoreDownloadInfo {\n");
        sb.append("    url: ").append(toIndentedString(url)).append("\n");
        sb.append("    gcsGeneration: ").append(toIndentedString(gcsGeneration)).append("\n");
        sb.append("    schemaVersion: ").append(toIndentedString(schemaVersion)).append("\n");
        sb.append("    storeId: ").append(toIndentedString(storeId)).append("\n");
        sb.append("    storeName: ").append(toIndentedString(storeName)).append("\n");
        sb.append("    tables: ").append(toIndentedString(tables)).append("\n");
        sb.append("    expiresIn: ").append(toIndentedString(expiresIn)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        return o == null ? "null" : o.toString().replace("\n", "\n    ");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields =
                new HashSet<String>(
                        Arrays.asList(
                                "url",
                                "gcs_generation",
                                "schema_version",
                                "store_id",
                                "store_name",
                                "tables",
                                "expires_in"));

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields =
                new HashSet<String>(
                        Arrays.asList(
                                "url",
                                "gcs_generation",
                                "schema_version",
                                "store_id",
                                "store_name",
                                "tables",
                                "expires_in"));
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to DataStoreDownloadInfo
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!DataStoreDownloadInfo.openapiRequiredFields
                    .isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(
                        String.format(
                                java.util.Locale.ROOT,
                                "The required field(s) %s in DataStoreDownloadInfo is not found in the empty JSON string",
                                DataStoreDownloadInfo.openapiRequiredFields.toString()));
            }
        }

        // check to make sure all required properties/fields are present in the JSON string
        for (String requiredField : DataStoreDownloadInfo.openapiRequiredFields) {
            if (jsonElement.getAsJsonObject().get(requiredField) == null) {
                throw new IllegalArgumentException(
                        String.format(
                                java.util.Locale.ROOT,
                                "The required field `%s` is not found in the JSON string: %s",
                                requiredField,
                                jsonElement.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if (!jsonObj.get("url").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `url` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("url").toString()));
        }
        if (!jsonObj.get("schema_version").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `schema_version` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("schema_version").toString()));
        }
        if (!jsonObj.get("store_id").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `store_id` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("store_id").toString()));
        }
        if (!jsonObj.get("store_name").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `store_name` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("store_name").toString()));
        }
        // ensure the required json array is present
        if (jsonObj.get("tables") == null) {
            throw new IllegalArgumentException(
                    "Expected the field `linkedContent` to be an array in the JSON string but got `null`");
        } else if (!jsonObj.get("tables").isJsonArray()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `tables` to be an array in the JSON string but got `%s`",
                            jsonObj.get("tables").toString()));
        }
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!DataStoreDownloadInfo.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'DataStoreDownloadInfo' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<DataStoreDownloadInfo> thisAdapter =
                    gson.getDelegateAdapter(this, TypeToken.get(DataStoreDownloadInfo.class));

            return (TypeAdapter<T>)
                    new TypeAdapter<DataStoreDownloadInfo>() {
                        @Override
                        public void write(JsonWriter out, DataStoreDownloadInfo value)
                                throws IOException {
                            JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                            elementAdapter.write(out, obj);
                        }

                        @Override
                        public DataStoreDownloadInfo read(JsonReader in) throws IOException {
                            JsonElement jsonElement = elementAdapter.read(in);
                            validateJsonElement(jsonElement);
                            return thisAdapter.fromJsonTree(jsonElement);
                        }
                    }.nullSafe();
        }
    }

    /**
     * Create an instance of DataStoreDownloadInfo given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of DataStoreDownloadInfo
     * @throws IOException if the JSON string is invalid with respect to DataStoreDownloadInfo
     */
    public static DataStoreDownloadInfo fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, DataStoreDownloadInfo.class);
    }

    /**
     * Convert an instance of DataStoreDownloadInfo to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
