/*
 * Vertesia API
 * The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.
 *
 * The version of the OpenAPI document: 1.4.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.vertesia.model;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.vertesia.JSON;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;

/**
 * A point-in-time version of a data store.
 */
@jakarta.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.22.0")
public class DataStoreVersion {
    public static final String SERIALIZED_NAME_ID = "id";

    @SerializedName(SERIALIZED_NAME_ID)
    @jakarta.annotation.Nonnull
    private String id;

    public static final String SERIALIZED_NAME_STORE_ID = "store_id";

    @SerializedName(SERIALIZED_NAME_STORE_ID)
    @jakarta.annotation.Nonnull
    private String storeId;

    public static final String SERIALIZED_NAME_MESSAGE = "message";

    @SerializedName(SERIALIZED_NAME_MESSAGE)
    @jakarta.annotation.Nonnull
    private String message;

    public static final String SERIALIZED_NAME_SCHEMA_VERSION = "schema_version";

    @SerializedName(SERIALIZED_NAME_SCHEMA_VERSION)
    @jakarta.annotation.Nonnull
    private String schemaVersion;

    public static final String SERIALIZED_NAME_TABLES = "tables";

    @SerializedName(SERIALIZED_NAME_TABLES)
    @jakarta.annotation.Nonnull
    private Map<String, DataStoreVersionTableState> tables;

    public static final String SERIALIZED_NAME_CREATED_AT = "created_at";

    @SerializedName(SERIALIZED_NAME_CREATED_AT)
    @jakarta.annotation.Nonnull
    private String createdAt;

    public static final String SERIALIZED_NAME_CREATED_BY = "created_by";

    @SerializedName(SERIALIZED_NAME_CREATED_BY)
    @jakarta.annotation.Nullable private String createdBy;

    public static final String SERIALIZED_NAME_GCS_GENERATION = "gcs_generation";

    @SerializedName(SERIALIZED_NAME_GCS_GENERATION)
    @jakarta.annotation.Nonnull
    private BigDecimal gcsGeneration;

    public static final String SERIALIZED_NAME_GCS_PATH_ID = "gcs_path_id";

    @SerializedName(SERIALIZED_NAME_GCS_PATH_ID)
    @jakarta.annotation.Nullable private String gcsPathId;

    public static final String SERIALIZED_NAME_IS_SNAPSHOT = "is_snapshot";

    @SerializedName(SERIALIZED_NAME_IS_SNAPSHOT)
    @jakarta.annotation.Nullable private Boolean isSnapshot;

    public static final String SERIALIZED_NAME_SNAPSHOT_NAME = "snapshot_name";

    @SerializedName(SERIALIZED_NAME_SNAPSHOT_NAME)
    @jakarta.annotation.Nullable private String snapshotName;

    public DataStoreVersion() {}

    public DataStoreVersion id(@jakarta.annotation.Nonnull String id) {
        this.id = id;
        return this;
    }

    /**
     * Version ID
     * @return id
     */
    @jakarta.annotation.Nonnull
    public String getId() {
        return id;
    }

    public void setId(@jakarta.annotation.Nonnull String id) {
        this.id = id;
    }

    public DataStoreVersion storeId(@jakarta.annotation.Nonnull String storeId) {
        this.storeId = storeId;
        return this;
    }

    /**
     * Parent store ID
     * @return storeId
     */
    @jakarta.annotation.Nonnull
    public String getStoreId() {
        return storeId;
    }

    public void setStoreId(@jakarta.annotation.Nonnull String storeId) {
        this.storeId = storeId;
    }

    public DataStoreVersion message(@jakarta.annotation.Nonnull String message) {
        this.message = message;
        return this;
    }

    /**
     * Commit message
     * @return message
     */
    @jakarta.annotation.Nonnull
    public String getMessage() {
        return message;
    }

    public void setMessage(@jakarta.annotation.Nonnull String message) {
        this.message = message;
    }

    public DataStoreVersion schemaVersion(@jakarta.annotation.Nonnull String schemaVersion) {
        this.schemaVersion = schemaVersion;
        return this;
    }

    /**
     * Schema version at this point
     * @return schemaVersion
     */
    @jakarta.annotation.Nonnull
    public String getSchemaVersion() {
        return schemaVersion;
    }

    public void setSchemaVersion(@jakarta.annotation.Nonnull String schemaVersion) {
        this.schemaVersion = schemaVersion;
    }

    public DataStoreVersion tables(
            @jakarta.annotation.Nonnull Map<String, DataStoreVersionTableState> tables) {
        this.tables = tables;
        return this;
    }

    public DataStoreVersion putTablesItem(String key, DataStoreVersionTableState tablesItem) {
        if (this.tables == null) {
            this.tables = new HashMap<>();
        }
        this.tables.put(key, tablesItem);
        return this;
    }

    /**
     * Table states at this version
     * @return tables
     */
    @jakarta.annotation.Nonnull
    public Map<String, DataStoreVersionTableState> getTables() {
        return tables;
    }

    public void setTables(
            @jakarta.annotation.Nonnull Map<String, DataStoreVersionTableState> tables) {
        this.tables = tables;
    }

    public DataStoreVersion createdAt(@jakarta.annotation.Nonnull String createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    /**
     * Creation timestamp
     * @return createdAt
     */
    @jakarta.annotation.Nonnull
    public String getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(@jakarta.annotation.Nonnull String createdAt) {
        this.createdAt = createdAt;
    }

    public DataStoreVersion createdBy(@jakarta.annotation.Nullable String createdBy) {
        this.createdBy = createdBy;
        return this;
    }

    /**
     * User/agent who created
     * @return createdBy
     */
    @jakarta.annotation.Nullable public String getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(@jakarta.annotation.Nullable String createdBy) {
        this.createdBy = createdBy;
    }

    public DataStoreVersion gcsGeneration(@jakarta.annotation.Nonnull BigDecimal gcsGeneration) {
        this.gcsGeneration = gcsGeneration;
        return this;
    }

    /**
     * GCS object generation number
     * @return gcsGeneration
     */
    @jakarta.annotation.Nonnull
    public BigDecimal getGcsGeneration() {
        return gcsGeneration;
    }

    public void setGcsGeneration(@jakarta.annotation.Nonnull BigDecimal gcsGeneration) {
        this.gcsGeneration = gcsGeneration;
    }

    public DataStoreVersion gcsPathId(@jakarta.annotation.Nullable String gcsPathId) {
        this.gcsPathId = gcsPathId;
        return this;
    }

    /**
     * Timestamp-based ID used for GCS path (internal)
     * @return gcsPathId
     */
    @jakarta.annotation.Nullable public String getGcsPathId() {
        return gcsPathId;
    }

    public void setGcsPathId(@jakarta.annotation.Nullable String gcsPathId) {
        this.gcsPathId = gcsPathId;
    }

    public DataStoreVersion isSnapshot(@jakarta.annotation.Nullable Boolean isSnapshot) {
        this.isSnapshot = isSnapshot;
        return this;
    }

    /**
     * Whether this is a named snapshot
     * @return isSnapshot
     */
    @jakarta.annotation.Nullable public Boolean getIsSnapshot() {
        return isSnapshot;
    }

    public void setIsSnapshot(@jakarta.annotation.Nullable Boolean isSnapshot) {
        this.isSnapshot = isSnapshot;
    }

    public DataStoreVersion snapshotName(@jakarta.annotation.Nullable String snapshotName) {
        this.snapshotName = snapshotName;
        return this;
    }

    /**
     * Snapshot name (if is_snapshot)
     * @return snapshotName
     */
    @jakarta.annotation.Nullable public String getSnapshotName() {
        return snapshotName;
    }

    public void setSnapshotName(@jakarta.annotation.Nullable String snapshotName) {
        this.snapshotName = snapshotName;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DataStoreVersion dataStoreVersion = (DataStoreVersion) o;
        return Objects.equals(this.id, dataStoreVersion.id)
                && Objects.equals(this.storeId, dataStoreVersion.storeId)
                && Objects.equals(this.message, dataStoreVersion.message)
                && Objects.equals(this.schemaVersion, dataStoreVersion.schemaVersion)
                && Objects.equals(this.tables, dataStoreVersion.tables)
                && Objects.equals(this.createdAt, dataStoreVersion.createdAt)
                && Objects.equals(this.createdBy, dataStoreVersion.createdBy)
                && Objects.equals(this.gcsGeneration, dataStoreVersion.gcsGeneration)
                && Objects.equals(this.gcsPathId, dataStoreVersion.gcsPathId)
                && Objects.equals(this.isSnapshot, dataStoreVersion.isSnapshot)
                && Objects.equals(this.snapshotName, dataStoreVersion.snapshotName);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                id,
                storeId,
                message,
                schemaVersion,
                tables,
                createdAt,
                createdBy,
                gcsGeneration,
                gcsPathId,
                isSnapshot,
                snapshotName);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class DataStoreVersion {\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    storeId: ").append(toIndentedString(storeId)).append("\n");
        sb.append("    message: ").append(toIndentedString(message)).append("\n");
        sb.append("    schemaVersion: ").append(toIndentedString(schemaVersion)).append("\n");
        sb.append("    tables: ").append(toIndentedString(tables)).append("\n");
        sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
        sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
        sb.append("    gcsGeneration: ").append(toIndentedString(gcsGeneration)).append("\n");
        sb.append("    gcsPathId: ").append(toIndentedString(gcsPathId)).append("\n");
        sb.append("    isSnapshot: ").append(toIndentedString(isSnapshot)).append("\n");
        sb.append("    snapshotName: ").append(toIndentedString(snapshotName)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        return o == null ? "null" : o.toString().replace("\n", "\n    ");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields =
                new HashSet<String>(
                        Arrays.asList(
                                "id",
                                "store_id",
                                "message",
                                "schema_version",
                                "tables",
                                "created_at",
                                "created_by",
                                "gcs_generation",
                                "gcs_path_id",
                                "is_snapshot",
                                "snapshot_name"));

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields =
                new HashSet<String>(
                        Arrays.asList(
                                "id",
                                "store_id",
                                "message",
                                "schema_version",
                                "tables",
                                "created_at",
                                "gcs_generation"));
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to DataStoreVersion
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!DataStoreVersion.openapiRequiredFields
                    .isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(
                        String.format(
                                java.util.Locale.ROOT,
                                "The required field(s) %s in DataStoreVersion is not found in the empty JSON string",
                                DataStoreVersion.openapiRequiredFields.toString()));
            }
        }

        // check to make sure all required properties/fields are present in the JSON string
        for (String requiredField : DataStoreVersion.openapiRequiredFields) {
            if (jsonElement.getAsJsonObject().get(requiredField) == null) {
                throw new IllegalArgumentException(
                        String.format(
                                java.util.Locale.ROOT,
                                "The required field `%s` is not found in the JSON string: %s",
                                requiredField,
                                jsonElement.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if (!jsonObj.get("id").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `id` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("id").toString()));
        }
        if (!jsonObj.get("store_id").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `store_id` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("store_id").toString()));
        }
        if (!jsonObj.get("message").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `message` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("message").toString()));
        }
        if (!jsonObj.get("schema_version").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `schema_version` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("schema_version").toString()));
        }
        if (!jsonObj.get("created_at").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `created_at` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("created_at").toString()));
        }
        if ((jsonObj.get("created_by") != null && !jsonObj.get("created_by").isJsonNull())
                && !jsonObj.get("created_by").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `created_by` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("created_by").toString()));
        }
        if ((jsonObj.get("gcs_path_id") != null && !jsonObj.get("gcs_path_id").isJsonNull())
                && !jsonObj.get("gcs_path_id").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `gcs_path_id` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("gcs_path_id").toString()));
        }
        if ((jsonObj.get("snapshot_name") != null && !jsonObj.get("snapshot_name").isJsonNull())
                && !jsonObj.get("snapshot_name").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `snapshot_name` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("snapshot_name").toString()));
        }
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!DataStoreVersion.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'DataStoreVersion' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<DataStoreVersion> thisAdapter =
                    gson.getDelegateAdapter(this, TypeToken.get(DataStoreVersion.class));

            return (TypeAdapter<T>)
                    new TypeAdapter<DataStoreVersion>() {
                        @Override
                        public void write(JsonWriter out, DataStoreVersion value)
                                throws IOException {
                            JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                            elementAdapter.write(out, obj);
                        }

                        @Override
                        public DataStoreVersion read(JsonReader in) throws IOException {
                            JsonElement jsonElement = elementAdapter.read(in);
                            validateJsonElement(jsonElement);
                            return thisAdapter.fromJsonTree(jsonElement);
                        }
                    }.nullSafe();
        }
    }

    /**
     * Create an instance of DataStoreVersion given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of DataStoreVersion
     * @throws IOException if the JSON string is invalid with respect to DataStoreVersion
     */
    public static DataStoreVersion fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, DataStoreVersion.class);
    }

    /**
     * Convert an instance of DataStoreVersion to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
