/*
 * Vertesia API
 * The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` SDK for typed access from Node.js applications.
 *
 * The version of the OpenAPI document: 1.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.vertesia.model;

import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.vertesia.JSON;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashSet;
import java.util.List;
import java.util.Objects;

/**
 * GeneratedInteractionDefinition
 */
@javax.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.22.0")
public class GeneratedInteractionDefinition {
    public static final String SERIALIZED_NAME_NAME = "name";

    @SerializedName(SERIALIZED_NAME_NAME)
    @javax.annotation.Nonnull
    private String name;

    public static final String SERIALIZED_NAME_DESCRIPTION = "description";

    @SerializedName(SERIALIZED_NAME_DESCRIPTION)
    @javax.annotation.Nonnull
    private String description;

    public static final String SERIALIZED_NAME_TEMPERATURE = "temperature";

    @SerializedName(SERIALIZED_NAME_TEMPERATURE)
    @javax.annotation.Nonnull
    private BigDecimal temperature;

    public static final String SERIALIZED_NAME_PROMPTS = "prompts";

    @SerializedName(SERIALIZED_NAME_PROMPTS)
    @javax.annotation.Nonnull
    private List<GeneratedInteractionPromptSegment> prompts = new ArrayList<>();

    public static final String SERIALIZED_NAME_MAX_TOKENS = "max_tokens";

    @SerializedName(SERIALIZED_NAME_MAX_TOKENS)
    @javax.annotation.Nullable private BigDecimal maxTokens;

    public static final String SERIALIZED_NAME_RESULT_SCHEMA = "result_schema";

    @SerializedName(SERIALIZED_NAME_RESULT_SCHEMA)
    @javax.annotation.Nonnull
    private JSONSchema resultSchema;

    /**
     * Gets or Sets tags
     */
    @JsonAdapter(TagsEnum.Adapter.class)
    public enum TagsEnum {
        GENERATED("generated"),

        AGENT("agent"),

        UNKNOWN_DEFAULT_OPEN_API("unknown_default_open_api");

        private String value;

        TagsEnum(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        public static TagsEnum fromValue(String value) {
            for (TagsEnum b : TagsEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            return UNKNOWN_DEFAULT_OPEN_API;
        }

        public static class Adapter extends TypeAdapter<TagsEnum> {
            @Override
            public void write(final JsonWriter jsonWriter, final TagsEnum enumeration)
                    throws IOException {
                jsonWriter.value(enumeration.getValue());
            }

            @Override
            public TagsEnum read(final JsonReader jsonReader) throws IOException {
                String value = jsonReader.nextString();
                return TagsEnum.fromValue(value);
            }
        }

        public static void validateJsonElement(JsonElement jsonElement) throws IOException {
            String value = jsonElement.getAsString();
            TagsEnum.fromValue(value);
        }
    }

    public static final String SERIALIZED_NAME_TAGS = "tags";

    @SerializedName(SERIALIZED_NAME_TAGS)
    @javax.annotation.Nonnull
    private List<TagsEnum> tags = new ArrayList<>();

    public GeneratedInteractionDefinition() {}

    public GeneratedInteractionDefinition name(@javax.annotation.Nonnull String name) {
        this.name = name;
        return this;
    }

    /**
     * Get name
     * @return name
     */
    @javax.annotation.Nonnull
    public String getName() {
        return name;
    }

    public void setName(@javax.annotation.Nonnull String name) {
        this.name = name;
    }

    public GeneratedInteractionDefinition description(
            @javax.annotation.Nonnull String description) {
        this.description = description;
        return this;
    }

    /**
     * Get description
     * @return description
     */
    @javax.annotation.Nonnull
    public String getDescription() {
        return description;
    }

    public void setDescription(@javax.annotation.Nonnull String description) {
        this.description = description;
    }

    public GeneratedInteractionDefinition temperature(
            @javax.annotation.Nonnull BigDecimal temperature) {
        this.temperature = temperature;
        return this;
    }

    /**
     * Get temperature
     * @return temperature
     */
    @javax.annotation.Nonnull
    public BigDecimal getTemperature() {
        return temperature;
    }

    public void setTemperature(@javax.annotation.Nonnull BigDecimal temperature) {
        this.temperature = temperature;
    }

    public GeneratedInteractionDefinition prompts(
            @javax.annotation.Nonnull List<GeneratedInteractionPromptSegment> prompts) {
        this.prompts = prompts;
        return this;
    }

    public GeneratedInteractionDefinition addPromptsItem(
            GeneratedInteractionPromptSegment promptsItem) {
        if (this.prompts == null) {
            this.prompts = new ArrayList<>();
        }
        this.prompts.add(promptsItem);
        return this;
    }

    /**
     * Get prompts
     * @return prompts
     */
    @javax.annotation.Nonnull
    public List<GeneratedInteractionPromptSegment> getPrompts() {
        return prompts;
    }

    public void setPrompts(
            @javax.annotation.Nonnull List<GeneratedInteractionPromptSegment> prompts) {
        this.prompts = prompts;
    }

    public GeneratedInteractionDefinition maxTokens(
            @javax.annotation.Nullable BigDecimal maxTokens) {
        this.maxTokens = maxTokens;
        return this;
    }

    /**
     * Get maxTokens
     * @return maxTokens
     */
    @javax.annotation.Nullable public BigDecimal getMaxTokens() {
        return maxTokens;
    }

    public void setMaxTokens(@javax.annotation.Nullable BigDecimal maxTokens) {
        this.maxTokens = maxTokens;
    }

    public GeneratedInteractionDefinition resultSchema(
            @javax.annotation.Nonnull JSONSchema resultSchema) {
        this.resultSchema = resultSchema;
        return this;
    }

    /**
     * Get resultSchema
     * @return resultSchema
     */
    @javax.annotation.Nonnull
    public JSONSchema getResultSchema() {
        return resultSchema;
    }

    public void setResultSchema(@javax.annotation.Nonnull JSONSchema resultSchema) {
        this.resultSchema = resultSchema;
    }

    public GeneratedInteractionDefinition tags(@javax.annotation.Nonnull List<TagsEnum> tags) {
        this.tags = tags;
        return this;
    }

    public GeneratedInteractionDefinition addTagsItem(TagsEnum tagsItem) {
        if (this.tags == null) {
            this.tags = new ArrayList<>();
        }
        this.tags.add(tagsItem);
        return this;
    }

    /**
     * Get tags
     * @return tags
     */
    @javax.annotation.Nonnull
    public List<TagsEnum> getTags() {
        return tags;
    }

    public void setTags(@javax.annotation.Nonnull List<TagsEnum> tags) {
        this.tags = tags;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GeneratedInteractionDefinition generatedInteractionDefinition =
                (GeneratedInteractionDefinition) o;
        return Objects.equals(this.name, generatedInteractionDefinition.name)
                && Objects.equals(this.description, generatedInteractionDefinition.description)
                && Objects.equals(this.temperature, generatedInteractionDefinition.temperature)
                && Objects.equals(this.prompts, generatedInteractionDefinition.prompts)
                && Objects.equals(this.maxTokens, generatedInteractionDefinition.maxTokens)
                && Objects.equals(this.resultSchema, generatedInteractionDefinition.resultSchema)
                && Objects.equals(this.tags, generatedInteractionDefinition.tags);
    }

    @Override
    public int hashCode() {
        return Objects.hash(name, description, temperature, prompts, maxTokens, resultSchema, tags);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class GeneratedInteractionDefinition {\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    description: ").append(toIndentedString(description)).append("\n");
        sb.append("    temperature: ").append(toIndentedString(temperature)).append("\n");
        sb.append("    prompts: ").append(toIndentedString(prompts)).append("\n");
        sb.append("    maxTokens: ").append(toIndentedString(maxTokens)).append("\n");
        sb.append("    resultSchema: ").append(toIndentedString(resultSchema)).append("\n");
        sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        return o == null ? "null" : o.toString().replace("\n", "\n    ");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields =
                new HashSet<String>(
                        Arrays.asList(
                                "name",
                                "description",
                                "temperature",
                                "prompts",
                                "max_tokens",
                                "result_schema",
                                "tags"));

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields =
                new HashSet<String>(
                        Arrays.asList(
                                "name",
                                "description",
                                "temperature",
                                "prompts",
                                "result_schema",
                                "tags"));
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to GeneratedInteractionDefinition
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!GeneratedInteractionDefinition.openapiRequiredFields
                    .isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(
                        String.format(
                                java.util.Locale.ROOT,
                                "The required field(s) %s in GeneratedInteractionDefinition is not found in the empty JSON string",
                                GeneratedInteractionDefinition.openapiRequiredFields.toString()));
            }
        }

        // check to make sure all required properties/fields are present in the JSON string
        for (String requiredField : GeneratedInteractionDefinition.openapiRequiredFields) {
            if (jsonElement.getAsJsonObject().get(requiredField) == null) {
                throw new IllegalArgumentException(
                        String.format(
                                java.util.Locale.ROOT,
                                "The required field `%s` is not found in the JSON string: %s",
                                requiredField,
                                jsonElement.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if (!jsonObj.get("name").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `name` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("name").toString()));
        }
        if (!jsonObj.get("description").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `description` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("description").toString()));
        }
        if (jsonObj.get("prompts") != null) {
            if (!jsonObj.get("prompts").isJsonArray()) {
                throw new IllegalArgumentException(
                        String.format(
                                java.util.Locale.ROOT,
                                "Expected the field `prompts` to be an array in the JSON string but got `%s`",
                                jsonObj.get("prompts").toString()));
            }
            JsonArray jsonArrayprompts = jsonObj.getAsJsonArray("prompts");
            // validate the required field `prompts` (array)
            for (int i = 0; i < jsonArrayprompts.size(); i++) {
                GeneratedInteractionPromptSegment.validateJsonElement(jsonArrayprompts.get(i));
            }
        }
        // validate the required field `result_schema`
        JSONSchema.validateJsonElement(jsonObj.get("result_schema"));
        // ensure the required json array is present
        if (jsonObj.get("tags") == null) {
            throw new IllegalArgumentException(
                    "Expected the field `linkedContent` to be an array in the JSON string but got `null`");
        } else if (!jsonObj.get("tags").isJsonArray()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `tags` to be an array in the JSON string but got `%s`",
                            jsonObj.get("tags").toString()));
        }
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!GeneratedInteractionDefinition.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'GeneratedInteractionDefinition' and its
                // subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<GeneratedInteractionDefinition> thisAdapter =
                    gson.getDelegateAdapter(
                            this, TypeToken.get(GeneratedInteractionDefinition.class));

            return (TypeAdapter<T>)
                    new TypeAdapter<GeneratedInteractionDefinition>() {
                        @Override
                        public void write(JsonWriter out, GeneratedInteractionDefinition value)
                                throws IOException {
                            JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                            elementAdapter.write(out, obj);
                        }

                        @Override
                        public GeneratedInteractionDefinition read(JsonReader in)
                                throws IOException {
                            JsonElement jsonElement = elementAdapter.read(in);
                            validateJsonElement(jsonElement);
                            return thisAdapter.fromJsonTree(jsonElement);
                        }
                    }.nullSafe();
        }
    }

    /**
     * Create an instance of GeneratedInteractionDefinition given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of GeneratedInteractionDefinition
     * @throws IOException if the JSON string is invalid with respect to GeneratedInteractionDefinition
     */
    public static GeneratedInteractionDefinition fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, GeneratedInteractionDefinition.class);
    }

    /**
     * Convert an instance of GeneratedInteractionDefinition to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
