/*
 * Vertesia API
 * The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.
 *
 * The version of the OpenAPI document: 1.4.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.vertesia.model;

import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.vertesia.JSON;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashSet;
import java.util.List;
import java.util.Objects;

/**
 * HumanTaskDefinition
 */
@jakarta.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.22.0")
public class HumanTaskDefinition {
    public static final String SERIALIZED_NAME_TITLE = "title";

    @SerializedName(SERIALIZED_NAME_TITLE)
    @jakarta.annotation.Nonnull
    private String title;

    public static final String SERIALIZED_NAME_DESCRIPTION = "description";

    @SerializedName(SERIALIZED_NAME_DESCRIPTION)
    @jakarta.annotation.Nullable private String description;

    public static final String SERIALIZED_NAME_ASSIGNEE = "assignee";

    @SerializedName(SERIALIZED_NAME_ASSIGNEE)
    @jakarta.annotation.Nullable private String assignee;

    public static final String SERIALIZED_NAME_FIELDS = "fields";

    @SerializedName(SERIALIZED_NAME_FIELDS)
    @jakarta.annotation.Nonnull
    private List<TaskField> fields = new ArrayList<>();

    public HumanTaskDefinition() {}

    public HumanTaskDefinition title(@jakarta.annotation.Nonnull String title) {
        this.title = title;
        return this;
    }

    /**
     * Get title
     * @return title
     */
    @jakarta.annotation.Nonnull
    public String getTitle() {
        return title;
    }

    public void setTitle(@jakarta.annotation.Nonnull String title) {
        this.title = title;
    }

    public HumanTaskDefinition description(@jakarta.annotation.Nullable String description) {
        this.description = description;
        return this;
    }

    /**
     * Get description
     * @return description
     */
    @jakarta.annotation.Nullable public String getDescription() {
        return description;
    }

    public void setDescription(@jakarta.annotation.Nullable String description) {
        this.description = description;
    }

    public HumanTaskDefinition assignee(@jakarta.annotation.Nullable String assignee) {
        this.assignee = assignee;
        return this;
    }

    /**
     * Who owns the task. Either a group reference (&#x60;group:&lt;name&gt;&#x60;) or a concrete user id. Leave unset to make the task available to anyone who can see the inbox. &#x60;role:&lt;name&gt;&#x60; is not supported — use &#x60;group:&lt;name&gt;&#x60; instead.
     * @return assignee
     */
    @jakarta.annotation.Nullable public String getAssignee() {
        return assignee;
    }

    public void setAssignee(@jakarta.annotation.Nullable String assignee) {
        this.assignee = assignee;
    }

    public HumanTaskDefinition fields(@jakarta.annotation.Nonnull List<TaskField> fields) {
        this.fields = fields;
        return this;
    }

    public HumanTaskDefinition addFieldsItem(TaskField fieldsItem) {
        if (this.fields == null) {
            this.fields = new ArrayList<>();
        }
        this.fields.add(fieldsItem);
        return this;
    }

    /**
     * Get fields
     * @return fields
     */
    @jakarta.annotation.Nonnull
    public List<TaskField> getFields() {
        return fields;
    }

    public void setFields(@jakarta.annotation.Nonnull List<TaskField> fields) {
        this.fields = fields;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        HumanTaskDefinition humanTaskDefinition = (HumanTaskDefinition) o;
        return Objects.equals(this.title, humanTaskDefinition.title)
                && Objects.equals(this.description, humanTaskDefinition.description)
                && Objects.equals(this.assignee, humanTaskDefinition.assignee)
                && Objects.equals(this.fields, humanTaskDefinition.fields);
    }

    @Override
    public int hashCode() {
        return Objects.hash(title, description, assignee, fields);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class HumanTaskDefinition {\n");
        sb.append("    title: ").append(toIndentedString(title)).append("\n");
        sb.append("    description: ").append(toIndentedString(description)).append("\n");
        sb.append("    assignee: ").append(toIndentedString(assignee)).append("\n");
        sb.append("    fields: ").append(toIndentedString(fields)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        return o == null ? "null" : o.toString().replace("\n", "\n    ");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields =
                new HashSet<String>(Arrays.asList("title", "description", "assignee", "fields"));

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>(Arrays.asList("title", "fields"));
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to HumanTaskDefinition
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!HumanTaskDefinition.openapiRequiredFields
                    .isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(
                        String.format(
                                java.util.Locale.ROOT,
                                "The required field(s) %s in HumanTaskDefinition is not found in the empty JSON string",
                                HumanTaskDefinition.openapiRequiredFields.toString()));
            }
        }

        // check to make sure all required properties/fields are present in the JSON string
        for (String requiredField : HumanTaskDefinition.openapiRequiredFields) {
            if (jsonElement.getAsJsonObject().get(requiredField) == null) {
                throw new IllegalArgumentException(
                        String.format(
                                java.util.Locale.ROOT,
                                "The required field `%s` is not found in the JSON string: %s",
                                requiredField,
                                jsonElement.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if (!jsonObj.get("title").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `title` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("title").toString()));
        }
        if ((jsonObj.get("description") != null && !jsonObj.get("description").isJsonNull())
                && !jsonObj.get("description").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `description` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("description").toString()));
        }
        if ((jsonObj.get("assignee") != null && !jsonObj.get("assignee").isJsonNull())
                && !jsonObj.get("assignee").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `assignee` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("assignee").toString()));
        }
        if (jsonObj.get("fields") != null) {
            if (!jsonObj.get("fields").isJsonArray()) {
                throw new IllegalArgumentException(
                        String.format(
                                java.util.Locale.ROOT,
                                "Expected the field `fields` to be an array in the JSON string but got `%s`",
                                jsonObj.get("fields").toString()));
            }
            JsonArray jsonArrayfields = jsonObj.getAsJsonArray("fields");
            // validate the required field `fields` (array)
            for (int i = 0; i < jsonArrayfields.size(); i++) {
                TaskField.validateJsonElement(jsonArrayfields.get(i));
            }
        }
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!HumanTaskDefinition.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'HumanTaskDefinition' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<HumanTaskDefinition> thisAdapter =
                    gson.getDelegateAdapter(this, TypeToken.get(HumanTaskDefinition.class));

            return (TypeAdapter<T>)
                    new TypeAdapter<HumanTaskDefinition>() {
                        @Override
                        public void write(JsonWriter out, HumanTaskDefinition value)
                                throws IOException {
                            JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                            elementAdapter.write(out, obj);
                        }

                        @Override
                        public HumanTaskDefinition read(JsonReader in) throws IOException {
                            JsonElement jsonElement = elementAdapter.read(in);
                            validateJsonElement(jsonElement);
                            return thisAdapter.fromJsonTree(jsonElement);
                        }
                    }.nullSafe();
        }
    }

    /**
     * Create an instance of HumanTaskDefinition given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of HumanTaskDefinition
     * @throws IOException if the JSON string is invalid with respect to HumanTaskDefinition
     */
    public static HumanTaskDefinition fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, HumanTaskDefinition.class);
    }

    /**
     * Convert an instance of HumanTaskDefinition to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
