/*
 * Vertesia API
 * The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` SDK for typed access from Node.js applications.
 *
 * The version of the OpenAPI document: 1.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.vertesia.model;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.vertesia.JSON;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Objects;

/**
 * Location
 */
@jakarta.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.22.0")
public class Location {
    public static final String SERIALIZED_NAME_LATITUDE = "latitude";

    @SerializedName(SERIALIZED_NAME_LATITUDE)
    @jakarta.annotation.Nonnull
    private BigDecimal latitude;

    public static final String SERIALIZED_NAME_LONGITUDE = "longitude";

    @SerializedName(SERIALIZED_NAME_LONGITUDE)
    @jakarta.annotation.Nonnull
    private BigDecimal longitude;

    public Location() {}

    public Location latitude(@jakarta.annotation.Nonnull BigDecimal latitude) {
        this.latitude = latitude;
        return this;
    }

    /**
     * Get latitude
     * @return latitude
     */
    @jakarta.annotation.Nonnull
    public BigDecimal getLatitude() {
        return latitude;
    }

    public void setLatitude(@jakarta.annotation.Nonnull BigDecimal latitude) {
        this.latitude = latitude;
    }

    public Location longitude(@jakarta.annotation.Nonnull BigDecimal longitude) {
        this.longitude = longitude;
        return this;
    }

    /**
     * Get longitude
     * @return longitude
     */
    @jakarta.annotation.Nonnull
    public BigDecimal getLongitude() {
        return longitude;
    }

    public void setLongitude(@jakarta.annotation.Nonnull BigDecimal longitude) {
        this.longitude = longitude;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Location location = (Location) o;
        return Objects.equals(this.latitude, location.latitude)
                && Objects.equals(this.longitude, location.longitude);
    }

    @Override
    public int hashCode() {
        return Objects.hash(latitude, longitude);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Location {\n");
        sb.append("    latitude: ").append(toIndentedString(latitude)).append("\n");
        sb.append("    longitude: ").append(toIndentedString(longitude)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        return o == null ? "null" : o.toString().replace("\n", "\n    ");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>(Arrays.asList("latitude", "longitude"));

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>(Arrays.asList("latitude", "longitude"));
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to Location
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!Location.openapiRequiredFields
                    .isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(
                        String.format(
                                java.util.Locale.ROOT,
                                "The required field(s) %s in Location is not found in the empty JSON string",
                                Location.openapiRequiredFields.toString()));
            }
        }

        // check to make sure all required properties/fields are present in the JSON string
        for (String requiredField : Location.openapiRequiredFields) {
            if (jsonElement.getAsJsonObject().get(requiredField) == null) {
                throw new IllegalArgumentException(
                        String.format(
                                java.util.Locale.ROOT,
                                "The required field `%s` is not found in the JSON string: %s",
                                requiredField,
                                jsonElement.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!Location.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'Location' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<Location> thisAdapter =
                    gson.getDelegateAdapter(this, TypeToken.get(Location.class));

            return (TypeAdapter<T>)
                    new TypeAdapter<Location>() {
                        @Override
                        public void write(JsonWriter out, Location value) throws IOException {
                            JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                            elementAdapter.write(out, obj);
                        }

                        @Override
                        public Location read(JsonReader in) throws IOException {
                            JsonElement jsonElement = elementAdapter.read(in);
                            validateJsonElement(jsonElement);
                            return thisAdapter.fromJsonTree(jsonElement);
                        }
                    }.nullSafe();
        }
    }

    /**
     * Create an instance of Location given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of Location
     * @throws IOException if the JSON string is invalid with respect to Location
     */
    public static Location fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, Location.class);
    }

    /**
     * Convert an instance of Location to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
