/*
 * Vertesia API
 * The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.
 *
 * The version of the OpenAPI document: 1.5.0-dev.20260725.083715Z
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.vertesia.model;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.vertesia.JSON;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;

@jakarta.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.22.0")
public class NodeDefinitionBranchesInner extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(NodeDefinitionBranchesInner.class.getName());

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!NodeDefinitionBranchesInner.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'NodeDefinitionBranchesInner' and its
                // subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<BranchDefinition> adapterBranchDefinition =
                    gson.getDelegateAdapter(this, TypeToken.get(BranchDefinition.class));
            final TypeAdapter<BranchNodeBranchDefinition> adapterBranchNodeBranchDefinition =
                    gson.getDelegateAdapter(this, TypeToken.get(BranchNodeBranchDefinition.class));

            return (TypeAdapter<T>)
                    new TypeAdapter<NodeDefinitionBranchesInner>() {
                        @Override
                        public void write(JsonWriter out, NodeDefinitionBranchesInner value)
                                throws IOException {
                            if (value == null || value.getActualInstance() == null) {
                                elementAdapter.write(out, null);
                                return;
                            }

                            // check if the actual instance is of the type `BranchDefinition`
                            if (value.getActualInstance() instanceof BranchDefinition) {
                                JsonElement element =
                                        adapterBranchDefinition.toJsonTree(
                                                (BranchDefinition) value.getActualInstance());
                                elementAdapter.write(out, element);
                                return;
                            }
                            // check if the actual instance is of the type
                            // `BranchNodeBranchDefinition`
                            if (value.getActualInstance() instanceof BranchNodeBranchDefinition) {
                                JsonElement element =
                                        adapterBranchNodeBranchDefinition.toJsonTree(
                                                (BranchNodeBranchDefinition)
                                                        value.getActualInstance());
                                elementAdapter.write(out, element);
                                return;
                            }
                            throw new IOException(
                                    "Failed to serialize as the type doesn't match oneOf schemas: BranchDefinition, BranchNodeBranchDefinition");
                        }

                        @Override
                        public NodeDefinitionBranchesInner read(JsonReader in) throws IOException {
                            Object deserialized = null;
                            JsonElement jsonElement = elementAdapter.read(in);

                            int match = 0;
                            ArrayList<String> errorMessages = new ArrayList<>();
                            TypeAdapter actualAdapter = elementAdapter;

                            // deserialize BranchDefinition
                            try {
                                // validate the JSON object to see if any exception is thrown
                                BranchDefinition.validateJsonElement(jsonElement);
                                actualAdapter = adapterBranchDefinition;
                                match++;
                                log.log(
                                        Level.FINER,
                                        "Input data matches schema 'BranchDefinition'");
                            } catch (Exception e) {
                                // deserialization failed, continue
                                errorMessages.add(
                                        String.format(
                                                java.util.Locale.ROOT,
                                                "Deserialization for BranchDefinition failed with `%s`.",
                                                e.getMessage()));
                                log.log(
                                        Level.FINER,
                                        "Input data does not match schema 'BranchDefinition'",
                                        e);
                            }
                            // deserialize BranchNodeBranchDefinition
                            try {
                                // validate the JSON object to see if any exception is thrown
                                BranchNodeBranchDefinition.validateJsonElement(jsonElement);
                                actualAdapter = adapterBranchNodeBranchDefinition;
                                match++;
                                log.log(
                                        Level.FINER,
                                        "Input data matches schema 'BranchNodeBranchDefinition'");
                            } catch (Exception e) {
                                // deserialization failed, continue
                                errorMessages.add(
                                        String.format(
                                                java.util.Locale.ROOT,
                                                "Deserialization for BranchNodeBranchDefinition failed with `%s`.",
                                                e.getMessage()));
                                log.log(
                                        Level.FINER,
                                        "Input data does not match schema 'BranchNodeBranchDefinition'",
                                        e);
                            }

                            if (match == 1) {
                                NodeDefinitionBranchesInner ret = new NodeDefinitionBranchesInner();
                                ret.setActualInstance(actualAdapter.fromJsonTree(jsonElement));
                                return ret;
                            }

                            throw new IOException(
                                    String.format(
                                            java.util.Locale.ROOT,
                                            "Failed deserialization for NodeDefinitionBranchesInner: %d classes match result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s",
                                            match,
                                            errorMessages,
                                            jsonElement.toString()));
                        }
                    }.nullSafe();
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<String, Class<?>>();

    public NodeDefinitionBranchesInner() {
        super("oneOf", Boolean.FALSE);
    }

    public NodeDefinitionBranchesInner(Object o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("BranchDefinition", BranchDefinition.class);
        schemas.put("BranchNodeBranchDefinition", BranchNodeBranchDefinition.class);
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return NodeDefinitionBranchesInner.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * BranchDefinition, BranchNodeBranchDefinition
     *
     * It could be an instance of the 'oneOf' schemas.
     */
    @Override
    public void setActualInstance(Object instance) {
        if (instance instanceof BranchDefinition) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof BranchNodeBranchDefinition) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException(
                "Invalid instance type. Must be BranchDefinition, BranchNodeBranchDefinition");
    }

    /**
     * Get the actual instance, which can be the following:
     * BranchDefinition, BranchNodeBranchDefinition
     *
     * @return The actual instance (BranchDefinition, BranchNodeBranchDefinition)
     */
    @SuppressWarnings("unchecked")
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `BranchDefinition`. If the actual instance is not `BranchDefinition`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `BranchDefinition`
     * @throws ClassCastException if the instance is not `BranchDefinition`
     */
    @SuppressWarnings("unchecked")
    public BranchDefinition getBranchDefinition() throws ClassCastException {
        return (BranchDefinition) super.getActualInstance();
    }

    /**
     * Get the actual instance of `BranchNodeBranchDefinition`. If the actual instance is not `BranchNodeBranchDefinition`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `BranchNodeBranchDefinition`
     * @throws ClassCastException if the instance is not `BranchNodeBranchDefinition`
     */
    @SuppressWarnings("unchecked")
    public BranchNodeBranchDefinition getBranchNodeBranchDefinition() throws ClassCastException {
        return (BranchNodeBranchDefinition) super.getActualInstance();
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to NodeDefinitionBranchesInner
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        // validate oneOf schemas one by one
        int validCount = 0;
        ArrayList<String> errorMessages = new ArrayList<>();
        // validate the json string with BranchDefinition
        try {
            BranchDefinition.validateJsonElement(jsonElement);
            validCount++;
        } catch (Exception e) {
            errorMessages.add(
                    String.format(
                            java.util.Locale.ROOT,
                            "Deserialization for BranchDefinition failed with `%s`.",
                            e.getMessage()));
            // continue to the next one
        }
        // validate the json string with BranchNodeBranchDefinition
        try {
            BranchNodeBranchDefinition.validateJsonElement(jsonElement);
            validCount++;
        } catch (Exception e) {
            errorMessages.add(
                    String.format(
                            java.util.Locale.ROOT,
                            "Deserialization for BranchNodeBranchDefinition failed with `%s`.",
                            e.getMessage()));
            // continue to the next one
        }
        if (validCount != 1) {
            throw new IOException(
                    String.format(
                            java.util.Locale.ROOT,
                            "The JSON string is invalid for NodeDefinitionBranchesInner with oneOf schemas: BranchDefinition, BranchNodeBranchDefinition. %d class(es) match the result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s",
                            validCount,
                            errorMessages,
                            jsonElement.toString()));
        }
    }

    /**
     * Create an instance of NodeDefinitionBranchesInner given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of NodeDefinitionBranchesInner
     * @throws IOException if the JSON string is invalid with respect to NodeDefinitionBranchesInner
     */
    public static NodeDefinitionBranchesInner fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, NodeDefinitionBranchesInner.class);
    }

    /**
     * Convert an instance of NodeDefinitionBranchesInner to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
