/*
 * Vertesia API
 * The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.
 *
 * The version of the OpenAPI document: 1.6.0-dev.20260918.061604Z
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.vertesia.model;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.vertesia.JSON;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Objects;

/**
 * OpenAiSpeechOptions
 */
@jakarta.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.22.0")
public class OpenAiSpeechOptions {
    /**
     * Gets or Sets optionId
     */
    @JsonAdapter(OptionIdEnum.Adapter.class)
    public enum OptionIdEnum {
        OPENAI_SPEECH("openai-speech"),

        UNKNOWN_DEFAULT_OPEN_API("unknown_default_open_api");

        private String value;

        OptionIdEnum(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        public static OptionIdEnum fromValue(String value) {
            for (OptionIdEnum b : OptionIdEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            return UNKNOWN_DEFAULT_OPEN_API;
        }

        public static class Adapter extends TypeAdapter<OptionIdEnum> {
            @Override
            public void write(final JsonWriter jsonWriter, final OptionIdEnum enumeration)
                    throws IOException {
                jsonWriter.value(enumeration.getValue());
            }

            @Override
            public OptionIdEnum read(final JsonReader jsonReader) throws IOException {
                String value = jsonReader.nextString();
                return OptionIdEnum.fromValue(value);
            }
        }

        public static void validateJsonElement(JsonElement jsonElement) throws IOException {
            String value = jsonElement.getAsString();
            OptionIdEnum.fromValue(value);
        }
    }

    public static final String SERIALIZED_NAME_OPTION_ID = "_option_id";

    @SerializedName(SERIALIZED_NAME_OPTION_ID)
    @jakarta.annotation.Nullable private OptionIdEnum optionId;

    public static final String SERIALIZED_NAME_VOICE = "voice";

    @SerializedName(SERIALIZED_NAME_VOICE)
    @jakarta.annotation.Nullable private String voice;

    /**
     * Gets or Sets responseFormat
     */
    @JsonAdapter(ResponseFormatEnum.Adapter.class)
    public enum ResponseFormatEnum {
        MP3("mp3"),

        WAV("wav"),

        OPUS("opus"),

        AAC("aac"),

        FLAC("flac"),

        PCM("pcm"),

        UNKNOWN_DEFAULT_OPEN_API("unknown_default_open_api");

        private String value;

        ResponseFormatEnum(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        public static ResponseFormatEnum fromValue(String value) {
            for (ResponseFormatEnum b : ResponseFormatEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            return UNKNOWN_DEFAULT_OPEN_API;
        }

        public static class Adapter extends TypeAdapter<ResponseFormatEnum> {
            @Override
            public void write(final JsonWriter jsonWriter, final ResponseFormatEnum enumeration)
                    throws IOException {
                jsonWriter.value(enumeration.getValue());
            }

            @Override
            public ResponseFormatEnum read(final JsonReader jsonReader) throws IOException {
                String value = jsonReader.nextString();
                return ResponseFormatEnum.fromValue(value);
            }
        }

        public static void validateJsonElement(JsonElement jsonElement) throws IOException {
            String value = jsonElement.getAsString();
            ResponseFormatEnum.fromValue(value);
        }
    }

    public static final String SERIALIZED_NAME_RESPONSE_FORMAT = "response_format";

    @SerializedName(SERIALIZED_NAME_RESPONSE_FORMAT)
    @jakarta.annotation.Nullable private ResponseFormatEnum responseFormat;

    public static final String SERIALIZED_NAME_SPEED = "speed";

    @SerializedName(SERIALIZED_NAME_SPEED)
    @jakarta.annotation.Nullable private BigDecimal speed;

    public static final String SERIALIZED_NAME_INSTRUCTIONS = "instructions";

    @SerializedName(SERIALIZED_NAME_INSTRUCTIONS)
    @jakarta.annotation.Nullable private String instructions;

    public OpenAiSpeechOptions() {}

    public OpenAiSpeechOptions optionId(@jakarta.annotation.Nullable OptionIdEnum optionId) {
        this.optionId = optionId;
        return this;
    }

    /**
     * Get optionId
     * @return optionId
     */
    @jakarta.annotation.Nullable public OptionIdEnum getOptionId() {
        return optionId;
    }

    public void setOptionId(@jakarta.annotation.Nullable OptionIdEnum optionId) {
        this.optionId = optionId;
    }

    public OpenAiSpeechOptions voice(@jakarta.annotation.Nullable String voice) {
        this.voice = voice;
        return this;
    }

    /**
     * Get voice
     * @return voice
     */
    @jakarta.annotation.Nullable public String getVoice() {
        return voice;
    }

    public void setVoice(@jakarta.annotation.Nullable String voice) {
        this.voice = voice;
    }

    public OpenAiSpeechOptions responseFormat(
            @jakarta.annotation.Nullable ResponseFormatEnum responseFormat) {
        this.responseFormat = responseFormat;
        return this;
    }

    /**
     * Get responseFormat
     * @return responseFormat
     */
    @jakarta.annotation.Nullable public ResponseFormatEnum getResponseFormat() {
        return responseFormat;
    }

    public void setResponseFormat(@jakarta.annotation.Nullable ResponseFormatEnum responseFormat) {
        this.responseFormat = responseFormat;
    }

    public OpenAiSpeechOptions speed(@jakarta.annotation.Nullable BigDecimal speed) {
        this.speed = speed;
        return this;
    }

    /**
     * Get speed
     * minimum: 0.25
     * maximum: 4
     * @return speed
     */
    @jakarta.annotation.Nullable public BigDecimal getSpeed() {
        return speed;
    }

    public void setSpeed(@jakarta.annotation.Nullable BigDecimal speed) {
        this.speed = speed;
    }

    public OpenAiSpeechOptions instructions(@jakarta.annotation.Nullable String instructions) {
        this.instructions = instructions;
        return this;
    }

    /**
     * Get instructions
     * @return instructions
     */
    @jakarta.annotation.Nullable public String getInstructions() {
        return instructions;
    }

    public void setInstructions(@jakarta.annotation.Nullable String instructions) {
        this.instructions = instructions;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        OpenAiSpeechOptions openAiSpeechOptions = (OpenAiSpeechOptions) o;
        return Objects.equals(this.optionId, openAiSpeechOptions.optionId)
                && Objects.equals(this.voice, openAiSpeechOptions.voice)
                && Objects.equals(this.responseFormat, openAiSpeechOptions.responseFormat)
                && Objects.equals(this.speed, openAiSpeechOptions.speed)
                && Objects.equals(this.instructions, openAiSpeechOptions.instructions);
    }

    @Override
    public int hashCode() {
        return Objects.hash(optionId, voice, responseFormat, speed, instructions);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class OpenAiSpeechOptions {\n");
        sb.append("    optionId: ").append(toIndentedString(optionId)).append("\n");
        sb.append("    voice: ").append(toIndentedString(voice)).append("\n");
        sb.append("    responseFormat: ").append(toIndentedString(responseFormat)).append("\n");
        sb.append("    speed: ").append(toIndentedString(speed)).append("\n");
        sb.append("    instructions: ").append(toIndentedString(instructions)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        return o == null ? "null" : o.toString().replace("\n", "\n    ");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields =
                new HashSet<String>(
                        Arrays.asList(
                                "_option_id", "voice", "response_format", "speed", "instructions"));

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>(0);
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to OpenAiSpeechOptions
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!OpenAiSpeechOptions.openapiRequiredFields
                    .isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(
                        String.format(
                                java.util.Locale.ROOT,
                                "The required field(s) %s in OpenAiSpeechOptions is not found in the empty JSON string",
                                OpenAiSpeechOptions.openapiRequiredFields.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if ((jsonObj.get("_option_id") != null && !jsonObj.get("_option_id").isJsonNull())
                && !jsonObj.get("_option_id").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `_option_id` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("_option_id").toString()));
        }
        // validate the optional field `_option_id`
        if (jsonObj.get("_option_id") != null && !jsonObj.get("_option_id").isJsonNull()) {
            OptionIdEnum.validateJsonElement(jsonObj.get("_option_id"));
        }
        if ((jsonObj.get("voice") != null && !jsonObj.get("voice").isJsonNull())
                && !jsonObj.get("voice").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `voice` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("voice").toString()));
        }
        if ((jsonObj.get("response_format") != null && !jsonObj.get("response_format").isJsonNull())
                && !jsonObj.get("response_format").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `response_format` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("response_format").toString()));
        }
        // validate the optional field `response_format`
        if (jsonObj.get("response_format") != null
                && !jsonObj.get("response_format").isJsonNull()) {
            ResponseFormatEnum.validateJsonElement(jsonObj.get("response_format"));
        }
        if ((jsonObj.get("instructions") != null && !jsonObj.get("instructions").isJsonNull())
                && !jsonObj.get("instructions").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `instructions` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("instructions").toString()));
        }
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!OpenAiSpeechOptions.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'OpenAiSpeechOptions' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<OpenAiSpeechOptions> thisAdapter =
                    gson.getDelegateAdapter(this, TypeToken.get(OpenAiSpeechOptions.class));

            return (TypeAdapter<T>)
                    new TypeAdapter<OpenAiSpeechOptions>() {
                        @Override
                        public void write(JsonWriter out, OpenAiSpeechOptions value)
                                throws IOException {
                            JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                            elementAdapter.write(out, obj);
                        }

                        @Override
                        public OpenAiSpeechOptions read(JsonReader in) throws IOException {
                            JsonElement jsonElement = elementAdapter.read(in);
                            validateJsonElement(jsonElement);
                            return thisAdapter.fromJsonTree(jsonElement);
                        }
                    }.nullSafe();
        }
    }

    /**
     * Create an instance of OpenAiSpeechOptions given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of OpenAiSpeechOptions
     * @throws IOException if the JSON string is invalid with respect to OpenAiSpeechOptions
     */
    public static OpenAiSpeechOptions fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, OpenAiSpeechOptions.class);
    }

    /**
     * Convert an instance of OpenAiSpeechOptions to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
