/*
 * Vertesia API
 * The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` SDK for typed access from Node.js applications.
 *
 * The version of the OpenAPI document: 1.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.vertesia.model;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.vertesia.JSON;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/**
 * PartialProjectConfiguration
 */
@javax.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.22.0")
public class PartialProjectConfiguration {
    public static final String SERIALIZED_NAME_HUMAN_CONTEXT = "human_context";

    @SerializedName(SERIALIZED_NAME_HUMAN_CONTEXT)
    @javax.annotation.Nullable private String humanContext;

    public static final String SERIALIZED_NAME_DEFAULTS = "defaults";

    @SerializedName(SERIALIZED_NAME_DEFAULTS)
    @javax.annotation.Nullable private ProjectModelDefaults defaults;

    public static final String SERIALIZED_NAME_DEFAULT_VISIBILITY = "default_visibility";

    @SerializedName(SERIALIZED_NAME_DEFAULT_VISIBILITY)
    @javax.annotation.Nullable private ResourceVisibility defaultVisibility;

    public static final String SERIALIZED_NAME_SYNC_CONTENT_PROPERTIES = "sync_content_properties";

    @SerializedName(SERIALIZED_NAME_SYNC_CONTENT_PROPERTIES)
    @javax.annotation.Nullable private Boolean syncContentProperties;

    public static final String SERIALIZED_NAME_EMBEDDINGS = "embeddings";

    @SerializedName(SERIALIZED_NAME_EMBEDDINGS)
    @javax.annotation.Nullable private ProjectConfigurationEmbeddings embeddings;

    public static final String SERIALIZED_NAME_DATACENTER = "datacenter";

    @SerializedName(SERIALIZED_NAME_DATACENTER)
    @javax.annotation.Nullable private String datacenter;

    public static final String SERIALIZED_NAME_STORAGE_BUCKET = "storage_bucket";

    @SerializedName(SERIALIZED_NAME_STORAGE_BUCKET)
    @javax.annotation.Nullable private String storageBucket;

    public static final String SERIALIZED_NAME_AGENT_STREAMING_ENABLED = "agent_streaming_enabled";

    @SerializedName(SERIALIZED_NAME_AGENT_STREAMING_ENABLED)
    @javax.annotation.Nullable private Boolean agentStreamingEnabled;

    public static final String SERIALIZED_NAME_INDEXING = "indexing";

    @SerializedName(SERIALIZED_NAME_INDEXING)
    @javax.annotation.Nullable private ProjectConfigurationIndexing indexing;

    public static final String SERIALIZED_NAME_MAIN_LANGUAGE = "main_language";

    @SerializedName(SERIALIZED_NAME_MAIN_LANGUAGE)
    @javax.annotation.Nullable private String mainLanguage;

    public static final String SERIALIZED_NAME_BROWSER_USE = "browser_use";

    @SerializedName(SERIALIZED_NAME_BROWSER_USE)
    @javax.annotation.Nullable private BrowserUseProjectConfiguration browserUse;

    public static final String SERIALIZED_NAME_PDF_TEMPLATE_OBJECT_ID = "pdf_template_object_id";

    @SerializedName(SERIALIZED_NAME_PDF_TEMPLATE_OBJECT_ID)
    @javax.annotation.Nullable private String pdfTemplateObjectId;

    public PartialProjectConfiguration() {}

    public PartialProjectConfiguration humanContext(
            @javax.annotation.Nullable String humanContext) {
        this.humanContext = humanContext;
        return this;
    }

    /**
     * Get humanContext
     * @return humanContext
     */
    @javax.annotation.Nullable public String getHumanContext() {
        return humanContext;
    }

    public void setHumanContext(@javax.annotation.Nullable String humanContext) {
        this.humanContext = humanContext;
    }

    public PartialProjectConfiguration defaults(
            @javax.annotation.Nullable ProjectModelDefaults defaults) {
        this.defaults = defaults;
        return this;
    }

    /**
     * Get defaults
     * @return defaults
     */
    @javax.annotation.Nullable public ProjectModelDefaults getDefaults() {
        return defaults;
    }

    public void setDefaults(@javax.annotation.Nullable ProjectModelDefaults defaults) {
        this.defaults = defaults;
    }

    public PartialProjectConfiguration defaultVisibility(
            @javax.annotation.Nullable ResourceVisibility defaultVisibility) {
        this.defaultVisibility = defaultVisibility;
        return this;
    }

    /**
     * Get defaultVisibility
     * @return defaultVisibility
     */
    @javax.annotation.Nullable public ResourceVisibility getDefaultVisibility() {
        return defaultVisibility;
    }

    public void setDefaultVisibility(
            @javax.annotation.Nullable ResourceVisibility defaultVisibility) {
        this.defaultVisibility = defaultVisibility;
    }

    public PartialProjectConfiguration syncContentProperties(
            @javax.annotation.Nullable Boolean syncContentProperties) {
        this.syncContentProperties = syncContentProperties;
        return this;
    }

    /**
     * Get syncContentProperties
     * @return syncContentProperties
     */
    @javax.annotation.Nullable public Boolean getSyncContentProperties() {
        return syncContentProperties;
    }

    public void setSyncContentProperties(@javax.annotation.Nullable Boolean syncContentProperties) {
        this.syncContentProperties = syncContentProperties;
    }

    public PartialProjectConfiguration embeddings(
            @javax.annotation.Nullable ProjectConfigurationEmbeddings embeddings) {
        this.embeddings = embeddings;
        return this;
    }

    /**
     * Get embeddings
     * @return embeddings
     */
    @javax.annotation.Nullable public ProjectConfigurationEmbeddings getEmbeddings() {
        return embeddings;
    }

    public void setEmbeddings(
            @javax.annotation.Nullable ProjectConfigurationEmbeddings embeddings) {
        this.embeddings = embeddings;
    }

    public PartialProjectConfiguration datacenter(@javax.annotation.Nullable String datacenter) {
        this.datacenter = datacenter;
        return this;
    }

    /**
     * Get datacenter
     * @return datacenter
     */
    @javax.annotation.Nullable public String getDatacenter() {
        return datacenter;
    }

    public void setDatacenter(@javax.annotation.Nullable String datacenter) {
        this.datacenter = datacenter;
    }

    public PartialProjectConfiguration storageBucket(
            @javax.annotation.Nullable String storageBucket) {
        this.storageBucket = storageBucket;
        return this;
    }

    /**
     * Get storageBucket
     * @return storageBucket
     */
    @javax.annotation.Nullable public String getStorageBucket() {
        return storageBucket;
    }

    public void setStorageBucket(@javax.annotation.Nullable String storageBucket) {
        this.storageBucket = storageBucket;
    }

    public PartialProjectConfiguration agentStreamingEnabled(
            @javax.annotation.Nullable Boolean agentStreamingEnabled) {
        this.agentStreamingEnabled = agentStreamingEnabled;
        return this;
    }

    /**
     * Enable real-time streaming of agent LLM responses to clients. When enabled, LLM responses are streamed chunk-by-chunk via Redis pub/sub. Defaults to true if not specified.
     * @return agentStreamingEnabled
     */
    @javax.annotation.Nullable public Boolean getAgentStreamingEnabled() {
        return agentStreamingEnabled;
    }

    public void setAgentStreamingEnabled(@javax.annotation.Nullable Boolean agentStreamingEnabled) {
        this.agentStreamingEnabled = agentStreamingEnabled;
    }

    public PartialProjectConfiguration indexing(
            @javax.annotation.Nullable ProjectConfigurationIndexing indexing) {
        this.indexing = indexing;
        return this;
    }

    /**
     * Get indexing
     * @return indexing
     */
    @javax.annotation.Nullable public ProjectConfigurationIndexing getIndexing() {
        return indexing;
    }

    public void setIndexing(@javax.annotation.Nullable ProjectConfigurationIndexing indexing) {
        this.indexing = indexing;
    }

    public PartialProjectConfiguration mainLanguage(
            @javax.annotation.Nullable String mainLanguage) {
        this.mainLanguage = mainLanguage;
        return this;
    }

    /**
     * Primary language for full-text search analysis. ISO 639-1 code (e.g., &#39;en&#39;, &#39;fr&#39;, &#39;ja&#39;, &#39;de&#39;). Determines which Elasticsearch analyzer is used for the text field. Defaults to &#39;en&#39; (English/standard analyzer).  Changing this value requires a full reindex to take effect.
     * @return mainLanguage
     */
    @javax.annotation.Nullable public String getMainLanguage() {
        return mainLanguage;
    }

    public void setMainLanguage(@javax.annotation.Nullable String mainLanguage) {
        this.mainLanguage = mainLanguage;
    }

    public PartialProjectConfiguration browserUse(
            @javax.annotation.Nullable BrowserUseProjectConfiguration browserUse) {
        this.browserUse = browserUse;
        return this;
    }

    /**
     * Project defaults and caps for browser_use agent workstreams.
     * @return browserUse
     */
    @javax.annotation.Nullable public BrowserUseProjectConfiguration getBrowserUse() {
        return browserUse;
    }

    public void setBrowserUse(
            @javax.annotation.Nullable BrowserUseProjectConfiguration browserUse) {
        this.browserUse = browserUse;
    }

    public PartialProjectConfiguration pdfTemplateObjectId(
            @javax.annotation.Nullable String pdfTemplateObjectId) {
        this.pdfTemplateObjectId = pdfTemplateObjectId;
        return this;
    }

    /**
     * Object ID of a content object containing a custom LaTeX template (.latex file) to use as the branded PDF template. When set, \&quot;Export as Branded PDF\&quot; uses this template instead of the built-in Vertesia default template.
     * @return pdfTemplateObjectId
     */
    @javax.annotation.Nullable public String getPdfTemplateObjectId() {
        return pdfTemplateObjectId;
    }

    public void setPdfTemplateObjectId(@javax.annotation.Nullable String pdfTemplateObjectId) {
        this.pdfTemplateObjectId = pdfTemplateObjectId;
    }

    /**
     * A container for additional, undeclared properties.
     * This is a holder for any undeclared properties as specified with
     * the 'additionalProperties' keyword in the OAS document.
     */
    private Map<String, Object> additionalProperties;

    /**
     * Set the additional (undeclared) property with the specified name and value.
     * If the property does not already exist, create it otherwise replace it.
     *
     * @param key name of the property
     * @param value value of the property
     * @return the PartialProjectConfiguration instance itself
     */
    public PartialProjectConfiguration putAdditionalProperty(String key, Object value) {
        if (this.additionalProperties == null) {
            this.additionalProperties = new HashMap<String, Object>();
        }
        this.additionalProperties.put(key, value);
        return this;
    }

    /**
     * Return the additional (undeclared) property.
     *
     * @return a map of objects
     */
    public Map<String, Object> getAdditionalProperties() {
        return additionalProperties;
    }

    /**
     * Return the additional (undeclared) property with the specified name.
     *
     * @param key name of the property
     * @return an object
     */
    public Object getAdditionalProperty(String key) {
        if (this.additionalProperties == null) {
            return null;
        }
        return this.additionalProperties.get(key);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PartialProjectConfiguration partialProjectConfiguration = (PartialProjectConfiguration) o;
        return Objects.equals(this.humanContext, partialProjectConfiguration.humanContext)
                && Objects.equals(this.defaults, partialProjectConfiguration.defaults)
                && Objects.equals(
                        this.defaultVisibility, partialProjectConfiguration.defaultVisibility)
                && Objects.equals(
                        this.syncContentProperties,
                        partialProjectConfiguration.syncContentProperties)
                && Objects.equals(this.embeddings, partialProjectConfiguration.embeddings)
                && Objects.equals(this.datacenter, partialProjectConfiguration.datacenter)
                && Objects.equals(this.storageBucket, partialProjectConfiguration.storageBucket)
                && Objects.equals(
                        this.agentStreamingEnabled,
                        partialProjectConfiguration.agentStreamingEnabled)
                && Objects.equals(this.indexing, partialProjectConfiguration.indexing)
                && Objects.equals(this.mainLanguage, partialProjectConfiguration.mainLanguage)
                && Objects.equals(this.browserUse, partialProjectConfiguration.browserUse)
                && Objects.equals(
                        this.pdfTemplateObjectId, partialProjectConfiguration.pdfTemplateObjectId)
                && Objects.equals(
                        this.additionalProperties,
                        partialProjectConfiguration.additionalProperties);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                humanContext,
                defaults,
                defaultVisibility,
                syncContentProperties,
                embeddings,
                datacenter,
                storageBucket,
                agentStreamingEnabled,
                indexing,
                mainLanguage,
                browserUse,
                pdfTemplateObjectId,
                additionalProperties);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class PartialProjectConfiguration {\n");
        sb.append("    humanContext: ").append(toIndentedString(humanContext)).append("\n");
        sb.append("    defaults: ").append(toIndentedString(defaults)).append("\n");
        sb.append("    defaultVisibility: ")
                .append(toIndentedString(defaultVisibility))
                .append("\n");
        sb.append("    syncContentProperties: ")
                .append(toIndentedString(syncContentProperties))
                .append("\n");
        sb.append("    embeddings: ").append(toIndentedString(embeddings)).append("\n");
        sb.append("    datacenter: ").append(toIndentedString(datacenter)).append("\n");
        sb.append("    storageBucket: ").append(toIndentedString(storageBucket)).append("\n");
        sb.append("    agentStreamingEnabled: ")
                .append(toIndentedString(agentStreamingEnabled))
                .append("\n");
        sb.append("    indexing: ").append(toIndentedString(indexing)).append("\n");
        sb.append("    mainLanguage: ").append(toIndentedString(mainLanguage)).append("\n");
        sb.append("    browserUse: ").append(toIndentedString(browserUse)).append("\n");
        sb.append("    pdfTemplateObjectId: ")
                .append(toIndentedString(pdfTemplateObjectId))
                .append("\n");
        sb.append("    additionalProperties: ")
                .append(toIndentedString(additionalProperties))
                .append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        return o == null ? "null" : o.toString().replace("\n", "\n    ");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields =
                new HashSet<String>(
                        Arrays.asList(
                                "human_context",
                                "defaults",
                                "default_visibility",
                                "sync_content_properties",
                                "embeddings",
                                "datacenter",
                                "storage_bucket",
                                "agent_streaming_enabled",
                                "indexing",
                                "main_language",
                                "browser_use",
                                "pdf_template_object_id"));

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>(0);
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to PartialProjectConfiguration
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!PartialProjectConfiguration.openapiRequiredFields
                    .isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(
                        String.format(
                                java.util.Locale.ROOT,
                                "The required field(s) %s in PartialProjectConfiguration is not found in the empty JSON string",
                                PartialProjectConfiguration.openapiRequiredFields.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if ((jsonObj.get("human_context") != null && !jsonObj.get("human_context").isJsonNull())
                && !jsonObj.get("human_context").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `human_context` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("human_context").toString()));
        }
        // validate the optional field `defaults`
        if (jsonObj.get("defaults") != null && !jsonObj.get("defaults").isJsonNull()) {
            ProjectModelDefaults.validateJsonElement(jsonObj.get("defaults"));
        }
        // validate the optional field `default_visibility`
        if (jsonObj.get("default_visibility") != null
                && !jsonObj.get("default_visibility").isJsonNull()) {
            ResourceVisibility.validateJsonElement(jsonObj.get("default_visibility"));
        }
        // validate the optional field `embeddings`
        if (jsonObj.get("embeddings") != null && !jsonObj.get("embeddings").isJsonNull()) {
            ProjectConfigurationEmbeddings.validateJsonElement(jsonObj.get("embeddings"));
        }
        if ((jsonObj.get("datacenter") != null && !jsonObj.get("datacenter").isJsonNull())
                && !jsonObj.get("datacenter").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `datacenter` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("datacenter").toString()));
        }
        if ((jsonObj.get("storage_bucket") != null && !jsonObj.get("storage_bucket").isJsonNull())
                && !jsonObj.get("storage_bucket").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `storage_bucket` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("storage_bucket").toString()));
        }
        // validate the optional field `indexing`
        if (jsonObj.get("indexing") != null && !jsonObj.get("indexing").isJsonNull()) {
            ProjectConfigurationIndexing.validateJsonElement(jsonObj.get("indexing"));
        }
        if ((jsonObj.get("main_language") != null && !jsonObj.get("main_language").isJsonNull())
                && !jsonObj.get("main_language").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `main_language` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("main_language").toString()));
        }
        // validate the optional field `browser_use`
        if (jsonObj.get("browser_use") != null && !jsonObj.get("browser_use").isJsonNull()) {
            BrowserUseProjectConfiguration.validateJsonElement(jsonObj.get("browser_use"));
        }
        if ((jsonObj.get("pdf_template_object_id") != null
                        && !jsonObj.get("pdf_template_object_id").isJsonNull())
                && !jsonObj.get("pdf_template_object_id").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `pdf_template_object_id` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("pdf_template_object_id").toString()));
        }
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!PartialProjectConfiguration.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'PartialProjectConfiguration' and its
                // subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<PartialProjectConfiguration> thisAdapter =
                    gson.getDelegateAdapter(this, TypeToken.get(PartialProjectConfiguration.class));

            return (TypeAdapter<T>)
                    new TypeAdapter<PartialProjectConfiguration>() {
                        @Override
                        public void write(JsonWriter out, PartialProjectConfiguration value)
                                throws IOException {
                            JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                            obj.remove("additionalProperties");
                            // serialize additional properties
                            if (value.getAdditionalProperties() != null) {
                                for (Map.Entry<String, Object> entry :
                                        value.getAdditionalProperties().entrySet()) {
                                    if (entry.getValue() instanceof String)
                                        obj.addProperty(entry.getKey(), (String) entry.getValue());
                                    else if (entry.getValue() instanceof Number)
                                        obj.addProperty(entry.getKey(), (Number) entry.getValue());
                                    else if (entry.getValue() instanceof Boolean)
                                        obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                                    else if (entry.getValue() instanceof Character)
                                        obj.addProperty(
                                                entry.getKey(), (Character) entry.getValue());
                                    else {
                                        JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                                        if (jsonElement.isJsonArray()) {
                                            obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                                        } else {
                                            obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                                        }
                                    }
                                }
                            }
                            elementAdapter.write(out, obj);
                        }

                        @Override
                        public PartialProjectConfiguration read(JsonReader in) throws IOException {
                            JsonElement jsonElement = elementAdapter.read(in);
                            validateJsonElement(jsonElement);
                            JsonObject jsonObj = jsonElement.getAsJsonObject();
                            // store additional fields in the deserialized instance
                            PartialProjectConfiguration instance =
                                    thisAdapter.fromJsonTree(jsonObj);
                            for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
                                if (!openapiFields.contains(entry.getKey())) {
                                    if (entry.getValue().isJsonPrimitive()) { // primitive type
                                        if (entry.getValue().getAsJsonPrimitive().isString())
                                            instance.putAdditionalProperty(
                                                    entry.getKey(), entry.getValue().getAsString());
                                        else if (entry.getValue().getAsJsonPrimitive().isNumber())
                                            instance.putAdditionalProperty(
                                                    entry.getKey(), entry.getValue().getAsNumber());
                                        else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                                            instance.putAdditionalProperty(
                                                    entry.getKey(),
                                                    entry.getValue().getAsBoolean());
                                        else
                                            throw new IllegalArgumentException(
                                                    String.format(
                                                            java.util.Locale.ROOT,
                                                            "The field `%s` has unknown primitive type. Value: %s",
                                                            entry.getKey(),
                                                            entry.getValue().toString()));
                                    } else if (entry.getValue().isJsonArray()) {
                                        instance.putAdditionalProperty(
                                                entry.getKey(),
                                                gson.fromJson(entry.getValue(), List.class));
                                    } else { // JSON object
                                        instance.putAdditionalProperty(
                                                entry.getKey(),
                                                gson.fromJson(entry.getValue(), HashMap.class));
                                    }
                                }
                            }
                            return instance;
                        }
                    }.nullSafe();
        }
    }

    /**
     * Create an instance of PartialProjectConfiguration given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of PartialProjectConfiguration
     * @throws IOException if the JSON string is invalid with respect to PartialProjectConfiguration
     */
    public static PartialProjectConfiguration fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, PartialProjectConfiguration.class);
    }

    /**
     * Convert an instance of PartialProjectConfiguration to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
