/*
 * Vertesia API
 * The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.
 *
 * The version of the OpenAPI document: 1.5.0-dev.20260901.005903Z
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.vertesia.model;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.vertesia.JSON;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Objects;

/**
 * ProcessTestActorDecision
 */
@jakarta.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.22.0")
public class ProcessTestActorDecision {
    public static final String SERIALIZED_NAME_NODE = "node";

    @SerializedName(SERIALIZED_NAME_NODE)
    @jakarta.annotation.Nonnull
    private String node;

    public static final String SERIALIZED_NAME_ACTOR = "actor";

    @SerializedName(SERIALIZED_NAME_ACTOR)
    @jakarta.annotation.Nonnull
    private String actor;

    /**
     * Gets or Sets decision
     */
    @JsonAdapter(DecisionEnum.Adapter.class)
    public enum DecisionEnum {
        ACCEPTED("accepted"),

        FORBIDDEN("forbidden"),

        UNKNOWN_DEFAULT_OPEN_API("unknown_default_open_api");

        private String value;

        DecisionEnum(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        public static DecisionEnum fromValue(String value) {
            for (DecisionEnum b : DecisionEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            return UNKNOWN_DEFAULT_OPEN_API;
        }

        public static class Adapter extends TypeAdapter<DecisionEnum> {
            @Override
            public void write(final JsonWriter jsonWriter, final DecisionEnum enumeration)
                    throws IOException {
                jsonWriter.value(enumeration.getValue());
            }

            @Override
            public DecisionEnum read(final JsonReader jsonReader) throws IOException {
                String value = jsonReader.nextString();
                return DecisionEnum.fromValue(value);
            }
        }

        public static void validateJsonElement(JsonElement jsonElement) throws IOException {
            String value = jsonElement.getAsString();
            DecisionEnum.fromValue(value);
        }
    }

    public static final String SERIALIZED_NAME_DECISION = "decision";

    @SerializedName(SERIALIZED_NAME_DECISION)
    @jakarta.annotation.Nonnull
    private DecisionEnum decision;

    public static final String SERIALIZED_NAME_MESSAGE = "message";

    @SerializedName(SERIALIZED_NAME_MESSAGE)
    @jakarta.annotation.Nullable private String message;

    public ProcessTestActorDecision() {}

    public ProcessTestActorDecision node(@jakarta.annotation.Nonnull String node) {
        this.node = node;
        return this;
    }

    /**
     * Get node
     * @return node
     */
    @jakarta.annotation.Nonnull
    public String getNode() {
        return node;
    }

    public void setNode(@jakarta.annotation.Nonnull String node) {
        this.node = node;
    }

    public ProcessTestActorDecision actor(@jakarta.annotation.Nonnull String actor) {
        this.actor = actor;
        return this;
    }

    /**
     * Get actor
     * @return actor
     */
    @jakarta.annotation.Nonnull
    public String getActor() {
        return actor;
    }

    public void setActor(@jakarta.annotation.Nonnull String actor) {
        this.actor = actor;
    }

    public ProcessTestActorDecision decision(@jakarta.annotation.Nonnull DecisionEnum decision) {
        this.decision = decision;
        return this;
    }

    /**
     * Get decision
     * @return decision
     */
    @jakarta.annotation.Nonnull
    public DecisionEnum getDecision() {
        return decision;
    }

    public void setDecision(@jakarta.annotation.Nonnull DecisionEnum decision) {
        this.decision = decision;
    }

    public ProcessTestActorDecision message(@jakarta.annotation.Nullable String message) {
        this.message = message;
        return this;
    }

    /**
     * Get message
     * @return message
     */
    @jakarta.annotation.Nullable public String getMessage() {
        return message;
    }

    public void setMessage(@jakarta.annotation.Nullable String message) {
        this.message = message;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ProcessTestActorDecision processTestActorDecision = (ProcessTestActorDecision) o;
        return Objects.equals(this.node, processTestActorDecision.node)
                && Objects.equals(this.actor, processTestActorDecision.actor)
                && Objects.equals(this.decision, processTestActorDecision.decision)
                && Objects.equals(this.message, processTestActorDecision.message);
    }

    @Override
    public int hashCode() {
        return Objects.hash(node, actor, decision, message);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ProcessTestActorDecision {\n");
        sb.append("    node: ").append(toIndentedString(node)).append("\n");
        sb.append("    actor: ").append(toIndentedString(actor)).append("\n");
        sb.append("    decision: ").append(toIndentedString(decision)).append("\n");
        sb.append("    message: ").append(toIndentedString(message)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        return o == null ? "null" : o.toString().replace("\n", "\n    ");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>(Arrays.asList("node", "actor", "decision", "message"));

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>(Arrays.asList("node", "actor", "decision"));
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to ProcessTestActorDecision
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!ProcessTestActorDecision.openapiRequiredFields
                    .isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(
                        String.format(
                                java.util.Locale.ROOT,
                                "The required field(s) %s in ProcessTestActorDecision is not found in the empty JSON string",
                                ProcessTestActorDecision.openapiRequiredFields.toString()));
            }
        }

        // check to make sure all required properties/fields are present in the JSON string
        for (String requiredField : ProcessTestActorDecision.openapiRequiredFields) {
            if (jsonElement.getAsJsonObject().get(requiredField) == null) {
                throw new IllegalArgumentException(
                        String.format(
                                java.util.Locale.ROOT,
                                "The required field `%s` is not found in the JSON string: %s",
                                requiredField,
                                jsonElement.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if (!jsonObj.get("node").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `node` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("node").toString()));
        }
        if (!jsonObj.get("actor").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `actor` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("actor").toString()));
        }
        if (!jsonObj.get("decision").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `decision` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("decision").toString()));
        }
        // validate the required field `decision`
        DecisionEnum.validateJsonElement(jsonObj.get("decision"));
        if ((jsonObj.get("message") != null && !jsonObj.get("message").isJsonNull())
                && !jsonObj.get("message").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `message` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("message").toString()));
        }
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!ProcessTestActorDecision.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'ProcessTestActorDecision' and its
                // subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<ProcessTestActorDecision> thisAdapter =
                    gson.getDelegateAdapter(this, TypeToken.get(ProcessTestActorDecision.class));

            return (TypeAdapter<T>)
                    new TypeAdapter<ProcessTestActorDecision>() {
                        @Override
                        public void write(JsonWriter out, ProcessTestActorDecision value)
                                throws IOException {
                            JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                            elementAdapter.write(out, obj);
                        }

                        @Override
                        public ProcessTestActorDecision read(JsonReader in) throws IOException {
                            JsonElement jsonElement = elementAdapter.read(in);
                            validateJsonElement(jsonElement);
                            return thisAdapter.fromJsonTree(jsonElement);
                        }
                    }.nullSafe();
        }
    }

    /**
     * Create an instance of ProcessTestActorDecision given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of ProcessTestActorDecision
     * @throws IOException if the JSON string is invalid with respect to ProcessTestActorDecision
     */
    public static ProcessTestActorDecision fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, ProcessTestActorDecision.class);
    }

    /**
     * Convert an instance of ProcessTestActorDecision to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
