/*
 * Vertesia API
 * The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.
 *
 * The version of the OpenAPI document: 1.4.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.vertesia.model;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.vertesia.JSON;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;

/**
 * ProcessDefinitionBody
 */
@jakarta.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.22.0")
public class ProcessDefinitionBody {
    public static final String SERIALIZED_NAME_FORMAT_VERSION = "format_version";

    @SerializedName(SERIALIZED_NAME_FORMAT_VERSION)
    @jakarta.annotation.Nonnull
    private ProcessDefinitionFormatVersion formatVersion;

    public static final String SERIALIZED_NAME_PROCESS = "process";

    @SerializedName(SERIALIZED_NAME_PROCESS)
    @jakarta.annotation.Nonnull
    private String process;

    public static final String SERIALIZED_NAME_DESCRIPTION = "description";

    @SerializedName(SERIALIZED_NAME_DESCRIPTION)
    @jakarta.annotation.Nullable private String description;

    public static final String SERIALIZED_NAME_INITIAL = "initial";

    @SerializedName(SERIALIZED_NAME_INITIAL)
    @jakarta.annotation.Nonnull
    private String initial;

    public static final String SERIALIZED_NAME_MODEL = "model";

    @SerializedName(SERIALIZED_NAME_MODEL)
    @jakarta.annotation.Nullable private String model;

    public static final String SERIALIZED_NAME_CONTEXT = "context";

    @SerializedName(SERIALIZED_NAME_CONTEXT)
    @jakarta.annotation.Nonnull
    private ProcessContextDefinition context;

    public static final String SERIALIZED_NAME_NODES = "nodes";

    @SerializedName(SERIALIZED_NAME_NODES)
    @jakarta.annotation.Nonnull
    private Map<String, NodeDefinition> nodes = new HashMap<>();

    public static final String SERIALIZED_NAME_METADATA = "metadata";

    @SerializedName(SERIALIZED_NAME_METADATA)
    @jakarta.annotation.Nullable private Map<String, Object> metadata = new HashMap<>();

    public ProcessDefinitionBody() {}

    public ProcessDefinitionBody formatVersion(
            @jakarta.annotation.Nonnull ProcessDefinitionFormatVersion formatVersion) {
        this.formatVersion = formatVersion;
        return this;
    }

    /**
     * Get formatVersion
     * @return formatVersion
     */
    @jakarta.annotation.Nonnull
    public ProcessDefinitionFormatVersion getFormatVersion() {
        return formatVersion;
    }

    public void setFormatVersion(
            @jakarta.annotation.Nonnull ProcessDefinitionFormatVersion formatVersion) {
        this.formatVersion = formatVersion;
    }

    public ProcessDefinitionBody process(@jakarta.annotation.Nonnull String process) {
        this.process = process;
        return this;
    }

    /**
     * Get process
     * @return process
     */
    @jakarta.annotation.Nonnull
    public String getProcess() {
        return process;
    }

    public void setProcess(@jakarta.annotation.Nonnull String process) {
        this.process = process;
    }

    public ProcessDefinitionBody description(@jakarta.annotation.Nullable String description) {
        this.description = description;
        return this;
    }

    /**
     * Get description
     * @return description
     */
    @jakarta.annotation.Nullable public String getDescription() {
        return description;
    }

    public void setDescription(@jakarta.annotation.Nullable String description) {
        this.description = description;
    }

    public ProcessDefinitionBody initial(@jakarta.annotation.Nonnull String initial) {
        this.initial = initial;
        return this;
    }

    /**
     * Get initial
     * @return initial
     */
    @jakarta.annotation.Nonnull
    public String getInitial() {
        return initial;
    }

    public void setInitial(@jakarta.annotation.Nonnull String initial) {
        this.initial = initial;
    }

    public ProcessDefinitionBody model(@jakarta.annotation.Nullable String model) {
        this.model = model;
        return this;
    }

    /**
     * Get model
     * @return model
     */
    @jakarta.annotation.Nullable public String getModel() {
        return model;
    }

    public void setModel(@jakarta.annotation.Nullable String model) {
        this.model = model;
    }

    public ProcessDefinitionBody context(
            @jakarta.annotation.Nonnull ProcessContextDefinition context) {
        this.context = context;
        return this;
    }

    /**
     * Get context
     * @return context
     */
    @jakarta.annotation.Nonnull
    public ProcessContextDefinition getContext() {
        return context;
    }

    public void setContext(@jakarta.annotation.Nonnull ProcessContextDefinition context) {
        this.context = context;
    }

    public ProcessDefinitionBody nodes(
            @jakarta.annotation.Nonnull Map<String, NodeDefinition> nodes) {
        this.nodes = nodes;
        return this;
    }

    public ProcessDefinitionBody putNodesItem(String key, NodeDefinition nodesItem) {
        if (this.nodes == null) {
            this.nodes = new HashMap<>();
        }
        this.nodes.put(key, nodesItem);
        return this;
    }

    /**
     * Get nodes
     * @return nodes
     */
    @jakarta.annotation.Nonnull
    public Map<String, NodeDefinition> getNodes() {
        return nodes;
    }

    public void setNodes(@jakarta.annotation.Nonnull Map<String, NodeDefinition> nodes) {
        this.nodes = nodes;
    }

    public ProcessDefinitionBody metadata(
            @jakarta.annotation.Nullable Map<String, Object> metadata) {
        this.metadata = metadata;
        return this;
    }

    public ProcessDefinitionBody putMetadataItem(String key, Object metadataItem) {
        if (this.metadata == null) {
            this.metadata = new HashMap<>();
        }
        this.metadata.put(key, metadataItem);
        return this;
    }

    /**
     * Get metadata
     * @return metadata
     */
    @jakarta.annotation.Nullable public Map<String, Object> getMetadata() {
        return metadata;
    }

    public void setMetadata(@jakarta.annotation.Nullable Map<String, Object> metadata) {
        this.metadata = metadata;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ProcessDefinitionBody processDefinitionBody = (ProcessDefinitionBody) o;
        return Objects.equals(this.formatVersion, processDefinitionBody.formatVersion)
                && Objects.equals(this.process, processDefinitionBody.process)
                && Objects.equals(this.description, processDefinitionBody.description)
                && Objects.equals(this.initial, processDefinitionBody.initial)
                && Objects.equals(this.model, processDefinitionBody.model)
                && Objects.equals(this.context, processDefinitionBody.context)
                && Objects.equals(this.nodes, processDefinitionBody.nodes)
                && Objects.equals(this.metadata, processDefinitionBody.metadata);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                formatVersion, process, description, initial, model, context, nodes, metadata);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ProcessDefinitionBody {\n");
        sb.append("    formatVersion: ").append(toIndentedString(formatVersion)).append("\n");
        sb.append("    process: ").append(toIndentedString(process)).append("\n");
        sb.append("    description: ").append(toIndentedString(description)).append("\n");
        sb.append("    initial: ").append(toIndentedString(initial)).append("\n");
        sb.append("    model: ").append(toIndentedString(model)).append("\n");
        sb.append("    context: ").append(toIndentedString(context)).append("\n");
        sb.append("    nodes: ").append(toIndentedString(nodes)).append("\n");
        sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        return o == null ? "null" : o.toString().replace("\n", "\n    ");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields =
                new HashSet<String>(
                        Arrays.asList(
                                "format_version",
                                "process",
                                "description",
                                "initial",
                                "model",
                                "context",
                                "nodes",
                                "metadata"));

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields =
                new HashSet<String>(
                        Arrays.asList("format_version", "process", "initial", "context", "nodes"));
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to ProcessDefinitionBody
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!ProcessDefinitionBody.openapiRequiredFields
                    .isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(
                        String.format(
                                java.util.Locale.ROOT,
                                "The required field(s) %s in ProcessDefinitionBody is not found in the empty JSON string",
                                ProcessDefinitionBody.openapiRequiredFields.toString()));
            }
        }

        // check to make sure all required properties/fields are present in the JSON string
        for (String requiredField : ProcessDefinitionBody.openapiRequiredFields) {
            if (jsonElement.getAsJsonObject().get(requiredField) == null) {
                throw new IllegalArgumentException(
                        String.format(
                                java.util.Locale.ROOT,
                                "The required field `%s` is not found in the JSON string: %s",
                                requiredField,
                                jsonElement.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        // validate the required field `format_version`
        ProcessDefinitionFormatVersion.validateJsonElement(jsonObj.get("format_version"));
        if (!jsonObj.get("process").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `process` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("process").toString()));
        }
        if ((jsonObj.get("description") != null && !jsonObj.get("description").isJsonNull())
                && !jsonObj.get("description").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `description` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("description").toString()));
        }
        if (!jsonObj.get("initial").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `initial` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("initial").toString()));
        }
        if ((jsonObj.get("model") != null && !jsonObj.get("model").isJsonNull())
                && !jsonObj.get("model").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `model` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("model").toString()));
        }
        // validate the required field `context`
        ProcessContextDefinition.validateJsonElement(jsonObj.get("context"));
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!ProcessDefinitionBody.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'ProcessDefinitionBody' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<ProcessDefinitionBody> thisAdapter =
                    gson.getDelegateAdapter(this, TypeToken.get(ProcessDefinitionBody.class));

            return (TypeAdapter<T>)
                    new TypeAdapter<ProcessDefinitionBody>() {
                        @Override
                        public void write(JsonWriter out, ProcessDefinitionBody value)
                                throws IOException {
                            JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                            elementAdapter.write(out, obj);
                        }

                        @Override
                        public ProcessDefinitionBody read(JsonReader in) throws IOException {
                            JsonElement jsonElement = elementAdapter.read(in);
                            validateJsonElement(jsonElement);
                            return thisAdapter.fromJsonTree(jsonElement);
                        }
                    }.nullSafe();
        }
    }

    /**
     * Create an instance of ProcessDefinitionBody given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of ProcessDefinitionBody
     * @throws IOException if the JSON string is invalid with respect to ProcessDefinitionBody
     */
    public static ProcessDefinitionBody fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, ProcessDefinitionBody.class);
    }

    /**
     * Convert an instance of ProcessDefinitionBody to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
