/*
 * Vertesia API
 * The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` SDK for typed access from Node.js applications.
 *
 * The version of the OpenAPI document: 1.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.vertesia.model;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.vertesia.JSON;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Objects;

/**
 * RenditionWithDimensions
 */
@jakarta.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.22.0")
public class RenditionWithDimensions {
    public static final String SERIALIZED_NAME_NAME = "name";

    @SerializedName(SERIALIZED_NAME_NAME)
    @jakarta.annotation.Nonnull
    private String name;

    public static final String SERIALIZED_NAME_CONTENT = "content";

    @SerializedName(SERIALIZED_NAME_CONTENT)
    @jakarta.annotation.Nonnull
    private ContentSource content;

    public static final String SERIALIZED_NAME_DIMENSIONS = "dimensions";

    @SerializedName(SERIALIZED_NAME_DIMENSIONS)
    @jakarta.annotation.Nonnull
    private Dimensions dimensions;

    public RenditionWithDimensions() {}

    public RenditionWithDimensions name(@jakarta.annotation.Nonnull String name) {
        this.name = name;
        return this;
    }

    /**
     * Get name
     * @return name
     */
    @jakarta.annotation.Nonnull
    public String getName() {
        return name;
    }

    public void setName(@jakarta.annotation.Nonnull String name) {
        this.name = name;
    }

    public RenditionWithDimensions content(@jakarta.annotation.Nonnull ContentSource content) {
        this.content = content;
        return this;
    }

    /**
     * Get content
     * @return content
     */
    @jakarta.annotation.Nonnull
    public ContentSource getContent() {
        return content;
    }

    public void setContent(@jakarta.annotation.Nonnull ContentSource content) {
        this.content = content;
    }

    public RenditionWithDimensions dimensions(@jakarta.annotation.Nonnull Dimensions dimensions) {
        this.dimensions = dimensions;
        return this;
    }

    /**
     * Get dimensions
     * @return dimensions
     */
    @jakarta.annotation.Nonnull
    public Dimensions getDimensions() {
        return dimensions;
    }

    public void setDimensions(@jakarta.annotation.Nonnull Dimensions dimensions) {
        this.dimensions = dimensions;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        RenditionWithDimensions renditionWithDimensions = (RenditionWithDimensions) o;
        return Objects.equals(this.name, renditionWithDimensions.name)
                && Objects.equals(this.content, renditionWithDimensions.content)
                && Objects.equals(this.dimensions, renditionWithDimensions.dimensions);
    }

    @Override
    public int hashCode() {
        return Objects.hash(name, content, dimensions);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class RenditionWithDimensions {\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    content: ").append(toIndentedString(content)).append("\n");
        sb.append("    dimensions: ").append(toIndentedString(dimensions)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        return o == null ? "null" : o.toString().replace("\n", "\n    ");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>(Arrays.asList("name", "content", "dimensions"));

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>(Arrays.asList("name", "content", "dimensions"));
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to RenditionWithDimensions
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!RenditionWithDimensions.openapiRequiredFields
                    .isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(
                        String.format(
                                java.util.Locale.ROOT,
                                "The required field(s) %s in RenditionWithDimensions is not found in the empty JSON string",
                                RenditionWithDimensions.openapiRequiredFields.toString()));
            }
        }

        // check to make sure all required properties/fields are present in the JSON string
        for (String requiredField : RenditionWithDimensions.openapiRequiredFields) {
            if (jsonElement.getAsJsonObject().get(requiredField) == null) {
                throw new IllegalArgumentException(
                        String.format(
                                java.util.Locale.ROOT,
                                "The required field `%s` is not found in the JSON string: %s",
                                requiredField,
                                jsonElement.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if (!jsonObj.get("name").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `name` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("name").toString()));
        }
        // validate the required field `content`
        ContentSource.validateJsonElement(jsonObj.get("content"));
        // validate the required field `dimensions`
        Dimensions.validateJsonElement(jsonObj.get("dimensions"));
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!RenditionWithDimensions.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'RenditionWithDimensions' and its
                // subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<RenditionWithDimensions> thisAdapter =
                    gson.getDelegateAdapter(this, TypeToken.get(RenditionWithDimensions.class));

            return (TypeAdapter<T>)
                    new TypeAdapter<RenditionWithDimensions>() {
                        @Override
                        public void write(JsonWriter out, RenditionWithDimensions value)
                                throws IOException {
                            JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                            elementAdapter.write(out, obj);
                        }

                        @Override
                        public RenditionWithDimensions read(JsonReader in) throws IOException {
                            JsonElement jsonElement = elementAdapter.read(in);
                            validateJsonElement(jsonElement);
                            return thisAdapter.fromJsonTree(jsonElement);
                        }
                    }.nullSafe();
        }
    }

    /**
     * Create an instance of RenditionWithDimensions given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of RenditionWithDimensions
     * @throws IOException if the JSON string is invalid with respect to RenditionWithDimensions
     */
    public static RenditionWithDimensions fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, RenditionWithDimensions.class);
    }

    /**
     * Convert an instance of RenditionWithDimensions to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
