/*
 * Vertesia API
 * The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.
 *
 * The version of the OpenAPI document: 1.4.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.vertesia.model;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.vertesia.JSON;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Objects;

/**
 * Polled status response for markdown rendering workflow.
 */
@jakarta.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.22.0")
public class RenderMarkdownStatusResponse {
    public static final String SERIALIZED_NAME_WORKFLOW_ID = "workflow_id";

    @SerializedName(SERIALIZED_NAME_WORKFLOW_ID)
    @jakarta.annotation.Nullable private String workflowId;

    public static final String SERIALIZED_NAME_WORKFLOW_RUN_ID = "workflow_run_id";

    @SerializedName(SERIALIZED_NAME_WORKFLOW_RUN_ID)
    @jakarta.annotation.Nullable private String workflowRunId;

    public static final String SERIALIZED_NAME_STATUS = "status";

    @SerializedName(SERIALIZED_NAME_STATUS)
    @jakarta.annotation.Nonnull
    private WorkflowExecutionStatus status;

    public static final String SERIALIZED_NAME_FORMAT = "format";

    @SerializedName(SERIALIZED_NAME_FORMAT)
    @jakarta.annotation.Nullable private MarkdownRenditionFormat format;

    public static final String SERIALIZED_NAME_DOWNLOAD_URL = "download_url";

    @SerializedName(SERIALIZED_NAME_DOWNLOAD_URL)
    @jakarta.annotation.Nullable private String downloadUrl;

    public static final String SERIALIZED_NAME_FILE_URI = "file_uri";

    @SerializedName(SERIALIZED_NAME_FILE_URI)
    @jakarta.annotation.Nullable private String fileUri;

    public static final String SERIALIZED_NAME_ERROR = "error";

    @SerializedName(SERIALIZED_NAME_ERROR)
    @jakarta.annotation.Nullable private String error;

    public RenderMarkdownStatusResponse() {}

    public RenderMarkdownStatusResponse workflowId(@jakarta.annotation.Nullable String workflowId) {
        this.workflowId = workflowId;
        return this;
    }

    /**
     * Get workflowId
     * @return workflowId
     */
    @jakarta.annotation.Nullable public String getWorkflowId() {
        return workflowId;
    }

    public void setWorkflowId(@jakarta.annotation.Nullable String workflowId) {
        this.workflowId = workflowId;
    }

    public RenderMarkdownStatusResponse workflowRunId(
            @jakarta.annotation.Nullable String workflowRunId) {
        this.workflowRunId = workflowRunId;
        return this;
    }

    /**
     * Get workflowRunId
     * @return workflowRunId
     */
    @jakarta.annotation.Nullable public String getWorkflowRunId() {
        return workflowRunId;
    }

    public void setWorkflowRunId(@jakarta.annotation.Nullable String workflowRunId) {
        this.workflowRunId = workflowRunId;
    }

    public RenderMarkdownStatusResponse status(
            @jakarta.annotation.Nonnull WorkflowExecutionStatus status) {
        this.status = status;
        return this;
    }

    /**
     * Get status
     * @return status
     */
    @jakarta.annotation.Nonnull
    public WorkflowExecutionStatus getStatus() {
        return status;
    }

    public void setStatus(@jakarta.annotation.Nonnull WorkflowExecutionStatus status) {
        this.status = status;
    }

    public RenderMarkdownStatusResponse format(
            @jakarta.annotation.Nullable MarkdownRenditionFormat format) {
        this.format = format;
        return this;
    }

    /**
     * Requested output format (if known)
     * @return format
     */
    @jakarta.annotation.Nullable public MarkdownRenditionFormat getFormat() {
        return format;
    }

    public void setFormat(@jakarta.annotation.Nullable MarkdownRenditionFormat format) {
        this.format = format;
    }

    public RenderMarkdownStatusResponse downloadUrl(
            @jakarta.annotation.Nullable String downloadUrl) {
        this.downloadUrl = downloadUrl;
        return this;
    }

    /**
     * Download URL for completed output
     * @return downloadUrl
     */
    @jakarta.annotation.Nullable public String getDownloadUrl() {
        return downloadUrl;
    }

    public void setDownloadUrl(@jakarta.annotation.Nullable String downloadUrl) {
        this.downloadUrl = downloadUrl;
    }

    public RenderMarkdownStatusResponse fileUri(@jakarta.annotation.Nullable String fileUri) {
        this.fileUri = fileUri;
        return this;
    }

    /**
     * File URI in storage for completed output
     * @return fileUri
     */
    @jakarta.annotation.Nullable public String getFileUri() {
        return fileUri;
    }

    public void setFileUri(@jakarta.annotation.Nullable String fileUri) {
        this.fileUri = fileUri;
    }

    public RenderMarkdownStatusResponse error(@jakarta.annotation.Nullable String error) {
        this.error = error;
        return this;
    }

    /**
     * Error details for failed/terminated runs
     * @return error
     */
    @jakarta.annotation.Nullable public String getError() {
        return error;
    }

    public void setError(@jakarta.annotation.Nullable String error) {
        this.error = error;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        RenderMarkdownStatusResponse renderMarkdownStatusResponse =
                (RenderMarkdownStatusResponse) o;
        return Objects.equals(this.workflowId, renderMarkdownStatusResponse.workflowId)
                && Objects.equals(this.workflowRunId, renderMarkdownStatusResponse.workflowRunId)
                && Objects.equals(this.status, renderMarkdownStatusResponse.status)
                && Objects.equals(this.format, renderMarkdownStatusResponse.format)
                && Objects.equals(this.downloadUrl, renderMarkdownStatusResponse.downloadUrl)
                && Objects.equals(this.fileUri, renderMarkdownStatusResponse.fileUri)
                && Objects.equals(this.error, renderMarkdownStatusResponse.error);
    }

    @Override
    public int hashCode() {
        return Objects.hash(workflowId, workflowRunId, status, format, downloadUrl, fileUri, error);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class RenderMarkdownStatusResponse {\n");
        sb.append("    workflowId: ").append(toIndentedString(workflowId)).append("\n");
        sb.append("    workflowRunId: ").append(toIndentedString(workflowRunId)).append("\n");
        sb.append("    status: ").append(toIndentedString(status)).append("\n");
        sb.append("    format: ").append(toIndentedString(format)).append("\n");
        sb.append("    downloadUrl: ").append(toIndentedString(downloadUrl)).append("\n");
        sb.append("    fileUri: ").append(toIndentedString(fileUri)).append("\n");
        sb.append("    error: ").append(toIndentedString(error)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        return o == null ? "null" : o.toString().replace("\n", "\n    ");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields =
                new HashSet<String>(
                        Arrays.asList(
                                "workflow_id",
                                "workflow_run_id",
                                "status",
                                "format",
                                "download_url",
                                "file_uri",
                                "error"));

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields =
                new HashSet<String>(Arrays.asList("workflow_id", "workflow_run_id", "status"));
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to RenderMarkdownStatusResponse
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!RenderMarkdownStatusResponse.openapiRequiredFields
                    .isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(
                        String.format(
                                java.util.Locale.ROOT,
                                "The required field(s) %s in RenderMarkdownStatusResponse is not found in the empty JSON string",
                                RenderMarkdownStatusResponse.openapiRequiredFields.toString()));
            }
        }

        // check to make sure all required properties/fields are present in the JSON string
        for (String requiredField : RenderMarkdownStatusResponse.openapiRequiredFields) {
            if (jsonElement.getAsJsonObject().get(requiredField) == null) {
                throw new IllegalArgumentException(
                        String.format(
                                java.util.Locale.ROOT,
                                "The required field `%s` is not found in the JSON string: %s",
                                requiredField,
                                jsonElement.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if ((jsonObj.get("workflow_id") != null && !jsonObj.get("workflow_id").isJsonNull())
                && !jsonObj.get("workflow_id").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `workflow_id` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("workflow_id").toString()));
        }
        if ((jsonObj.get("workflow_run_id") != null && !jsonObj.get("workflow_run_id").isJsonNull())
                && !jsonObj.get("workflow_run_id").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `workflow_run_id` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("workflow_run_id").toString()));
        }
        // validate the required field `status`
        WorkflowExecutionStatus.validateJsonElement(jsonObj.get("status"));
        // validate the optional field `format`
        if (jsonObj.get("format") != null && !jsonObj.get("format").isJsonNull()) {
            MarkdownRenditionFormat.validateJsonElement(jsonObj.get("format"));
        }
        if ((jsonObj.get("download_url") != null && !jsonObj.get("download_url").isJsonNull())
                && !jsonObj.get("download_url").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `download_url` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("download_url").toString()));
        }
        if ((jsonObj.get("file_uri") != null && !jsonObj.get("file_uri").isJsonNull())
                && !jsonObj.get("file_uri").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `file_uri` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("file_uri").toString()));
        }
        if ((jsonObj.get("error") != null && !jsonObj.get("error").isJsonNull())
                && !jsonObj.get("error").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `error` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("error").toString()));
        }
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!RenderMarkdownStatusResponse.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'RenderMarkdownStatusResponse' and its
                // subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<RenderMarkdownStatusResponse> thisAdapter =
                    gson.getDelegateAdapter(
                            this, TypeToken.get(RenderMarkdownStatusResponse.class));

            return (TypeAdapter<T>)
                    new TypeAdapter<RenderMarkdownStatusResponse>() {
                        @Override
                        public void write(JsonWriter out, RenderMarkdownStatusResponse value)
                                throws IOException {
                            JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                            elementAdapter.write(out, obj);
                        }

                        @Override
                        public RenderMarkdownStatusResponse read(JsonReader in) throws IOException {
                            JsonElement jsonElement = elementAdapter.read(in);
                            validateJsonElement(jsonElement);
                            return thisAdapter.fromJsonTree(jsonElement);
                        }
                    }.nullSafe();
        }
    }

    /**
     * Create an instance of RenderMarkdownStatusResponse given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of RenderMarkdownStatusResponse
     * @throws IOException if the JSON string is invalid with respect to RenderMarkdownStatusResponse
     */
    public static RenderMarkdownStatusResponse fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, RenderMarkdownStatusResponse.class);
    }

    /**
     * Convert an instance of RenderMarkdownStatusResponse to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
