/*
 * Vertesia API
 * The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.
 *
 * The version of the OpenAPI document: 1.6.0-dev
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.vertesia.model;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.vertesia.JSON;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashSet;
import java.util.List;
import java.util.Objects;

/**
 * RenderingTemplateDefinition
 */
@jakarta.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.22.0")
public class RenderingTemplateDefinition {
    public static final String SERIALIZED_NAME_ID = "id";

    @SerializedName(SERIALIZED_NAME_ID)
    @jakarta.annotation.Nonnull
    private String id;

    public static final String SERIALIZED_NAME_NAME = "name";

    @SerializedName(SERIALIZED_NAME_NAME)
    @jakarta.annotation.Nonnull
    private String name;

    public static final String SERIALIZED_NAME_TITLE = "title";

    @SerializedName(SERIALIZED_NAME_TITLE)
    @jakarta.annotation.Nullable private String title;

    public static final String SERIALIZED_NAME_DESCRIPTION = "description";

    @SerializedName(SERIALIZED_NAME_DESCRIPTION)
    @jakarta.annotation.Nonnull
    private String description;

    /**
     * Template type
     */
    @JsonAdapter(TypeEnum.Adapter.class)
    public enum TypeEnum {
        PRESENTATION("presentation"),

        DOCUMENT("document"),

        UNKNOWN_DEFAULT_OPEN_API("unknown_default_open_api");

        private String value;

        TypeEnum(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        public static TypeEnum fromValue(String value) {
            for (TypeEnum b : TypeEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            return UNKNOWN_DEFAULT_OPEN_API;
        }

        public static class Adapter extends TypeAdapter<TypeEnum> {
            @Override
            public void write(final JsonWriter jsonWriter, final TypeEnum enumeration)
                    throws IOException {
                jsonWriter.value(enumeration.getValue());
            }

            @Override
            public TypeEnum read(final JsonReader jsonReader) throws IOException {
                String value = jsonReader.nextString();
                return TypeEnum.fromValue(value);
            }
        }

        public static void validateJsonElement(JsonElement jsonElement) throws IOException {
            String value = jsonElement.getAsString();
            TypeEnum.fromValue(value);
        }
    }

    public static final String SERIALIZED_NAME_TYPE = "type";

    @SerializedName(SERIALIZED_NAME_TYPE)
    @jakarta.annotation.Nonnull
    private TypeEnum type;

    public static final String SERIALIZED_NAME_TAGS = "tags";

    @SerializedName(SERIALIZED_NAME_TAGS)
    @jakarta.annotation.Nullable private List<String> tags = new ArrayList<>();

    public static final String SERIALIZED_NAME_ASSETS = "assets";

    @SerializedName(SERIALIZED_NAME_ASSETS)
    @jakarta.annotation.Nonnull
    private List<String> assets = new ArrayList<>();

    public static final String SERIALIZED_NAME_INSTRUCTIONS = "instructions";

    @SerializedName(SERIALIZED_NAME_INSTRUCTIONS)
    @jakarta.annotation.Nonnull
    private String instructions;

    public RenderingTemplateDefinition() {}

    public RenderingTemplateDefinition id(@jakarta.annotation.Nonnull String id) {
        this.id = id;
        return this;
    }

    /**
     * Unique template id: \&quot;collection:name\&quot;
     * @return id
     */
    @jakarta.annotation.Nonnull
    public String getId() {
        return id;
    }

    public void setId(@jakarta.annotation.Nonnull String id) {
        this.id = id;
    }

    public RenderingTemplateDefinition name(@jakarta.annotation.Nonnull String name) {
        this.name = name;
        return this;
    }

    /**
     * Unique template name (kebab-case)
     * @return name
     */
    @jakarta.annotation.Nonnull
    public String getName() {
        return name;
    }

    public void setName(@jakarta.annotation.Nonnull String name) {
        this.name = name;
    }

    public RenderingTemplateDefinition title(@jakarta.annotation.Nullable String title) {
        this.title = title;
        return this;
    }

    /**
     * Display title
     * @return title
     */
    @jakarta.annotation.Nullable public String getTitle() {
        return title;
    }

    public void setTitle(@jakarta.annotation.Nullable String title) {
        this.title = title;
    }

    public RenderingTemplateDefinition description(@jakarta.annotation.Nonnull String description) {
        this.description = description;
        return this;
    }

    /**
     * Short description
     * @return description
     */
    @jakarta.annotation.Nonnull
    public String getDescription() {
        return description;
    }

    public void setDescription(@jakarta.annotation.Nonnull String description) {
        this.description = description;
    }

    public RenderingTemplateDefinition type(@jakarta.annotation.Nonnull TypeEnum type) {
        this.type = type;
        return this;
    }

    /**
     * Template type
     * @return type
     */
    @jakarta.annotation.Nonnull
    public TypeEnum getType() {
        return type;
    }

    public void setType(@jakarta.annotation.Nonnull TypeEnum type) {
        this.type = type;
    }

    public RenderingTemplateDefinition tags(@jakarta.annotation.Nullable List<String> tags) {
        this.tags = tags;
        return this;
    }

    public RenderingTemplateDefinition addTagsItem(String tagsItem) {
        if (this.tags == null) {
            this.tags = new ArrayList<>();
        }
        this.tags.add(tagsItem);
        return this;
    }

    /**
     * Tags for categorization
     * @return tags
     */
    @jakarta.annotation.Nullable public List<String> getTags() {
        return tags;
    }

    public void setTags(@jakarta.annotation.Nullable List<String> tags) {
        this.tags = tags;
    }

    public RenderingTemplateDefinition assets(@jakarta.annotation.Nonnull List<String> assets) {
        this.assets = assets;
        return this;
    }

    public RenderingTemplateDefinition addAssetsItem(String assetsItem) {
        if (this.assets == null) {
            this.assets = new ArrayList<>();
        }
        this.assets.add(assetsItem);
        return this;
    }

    /**
     * Absolute paths to asset files
     * @return assets
     */
    @jakarta.annotation.Nonnull
    public List<String> getAssets() {
        return assets;
    }

    public void setAssets(@jakarta.annotation.Nonnull List<String> assets) {
        this.assets = assets;
    }

    public RenderingTemplateDefinition instructions(
            @jakarta.annotation.Nonnull String instructions) {
        this.instructions = instructions;
        return this;
    }

    /**
     * The template instructions (markdown)
     * @return instructions
     */
    @jakarta.annotation.Nonnull
    public String getInstructions() {
        return instructions;
    }

    public void setInstructions(@jakarta.annotation.Nonnull String instructions) {
        this.instructions = instructions;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        RenderingTemplateDefinition renderingTemplateDefinition = (RenderingTemplateDefinition) o;
        return Objects.equals(this.id, renderingTemplateDefinition.id)
                && Objects.equals(this.name, renderingTemplateDefinition.name)
                && Objects.equals(this.title, renderingTemplateDefinition.title)
                && Objects.equals(this.description, renderingTemplateDefinition.description)
                && Objects.equals(this.type, renderingTemplateDefinition.type)
                && Objects.equals(this.tags, renderingTemplateDefinition.tags)
                && Objects.equals(this.assets, renderingTemplateDefinition.assets)
                && Objects.equals(this.instructions, renderingTemplateDefinition.instructions);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, name, title, description, type, tags, assets, instructions);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class RenderingTemplateDefinition {\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    title: ").append(toIndentedString(title)).append("\n");
        sb.append("    description: ").append(toIndentedString(description)).append("\n");
        sb.append("    type: ").append(toIndentedString(type)).append("\n");
        sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
        sb.append("    assets: ").append(toIndentedString(assets)).append("\n");
        sb.append("    instructions: ").append(toIndentedString(instructions)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        return o == null ? "null" : o.toString().replace("\n", "\n    ");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields =
                new HashSet<String>(
                        Arrays.asList(
                                "id",
                                "name",
                                "title",
                                "description",
                                "type",
                                "tags",
                                "assets",
                                "instructions"));

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields =
                new HashSet<String>(
                        Arrays.asList(
                                "id", "name", "description", "type", "assets", "instructions"));
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to RenderingTemplateDefinition
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!RenderingTemplateDefinition.openapiRequiredFields
                    .isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(
                        String.format(
                                java.util.Locale.ROOT,
                                "The required field(s) %s in RenderingTemplateDefinition is not found in the empty JSON string",
                                RenderingTemplateDefinition.openapiRequiredFields.toString()));
            }
        }

        // check to make sure all required properties/fields are present in the JSON string
        for (String requiredField : RenderingTemplateDefinition.openapiRequiredFields) {
            if (jsonElement.getAsJsonObject().get(requiredField) == null) {
                throw new IllegalArgumentException(
                        String.format(
                                java.util.Locale.ROOT,
                                "The required field `%s` is not found in the JSON string: %s",
                                requiredField,
                                jsonElement.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if (!jsonObj.get("id").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `id` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("id").toString()));
        }
        if (!jsonObj.get("name").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `name` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("name").toString()));
        }
        if ((jsonObj.get("title") != null && !jsonObj.get("title").isJsonNull())
                && !jsonObj.get("title").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `title` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("title").toString()));
        }
        if (!jsonObj.get("description").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `description` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("description").toString()));
        }
        if (!jsonObj.get("type").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `type` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("type").toString()));
        }
        // validate the required field `type`
        TypeEnum.validateJsonElement(jsonObj.get("type"));
        // ensure the optional json data is an array if present
        if (jsonObj.get("tags") != null
                && !jsonObj.get("tags").isJsonNull()
                && !jsonObj.get("tags").isJsonArray()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `tags` to be an array in the JSON string but got `%s`",
                            jsonObj.get("tags").toString()));
        }
        // ensure the required json array is present
        if (jsonObj.get("assets") == null) {
            throw new IllegalArgumentException(
                    "Expected the field `linkedContent` to be an array in the JSON string but got `null`");
        } else if (!jsonObj.get("assets").isJsonArray()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `assets` to be an array in the JSON string but got `%s`",
                            jsonObj.get("assets").toString()));
        }
        if (!jsonObj.get("instructions").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `instructions` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("instructions").toString()));
        }
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!RenderingTemplateDefinition.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'RenderingTemplateDefinition' and its
                // subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<RenderingTemplateDefinition> thisAdapter =
                    gson.getDelegateAdapter(this, TypeToken.get(RenderingTemplateDefinition.class));

            return (TypeAdapter<T>)
                    new TypeAdapter<RenderingTemplateDefinition>() {
                        @Override
                        public void write(JsonWriter out, RenderingTemplateDefinition value)
                                throws IOException {
                            JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                            elementAdapter.write(out, obj);
                        }

                        @Override
                        public RenderingTemplateDefinition read(JsonReader in) throws IOException {
                            JsonElement jsonElement = elementAdapter.read(in);
                            validateJsonElement(jsonElement);
                            return thisAdapter.fromJsonTree(jsonElement);
                        }
                    }.nullSafe();
        }
    }

    /**
     * Create an instance of RenderingTemplateDefinition given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of RenderingTemplateDefinition
     * @throws IOException if the JSON string is invalid with respect to RenderingTemplateDefinition
     */
    public static RenderingTemplateDefinition fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, RenderingTemplateDefinition.class);
    }

    /**
     * Convert an instance of RenderingTemplateDefinition to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
