/*
 * Vertesia API
 * The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.
 *
 * The version of the OpenAPI document: 1.4.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.vertesia.model;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.vertesia.JSON;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Objects;

/**
 * RunSource
 */
@jakarta.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.22.0")
public class RunSource {
    public static final String SERIALIZED_NAME_TYPE = "type";

    @SerializedName(SERIALIZED_NAME_TYPE)
    @jakarta.annotation.Nonnull
    private RunSourceTypes type;

    public static final String SERIALIZED_NAME_LABEL = "label";

    @SerializedName(SERIALIZED_NAME_LABEL)
    @jakarta.annotation.Nonnull
    private String label;

    /**
     * Gets or Sets principalType
     */
    @JsonAdapter(PrincipalTypeEnum.Adapter.class)
    public enum PrincipalTypeEnum {
        USER("user"),

        OAUTH_ACCESS("oauth_access"),

        GROUP("group"),

        APIKEY("apikey"),

        SERVICE_ACCOUNT("service_account"),

        AGENT("agent"),

        SCHEDULE("schedule"),

        UNKNOWN_DEFAULT_OPEN_API("unknown_default_open_api");

        private String value;

        PrincipalTypeEnum(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        public static PrincipalTypeEnum fromValue(String value) {
            for (PrincipalTypeEnum b : PrincipalTypeEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            return UNKNOWN_DEFAULT_OPEN_API;
        }

        public static class Adapter extends TypeAdapter<PrincipalTypeEnum> {
            @Override
            public void write(final JsonWriter jsonWriter, final PrincipalTypeEnum enumeration)
                    throws IOException {
                jsonWriter.value(enumeration.getValue());
            }

            @Override
            public PrincipalTypeEnum read(final JsonReader jsonReader) throws IOException {
                String value = jsonReader.nextString();
                return PrincipalTypeEnum.fromValue(value);
            }
        }

        public static void validateJsonElement(JsonElement jsonElement) throws IOException {
            String value = jsonElement.getAsString();
            PrincipalTypeEnum.fromValue(value);
        }
    }

    public static final String SERIALIZED_NAME_PRINCIPAL_TYPE = "principal_type";

    @SerializedName(SERIALIZED_NAME_PRINCIPAL_TYPE)
    @jakarta.annotation.Nonnull
    private PrincipalTypeEnum principalType;

    public static final String SERIALIZED_NAME_PRINCIPAL_ID = "principal_id";

    @SerializedName(SERIALIZED_NAME_PRINCIPAL_ID)
    @jakarta.annotation.Nonnull
    private String principalId;

    public static final String SERIALIZED_NAME_CLIENT_IP = "client_ip";

    @SerializedName(SERIALIZED_NAME_CLIENT_IP)
    @jakarta.annotation.Nonnull
    private String clientIp;

    public RunSource() {}

    public RunSource type(@jakarta.annotation.Nonnull RunSourceTypes type) {
        this.type = type;
        return this;
    }

    /**
     * Get type
     * @return type
     */
    @jakarta.annotation.Nonnull
    public RunSourceTypes getType() {
        return type;
    }

    public void setType(@jakarta.annotation.Nonnull RunSourceTypes type) {
        this.type = type;
    }

    public RunSource label(@jakarta.annotation.Nonnull String label) {
        this.label = label;
        return this;
    }

    /**
     * Get label
     * @return label
     */
    @jakarta.annotation.Nonnull
    public String getLabel() {
        return label;
    }

    public void setLabel(@jakarta.annotation.Nonnull String label) {
        this.label = label;
    }

    public RunSource principalType(@jakarta.annotation.Nonnull PrincipalTypeEnum principalType) {
        this.principalType = principalType;
        return this;
    }

    /**
     * Get principalType
     * @return principalType
     */
    @jakarta.annotation.Nonnull
    public PrincipalTypeEnum getPrincipalType() {
        return principalType;
    }

    public void setPrincipalType(@jakarta.annotation.Nonnull PrincipalTypeEnum principalType) {
        this.principalType = principalType;
    }

    public RunSource principalId(@jakarta.annotation.Nonnull String principalId) {
        this.principalId = principalId;
        return this;
    }

    /**
     * Get principalId
     * @return principalId
     */
    @jakarta.annotation.Nonnull
    public String getPrincipalId() {
        return principalId;
    }

    public void setPrincipalId(@jakarta.annotation.Nonnull String principalId) {
        this.principalId = principalId;
    }

    public RunSource clientIp(@jakarta.annotation.Nonnull String clientIp) {
        this.clientIp = clientIp;
        return this;
    }

    /**
     * Get clientIp
     * @return clientIp
     */
    @jakarta.annotation.Nonnull
    public String getClientIp() {
        return clientIp;
    }

    public void setClientIp(@jakarta.annotation.Nonnull String clientIp) {
        this.clientIp = clientIp;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        RunSource runSource = (RunSource) o;
        return Objects.equals(this.type, runSource.type)
                && Objects.equals(this.label, runSource.label)
                && Objects.equals(this.principalType, runSource.principalType)
                && Objects.equals(this.principalId, runSource.principalId)
                && Objects.equals(this.clientIp, runSource.clientIp);
    }

    @Override
    public int hashCode() {
        return Objects.hash(type, label, principalType, principalId, clientIp);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class RunSource {\n");
        sb.append("    type: ").append(toIndentedString(type)).append("\n");
        sb.append("    label: ").append(toIndentedString(label)).append("\n");
        sb.append("    principalType: ").append(toIndentedString(principalType)).append("\n");
        sb.append("    principalId: ").append(toIndentedString(principalId)).append("\n");
        sb.append("    clientIp: ").append(toIndentedString(clientIp)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        return o == null ? "null" : o.toString().replace("\n", "\n    ");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields =
                new HashSet<String>(
                        Arrays.asList(
                                "type", "label", "principal_type", "principal_id", "client_ip"));

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields =
                new HashSet<String>(
                        Arrays.asList(
                                "type", "label", "principal_type", "principal_id", "client_ip"));
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to RunSource
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!RunSource.openapiRequiredFields
                    .isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(
                        String.format(
                                java.util.Locale.ROOT,
                                "The required field(s) %s in RunSource is not found in the empty JSON string",
                                RunSource.openapiRequiredFields.toString()));
            }
        }

        // check to make sure all required properties/fields are present in the JSON string
        for (String requiredField : RunSource.openapiRequiredFields) {
            if (jsonElement.getAsJsonObject().get(requiredField) == null) {
                throw new IllegalArgumentException(
                        String.format(
                                java.util.Locale.ROOT,
                                "The required field `%s` is not found in the JSON string: %s",
                                requiredField,
                                jsonElement.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        // validate the required field `type`
        RunSourceTypes.validateJsonElement(jsonObj.get("type"));
        if (!jsonObj.get("label").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `label` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("label").toString()));
        }
        if (!jsonObj.get("principal_type").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `principal_type` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("principal_type").toString()));
        }
        // validate the required field `principal_type`
        PrincipalTypeEnum.validateJsonElement(jsonObj.get("principal_type"));
        if (!jsonObj.get("principal_id").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `principal_id` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("principal_id").toString()));
        }
        if (!jsonObj.get("client_ip").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `client_ip` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("client_ip").toString()));
        }
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!RunSource.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'RunSource' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<RunSource> thisAdapter =
                    gson.getDelegateAdapter(this, TypeToken.get(RunSource.class));

            return (TypeAdapter<T>)
                    new TypeAdapter<RunSource>() {
                        @Override
                        public void write(JsonWriter out, RunSource value) throws IOException {
                            JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                            elementAdapter.write(out, obj);
                        }

                        @Override
                        public RunSource read(JsonReader in) throws IOException {
                            JsonElement jsonElement = elementAdapter.read(in);
                            validateJsonElement(jsonElement);
                            return thisAdapter.fromJsonTree(jsonElement);
                        }
                    }.nullSafe();
        }
    }

    /**
     * Create an instance of RunSource given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of RunSource
     * @throws IOException if the JSON string is invalid with respect to RunSource
     */
    public static RunSource fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, RunSource.class);
    }

    /**
     * Convert an instance of RunSource to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
