/*
 * Vertesia API
 * The Vertesia API provides project-scoped access to interaction execution and content workflows. Use it to run interactions, inspect execution history, stream run progress, replay previous executions, and search content objects and collections. Authenticate requests with a bearer token, or use the official `@vertesia/client` package for typed access from Node.js applications.
 *
 * The version of the OpenAPI document: 1.6.0-dev
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.vertesia.model;

import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.vertesia.JSON;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/**
 * Per-name resolution result for &#x60;POST /tools/validate&#x60;.
 */
@jakarta.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.22.0")
public class ToolValidationResult {
    public static final String SERIALIZED_NAME_NAME = "name";

    @SerializedName(SERIALIZED_NAME_NAME)
    @jakarta.annotation.Nonnull
    private String name;

    public static final String SERIALIZED_NAME_VALID = "valid";

    @SerializedName(SERIALIZED_NAME_VALID)
    @jakarta.annotation.Nonnull
    private Boolean valid;

    public static final String SERIALIZED_NAME_SOURCE = "source";

    @SerializedName(SERIALIZED_NAME_SOURCE)
    @jakarta.annotation.Nullable private ToolSource source;

    public static final String SERIALIZED_NAME_APP_INSTALL_ID = "app_install_id";

    @SerializedName(SERIALIZED_NAME_APP_INSTALL_ID)
    @jakarta.annotation.Nullable private String appInstallId;

    public static final String SERIALIZED_NAME_APP_NAME = "app_name";

    @SerializedName(SERIALIZED_NAME_APP_NAME)
    @jakarta.annotation.Nullable private String appName;

    public static final String SERIALIZED_NAME_SUGGESTION = "suggestion";

    @SerializedName(SERIALIZED_NAME_SUGGESTION)
    @jakarta.annotation.Nullable private String suggestion;

    public static final String SERIALIZED_NAME_COLLISIONS = "collisions";

    @SerializedName(SERIALIZED_NAME_COLLISIONS)
    @jakarta.annotation.Nullable private List<ToolValidationResultCollisionsInner> collisions = new ArrayList<>();

    public ToolValidationResult() {}

    public ToolValidationResult name(@jakarta.annotation.Nonnull String name) {
        this.name = name;
        return this;
    }

    /**
     * The name the caller asked about.
     * @return name
     */
    @jakarta.annotation.Nonnull
    public String getName() {
        return name;
    }

    public void setName(@jakarta.annotation.Nonnull String name) {
        this.name = name;
    }

    public ToolValidationResult valid(@jakarta.annotation.Nonnull Boolean valid) {
        this.valid = valid;
        return this;
    }

    /**
     * True if the name resolves to exactly one tool in the project&#39;s unified registry.
     * @return valid
     */
    @jakarta.annotation.Nonnull
    public Boolean getValid() {
        return valid;
    }

    public void setValid(@jakarta.annotation.Nonnull Boolean valid) {
        this.valid = valid;
    }

    public ToolValidationResult source(@jakarta.annotation.Nullable ToolSource source) {
        this.source = source;
        return this;
    }

    /**
     * When &#x60;valid&#x60;: which source the tool came from.
     * @return source
     */
    @jakarta.annotation.Nullable public ToolSource getSource() {
        return source;
    }

    public void setSource(@jakarta.annotation.Nullable ToolSource source) {
        this.source = source;
    }

    public ToolValidationResult appInstallId(@jakarta.annotation.Nullable String appInstallId) {
        this.appInstallId = appInstallId;
        return this;
    }

    /**
     * When &#x60;valid&#x60; and &#x60;source &#x3D;&#x3D;&#x3D; &#39;app&#39;&#x60;: the app installation that provides the tool.
     * @return appInstallId
     */
    @jakarta.annotation.Nullable public String getAppInstallId() {
        return appInstallId;
    }

    public void setAppInstallId(@jakarta.annotation.Nullable String appInstallId) {
        this.appInstallId = appInstallId;
    }

    public ToolValidationResult appName(@jakarta.annotation.Nullable String appName) {
        this.appName = appName;
        return this;
    }

    /**
     * When &#x60;valid&#x60; and &#x60;source &#x3D;&#x3D;&#x3D; &#39;app&#39;&#x60;: the app&#39;s manifest name.
     * @return appName
     */
    @jakarta.annotation.Nullable public String getAppName() {
        return appName;
    }

    public void setAppName(@jakarta.annotation.Nullable String appName) {
        this.appName = appName;
    }

    public ToolValidationResult suggestion(@jakarta.annotation.Nullable String suggestion) {
        this.suggestion = suggestion;
        return this;
    }

    /**
     * When &#x60;!valid&#x60; and a close match exists: the suggested replacement name (Levenshtein-based).
     * @return suggestion
     */
    @jakarta.annotation.Nullable public String getSuggestion() {
        return suggestion;
    }

    public void setSuggestion(@jakarta.annotation.Nullable String suggestion) {
        this.suggestion = suggestion;
    }

    public ToolValidationResult collisions(
            @jakarta.annotation.Nullable List<ToolValidationResultCollisionsInner> collisions) {
        this.collisions = collisions;
        return this;
    }

    public ToolValidationResult addCollisionsItem(
            ToolValidationResultCollisionsInner collisionsItem) {
        if (this.collisions == null) {
            this.collisions = new ArrayList<>();
        }
        this.collisions.add(collisionsItem);
        return this;
    }

    /**
     * Populated when a name appears in more than one source. Validation does not fail on this, but exposes the ambiguity so callers can surface a warning (last-write-wins resolution applies).
     * @return collisions
     */
    @jakarta.annotation.Nullable public List<ToolValidationResultCollisionsInner> getCollisions() {
        return collisions;
    }

    public void setCollisions(
            @jakarta.annotation.Nullable List<ToolValidationResultCollisionsInner> collisions) {
        this.collisions = collisions;
    }

    /**
     * A container for additional, undeclared properties.
     * This is a holder for any undeclared properties as specified with
     * the 'additionalProperties' keyword in the OAS document.
     */
    private Map<String, Object> additionalProperties;

    /**
     * Set the additional (undeclared) property with the specified name and value.
     * If the property does not already exist, create it otherwise replace it.
     *
     * @param key name of the property
     * @param value value of the property
     * @return the ToolValidationResult instance itself
     */
    public ToolValidationResult putAdditionalProperty(String key, Object value) {
        if (this.additionalProperties == null) {
            this.additionalProperties = new HashMap<String, Object>();
        }
        this.additionalProperties.put(key, value);
        return this;
    }

    /**
     * Return the additional (undeclared) property.
     *
     * @return a map of objects
     */
    public Map<String, Object> getAdditionalProperties() {
        return additionalProperties;
    }

    /**
     * Return the additional (undeclared) property with the specified name.
     *
     * @param key name of the property
     * @return an object
     */
    public Object getAdditionalProperty(String key) {
        if (this.additionalProperties == null) {
            return null;
        }
        return this.additionalProperties.get(key);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ToolValidationResult toolValidationResult = (ToolValidationResult) o;
        return Objects.equals(this.name, toolValidationResult.name)
                && Objects.equals(this.valid, toolValidationResult.valid)
                && Objects.equals(this.source, toolValidationResult.source)
                && Objects.equals(this.appInstallId, toolValidationResult.appInstallId)
                && Objects.equals(this.appName, toolValidationResult.appName)
                && Objects.equals(this.suggestion, toolValidationResult.suggestion)
                && Objects.equals(this.collisions, toolValidationResult.collisions)
                && Objects.equals(
                        this.additionalProperties, toolValidationResult.additionalProperties);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                name,
                valid,
                source,
                appInstallId,
                appName,
                suggestion,
                collisions,
                additionalProperties);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ToolValidationResult {\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    valid: ").append(toIndentedString(valid)).append("\n");
        sb.append("    source: ").append(toIndentedString(source)).append("\n");
        sb.append("    appInstallId: ").append(toIndentedString(appInstallId)).append("\n");
        sb.append("    appName: ").append(toIndentedString(appName)).append("\n");
        sb.append("    suggestion: ").append(toIndentedString(suggestion)).append("\n");
        sb.append("    collisions: ").append(toIndentedString(collisions)).append("\n");
        sb.append("    additionalProperties: ")
                .append(toIndentedString(additionalProperties))
                .append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        return o == null ? "null" : o.toString().replace("\n", "\n    ");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields =
                new HashSet<String>(
                        Arrays.asList(
                                "name",
                                "valid",
                                "source",
                                "app_install_id",
                                "app_name",
                                "suggestion",
                                "collisions"));

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>(Arrays.asList("name", "valid"));
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to ToolValidationResult
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!ToolValidationResult.openapiRequiredFields
                    .isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(
                        String.format(
                                java.util.Locale.ROOT,
                                "The required field(s) %s in ToolValidationResult is not found in the empty JSON string",
                                ToolValidationResult.openapiRequiredFields.toString()));
            }
        }

        // check to make sure all required properties/fields are present in the JSON string
        for (String requiredField : ToolValidationResult.openapiRequiredFields) {
            if (jsonElement.getAsJsonObject().get(requiredField) == null) {
                throw new IllegalArgumentException(
                        String.format(
                                java.util.Locale.ROOT,
                                "The required field `%s` is not found in the JSON string: %s",
                                requiredField,
                                jsonElement.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if (!jsonObj.get("name").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `name` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("name").toString()));
        }
        // validate the optional field `source`
        if (jsonObj.get("source") != null && !jsonObj.get("source").isJsonNull()) {
            ToolSource.validateJsonElement(jsonObj.get("source"));
        }
        if ((jsonObj.get("app_install_id") != null && !jsonObj.get("app_install_id").isJsonNull())
                && !jsonObj.get("app_install_id").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `app_install_id` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("app_install_id").toString()));
        }
        if ((jsonObj.get("app_name") != null && !jsonObj.get("app_name").isJsonNull())
                && !jsonObj.get("app_name").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `app_name` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("app_name").toString()));
        }
        if ((jsonObj.get("suggestion") != null && !jsonObj.get("suggestion").isJsonNull())
                && !jsonObj.get("suggestion").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            java.util.Locale.ROOT,
                            "Expected the field `suggestion` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("suggestion").toString()));
        }
        if (jsonObj.get("collisions") != null && !jsonObj.get("collisions").isJsonNull()) {
            JsonArray jsonArraycollisions = jsonObj.getAsJsonArray("collisions");
            if (jsonArraycollisions != null) {
                // ensure the json data is an array
                if (!jsonObj.get("collisions").isJsonArray()) {
                    throw new IllegalArgumentException(
                            String.format(
                                    java.util.Locale.ROOT,
                                    "Expected the field `collisions` to be an array in the JSON string but got `%s`",
                                    jsonObj.get("collisions").toString()));
                }

                // validate the optional field `collisions` (array)
                for (int i = 0; i < jsonArraycollisions.size(); i++) {
                    ToolValidationResultCollisionsInner.validateJsonElement(
                            jsonArraycollisions.get(i));
                }
                ;
            }
        }
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!ToolValidationResult.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'ToolValidationResult' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<ToolValidationResult> thisAdapter =
                    gson.getDelegateAdapter(this, TypeToken.get(ToolValidationResult.class));

            return (TypeAdapter<T>)
                    new TypeAdapter<ToolValidationResult>() {
                        @Override
                        public void write(JsonWriter out, ToolValidationResult value)
                                throws IOException {
                            JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                            obj.remove("additionalProperties");
                            // serialize additional properties
                            if (value.getAdditionalProperties() != null) {
                                for (Map.Entry<String, Object> entry :
                                        value.getAdditionalProperties().entrySet()) {
                                    if (entry.getValue() instanceof String)
                                        obj.addProperty(entry.getKey(), (String) entry.getValue());
                                    else if (entry.getValue() instanceof Number)
                                        obj.addProperty(entry.getKey(), (Number) entry.getValue());
                                    else if (entry.getValue() instanceof Boolean)
                                        obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                                    else if (entry.getValue() instanceof Character)
                                        obj.addProperty(
                                                entry.getKey(), (Character) entry.getValue());
                                    else {
                                        JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                                        if (jsonElement.isJsonArray()) {
                                            obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                                        } else {
                                            obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                                        }
                                    }
                                }
                            }
                            elementAdapter.write(out, obj);
                        }

                        @Override
                        public ToolValidationResult read(JsonReader in) throws IOException {
                            JsonElement jsonElement = elementAdapter.read(in);
                            validateJsonElement(jsonElement);
                            JsonObject jsonObj = jsonElement.getAsJsonObject();
                            // store additional fields in the deserialized instance
                            ToolValidationResult instance = thisAdapter.fromJsonTree(jsonObj);
                            for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
                                if (!openapiFields.contains(entry.getKey())) {
                                    if (entry.getValue().isJsonPrimitive()) { // primitive type
                                        if (entry.getValue().getAsJsonPrimitive().isString())
                                            instance.putAdditionalProperty(
                                                    entry.getKey(), entry.getValue().getAsString());
                                        else if (entry.getValue().getAsJsonPrimitive().isNumber())
                                            instance.putAdditionalProperty(
                                                    entry.getKey(), entry.getValue().getAsNumber());
                                        else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                                            instance.putAdditionalProperty(
                                                    entry.getKey(),
                                                    entry.getValue().getAsBoolean());
                                        else
                                            throw new IllegalArgumentException(
                                                    String.format(
                                                            java.util.Locale.ROOT,
                                                            "The field `%s` has unknown primitive type. Value: %s",
                                                            entry.getKey(),
                                                            entry.getValue().toString()));
                                    } else if (entry.getValue().isJsonArray()) {
                                        instance.putAdditionalProperty(
                                                entry.getKey(),
                                                gson.fromJson(entry.getValue(), List.class));
                                    } else { // JSON object
                                        instance.putAdditionalProperty(
                                                entry.getKey(),
                                                gson.fromJson(entry.getValue(), HashMap.class));
                                    }
                                }
                            }
                            return instance;
                        }
                    }.nullSafe();
        }
    }

    /**
     * Create an instance of ToolValidationResult given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of ToolValidationResult
     * @throws IOException if the JSON string is invalid with respect to ToolValidationResult
     */
    public static ToolValidationResult fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, ToolValidationResult.class);
    }

    /**
     * Convert an instance of ToolValidationResult to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
